In [1]:
library(tidyverse)
library(scales)
library(fs)
library(phylotools)

###
Mode <- function(x) {
  ux <- unique(x)
  ux[which.max(tabulate(match(x, ux)))]
}

── Attaching core tidyverse packages ──────────────────────── tidyverse 2.0.0 ──
✔ dplyr     1.1.4     ✔ readr     2.1.4
✔ forcats   1.0.0     ✔ stringr   1.5.1
✔ ggplot2   3.5.2     ✔ tibble    3.3.0
✔ lubridate 1.9.3     ✔ tidyr     1.3.1
✔ purrr     1.0.4
── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
✖ dplyr::filter() masks stats::filter()
✖ dplyr::lag()    masks stats::lag()
ℹ Use the conflicted package (<http://conflicted.r-lib.org/>) to force all conflicts to become errors

Attaching package: ‘scales’


The following object is masked from ‘package:purrr’:

    discard


The following object is masked from ‘package:readr’:

    col_factor


Loading required package: ape


Attaching package: ‘ape’


The following object is masked from ‘package:dplyr’:

    where

In [2]:
getwd()

[1] "/hpc/projects/balla_group/sra_experiments/SRA_metadata/dec2025_75k_submitteradded"

In [3]:
#setwd('/hpc/projects/projects/balla_group/sra_experiments/SRA_metadata/june2025_75k')
workingpath <- getwd()
workingpathdash <- str_c(workingpath, "/")

In [4]:
metadata_curationstep0 <- read_tsv("all_zf_datescurated_withGEO.tsv")

Rows: 77329 Columns: 80
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr  (52): run.accession, study.accession, bioproject, study.title, sample.a...
dbl  (11): run.total_bases, run.total_spots, run.r1_length, run.r2_length, r...
date (17): earliest_date, run.enafirstpublic_date, run.enalastupdate_date, r...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [5]:
## start by removing many of columns from metadata_join5
## remember we use 6 columns for first pass of age stage tissue
## then 20 columns for second & third pass (17 columns second then 3 study columns are third)

## put the primary curation BEFORE run.title

metadata_curationstep1 <- metadata_curationstep0 %>% select(run.accession:earliest_date,experiment.title,experiment.attributes,sample.title,sample.attributes,GEOsample.title,GEOsample.characteristics,run.title,run.alias,run.attributes,experiment.alias,experiment.library_name,experiment.design_description,experiment.library_construction_protocol,sample.description,sample.alias,GEOsample.dataprocessing,GEOsample.source,GEOsample.treatmentprotocol,GEOsample.extractprotocol,GEOsample.growthprotocol,study.abstract,study.attributes)

## Now the dev_stage & tissue calling functions!!


- updated data cleaning function

- updated devstage main function
 
  - but first a more in-depth dev_stage function that searches more terms

- dev_stage_coarse

- tissue

- tissue_coarse

In [6]:
clean_text_columns <- function(df, columns) {
  # Check if all specified columns exist in the dataframe
  if (!all(columns %in% names(df))) {
    stop("Not all specified columns exist in the dataframe")
  }
  
  # Apply cleaning operations to specified columns - late change, convert commas to spaces don't just remove
  df %>%
    ## remove all tildes and parentheses also - & , to spaces (and further down _ to space)
    mutate(across(all_of(columns), ~ gsub("[~()]", "", .))) %>%
    mutate(across(all_of(columns), ~ gsub("-", " ", .))) %>%
    mutate(across(all_of(columns), ~ gsub(",", " ", .))) %>%
    ### adding many mutates from above smaller function for age stage devstage extraction to here as well 50% epi 
    
    # mutate(across(all_of(columns), ~ gsub("(?<=\\d)_(?=\\d)", ".", .))) %>%
    ## for above can't use gsub with lookahead or lookbehind, need to use str_replace
    # Apply the regex to replace underscores surrounded by digits - but first replace numbers after batch also check for day 0 & 0 day
    mutate(across(all_of(columns), ~ gsub("batch1", "batchA", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("batch2", "batchB", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("batch3", "batchC", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("batch4", "batchD", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("batch5", "batchE", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("batch6", "batchF", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("day 0", "day x", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("day0", "day x", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("20 mins post", "0 hours post", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("3 prime", "three prime", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("5 prime", "five prime", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("3'", "three prime", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("5'", "five prime", ., ignore.case = TRUE))) %>%
    # mutate(across(all_of(columns), ~ gsub(" 0 day", "day x", ., ignore.case = TRUE))) %>%
    ## really not sure the next line is a good idea...seems like it breaks a lot of edge cases...
    #mutate(across(all_of(columns), ~ str_replace_all(., "(?<=\\d)_(?=\\d)", "."))) %>% 
    ## first convert underscores before and after numbers to decimal points (?<=\d)_(?=\d) BUT WATCH THINGS LIKE batch2_32hpf_YD Dre_132_6hpf_RPF Dre_155_6hpf_RPF
    mutate(across(all_of(columns), ~ gsub("_", " ", .))) %>%
    mutate(across(all_of(columns), ~ gsub("after", "post", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("BHPF", "BHbisPhenolF", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("heterozygotes", "heterozygous", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("heterozygote", "heterozygous", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("homozygotes", "homozygous", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("homozygote", "homozygous", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("weeks post sham", "wks post sham", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("month F0", "mnth F0", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("post 1 year", "post 1y", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("1 year later", "1y later", ., ignore.case = TRUE))) %>%
    ## note insidious cases where 'injected' or 'exposed' gives additional timepoints that are bad - asking chatGPT to fix these
    ## The regex pattern will capture the phrase "exposed" followed by any number of words and then the word "at" followed by any number, and replace it with "exposed xxx".
    ## modification to keep the words in between str_replace_all(text, "(exposed(?:\\s+\\w+){1,30})\\s+at\\s+\\d+", "\\1 at xxx")
    ## more in august to check "epiboly  hatching  growth" hatching, growth
    ## Aug 6 adding exposed .... from xxx dpf to yyy dpf by adding more terms here (might need to first search for to, then from, also run 2 'to' searches)
    ## check "without head or testis" also "without eyes", "eyes removed" - NOTE REMOVED TERMS ARE FIXED IN TISSUE FUNCTION...also adding checks for multiple numbers at bottom & "xxx post injury"
    mutate(across(all_of(columns), ~ gsub("post hatching", "post hatch", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("50% epi stage", "50% epiboly stage", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("epiboly  hatching  growth", "epibol hatch growth", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hatching gland", "hatch gland", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("post hatching", "post hatch", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hatching rate", "hatch rate", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("million year", "million yr", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("juvinile", "juvenile", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("adulthood", "maturity", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("few year", "few yr", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("65 year", "65 yr", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("recent year", "recent yr", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("many year", "many yr", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("without head or testis", "without xxyy", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("\\b\\w+ post injury\\b", "xxx post injury", ., ignore.case = TRUE))) %>%
    # Regex pattern to match any word following "without"
    # pattern_without <- "(?<=without )\\w+"
    # Use str_replace_all to apply the pattern and replace the matched word with "xxx"
    # result1 <- str_replace_all(text1, pattern, "xxx")
    # result2 <- str_replace_all(text2, pattern, "xxx")
    mutate(across(all_of(columns), ~ str_replace_all(., "(?<=without )\\w+", "xxx"))) %>%
    ## check "exposed to a drug from 1dpf to 5dpf" also adding more weeks & months pf below
    ## some new 2025 additions  post fertilization hour 120
    mutate(across(all_of(columns), ~ gsub("days post heart amputation", "dy post heart amputation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days after genetic ablation", "dy after genetic ablation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days post incubation", "dy post incubation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days post amputation", "dy post amputation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days post single ablation", "dy post single ablation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days post double ablation", "dy post double ablation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days after single ablation", "dy after single ablation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days after double ablation", "dy after double ablation", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("post fertilization hour 120", "120 hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(injection(?:\\s+\\w+){1,30})\\s+at\\s+\\d+", "\\1 at xxx"))) %>%
    ## many possible epiboly - only 30% is blastula rest are gastrula  - so replace these with zfs:0000015 30percent_epiboly 30epiboly  30% epiboly 30%-epiboly 15%-epiboly dome-to-epiboly
    ## also some non numeric epiboly affected epiboly impaired epiboly both epiboly perturbed epiboly at epiboly in epiboly of epiboly on epiboly to epiboly 75epibolu
    ## 1cell stage embryos were injected
    mutate(across(all_of(columns), ~ gsub("dome to epiboly", "dome to epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("affected epiboly", "affected epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("impaired epiboly", "impaired epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("both epiboly", "both epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("perturbed epiboly", "perturbed epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("at epiboly", "at epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("in epiboly", "in epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("of epiboly", "of epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("on epiboly", "on epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("to epiboly", "to epib", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("30percent epiboly", "zfs:0000015", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("30epiboly", "zfs:0000015", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("30% epiboly", "zfs:0000015", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("15% epiboly", "zfs:0000015", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("epibolu", "epiboly", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("90d pfa", "90 days", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("moths", "months", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("1cell stage embryos were injected", "1c embryos were injected", ., ignore.case = TRUE))) %>%
    ## rest from 2024 
    mutate(across(all_of(columns), ~ str_replace_all(., "(exposed(?:\\s+\\w+){1,30})\\s+at\\s+\\d+", "\\1 at xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(exposed(?:\\s+\\w+){1,30})\\s+for\\s+\\d+", "\\1 for xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(exposed(?:\\s+\\w+){1,30})\\s+to\\s+\\d+", "\\1 ttwo xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(exposed(?:\\s+\\w+){1,30})\\s+to\\s+\\d+", "\\1 to xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(exposed(?:\\s+\\w+){1,30})\\s+from\\s+\\d+", "\\1 from xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(injected(?:\\s+\\w+){1,30})\\s+at\\s+\\d+", "\\1 at xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(injected(?:\\s+\\w+){1,30})\\s+for\\s+\\d+", "\\1 for xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(injected(?:\\s+\\w+){1,30})\\s+to\\s+\\d+", "\\1 ttwo xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(injected(?:\\s+\\w+){1,30})\\s+to\\s+\\d+", "\\1 to xxx"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(injected(?:\\s+\\w+){1,30})\\s+from\\s+\\d+", "\\1 from xxx"))) %>%
    mutate(across(all_of(columns), ~ gsub("oocytes microinject", "microinject", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("oocyte microinject", "microinject", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("seven somite", "7 somite", ., ignore.case = TRUE))) %>%
    ## stressed 21 days
    mutate(across(all_of(columns), ~ gsub("stressed 21 days", "stressed", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("mothes", "months", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("age:6 mouths", "age:6 months", ., ignore.case = TRUE))) %>%
    ## ArrayExpress Age:2 days
    mutate(across(all_of(columns), ~ gsub("ArrayExpress Age:2 days", "age:2 days", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("injected at one", "injected at a", ., ignore.case = TRUE))) %>%
    # mutate(across(all_of(columns), ~ gsub("injected at 1", "injected at a", ., ignore.case = TRUE))) %>% # previous line should catch 
    mutate(across(all_of(columns), ~ gsub("hour old", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hours old", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("day old", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days old", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("week old", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("weeks old", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("month old", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("months old", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("post post", "post", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("d post fert[^ ]*", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("day post fert[^ ]*", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days post fert[^ ]*", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("w post fert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("week post fert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("weeks post fert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("wk post fert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("wks post fert[^ ]*", "wpf", ., ignore.case = TRUE))) %>% 
    mutate(across(all_of(columns), ~ gsub("m post fert[^ ]*", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("month post fert[^ ]*", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("months post fert[^ ]*", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("w postfert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("week postfert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("weeks postfert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("wk postfert[^ ]*", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("wks postfert[^ ]*", "wpf", ., ignore.case = TRUE))) %>% 
    mutate(across(all_of(columns), ~ gsub("m postfert[^ ]*", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("month postfert[^ ]*", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("months postfert[^ ]*", "mpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("d postfert[^ ]*", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("day postfert[^ ]*", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("days postfert[^ ]*", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("h post fert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hour post fert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hours post fert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hr post fert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hrs post fert[^ ]*", "hpf", ., ignore.case = TRUE))) %>% 
    mutate(across(all_of(columns), ~ gsub("h postfert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hour postfert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hours postfert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hr postfert[^ ]*", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hrs postfert[^ ]*", "hpf", ., ignore.case = TRUE))) %>% 
    mutate(across(all_of(columns), ~ str_replace_all(., "(\\d+) to (\\d+) (hpf|hfp|wpf|dfp|dpf|month|mpf)", "\\1 \\3 to \\2 \\3"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(\\d+)(?=(?: \\d+)*(?: and \\d+ (hpf|hfp|wpf|dfp|dpf|month|mpf)))", "\\1 \\2"))) %>%
    mutate(across(all_of(columns), ~ str_replace_all(., "(\\d+)(?=(?: \\d+)* (hpf|hfp|wpf|dfp|dpf|month|mpf))", "\\1 \\2"))) %>% 
    mutate(across(all_of(columns), ~ gsub("hpf hpf hpf", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hpf hpf", "hpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("dpf dpf", "dpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("wpf wpf", "wpf", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("month months", "month", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("month month", "month", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("hfp hfp", "hfp", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("dfp dfp", "dfp", ., ignore.case = TRUE))) %>%
    mutate(across(all_of(columns), ~ gsub("mpf mpf", "mpf", ., ignore.case = TRUE)))
  
  # mutate(across(all_of(columns), tolower))
}

In [7]:
classify_stage2025first <- function(entry) {
  classifications <- c()
  # First - Replace dashes with spaces in the entry - instead doing this & rest in separate function clean_text_columns (but keeping basic dash replace just in case)-
  entry <- gsub("-", " ", entry)
  # ## fix post-fertilization - use agrep?? post fertilization - instead simpler fix (but add \s ??)
  # Regex pattern to match a number immediately before or after "hpf", "hfp", "week", or "wpf"
  ## if I add h at end need to also add it here
    ## for first stage ONLY adding both singlular and plural
  # plus h only when followed by | or end "(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf|h(?=\\||$))", also adding d at very end
#  pattern <- "(\\d+(\\.\\d+)?\\s*(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf))|((hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf)\\s*\\d+(\\.\\d+)?)"
  pattern <- "(\\d+(\\.\\d+)?\\s*(hpf|hfp|week|wpf|day|dfp|dpf|pdf|epiboly|hours|hrs|somite|month|weeks|days|hour|months|mpf|d(?=\\||$)|h(?=\\||$)))|((hpf|hfp|week|wpf|day|dfp|dpf|pdf|epiboly|hours|hrs|somite|month|weeks|days|hour|months|mpf|d(?=\\||$)|h(?=\\||$))\\s*\\d+(\\.\\d+)?)"
  
  # Use regmatches and regexpr to find and extract the matched pattern - moved to further down
  # matches <- regmatches(entry, regexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))
  

  ## first more basic grep searches - CHECK SOME OF THESE, MAY NOT WANT TO INCLUDE MORE GENERAL KEYWORDS...   15% epiboly 30% epiboly also move adult first, most likely to be additional term
  ## remove adult here, only adding to coarse category if not otherwise found
  # if (grepl("adult", entry, ignore.case = TRUE) == TRUE | grepl("mpf", entry, ignore.case = TRUE) == TRUE | grepl("month", entry, ignore.case = TRUE) == TRUE | grepl("year", entry, ignore.case = TRUE) == TRUE) {
  #   return("Adult Period")
  # }
  ## similarly add month & year to coarse category - also at this point 6/11 removing 'day' from keywords...could be
  ### moving mpf to numbers because 1-3 is juvenile, only leaving if undetermined in coarse
  ### also do same for juvenile & larval larva larvae - also removing 'cleavage', can be general term
  ## fixing 00044 to adult, removig 00045 00046 00047 which are only used with earlier stages
  ## aug 1 changing all else if to if - 'shield' and 'oblong' were not being caught??
  if (grepl("zfs:0000044", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Adult")
  }
  if (grepl("zygote", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000001", entry, ignore.case = TRUE) == TRUE | grepl("unfertilized", entry, ignore.case = TRUE) == TRUE | grepl("sperm ", entry, ignore.case = TRUE) == TRUE | grepl("spermatozoa", entry, ignore.case = TRUE) == TRUE | grepl("zygote", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Zygote")
  }
  if (grepl("zfs:0000002", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000003", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000004", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000005", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000006", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000007", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cleavage")
  }
  if (grepl("blastula", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000008", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000009", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000010", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000011", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000012", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000013", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000014", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000015", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000016", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Blastula")
  }
  if (grepl("gastrula", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000017", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000018", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000019", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000020", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000021", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000022", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  if (grepl("somite", entry, ignore.case = TRUE) == TRUE | grepl("segmentation", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000049", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000023", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000024", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000025", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000026", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000027", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000028", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Segmentation")
  }
  if (grepl("pharyngula", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000050", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000029", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000030", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000031", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000032", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pharyngula")
  }
  if (grepl("hatching", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0007000", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000033", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000034", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hatching")
  }
  if (grepl("protruding mouth", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000048", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000035", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000036", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000037", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000038", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000039", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000040", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000041", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Larval")
  }
  if (grepl("zfs:0000051", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000042", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000043", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Juvenile")
  }
  # if (grepl("10% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("15% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("20% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("25% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("30% epiboly", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Blastula")
  # }
  ## after above new gsubs, any remaining epiboly is Gastrula
  if (grepl("epiboly", entry, ignore.case = TRUE) == TRUE | grepl("germ ring", entry, ignore.case = TRUE) == TRUE | grepl("shield stage", entry, ignore.case = TRUE) == TRUE | grepl("bud stage", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  # if (grepl("50% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("55% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("60% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("65% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("70% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("75% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("80% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("85% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("90% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("germ ring", entry, ignore.case = TRUE) == TRUE | grepl("shield stage", entry, ignore.case = TRUE) == TRUE | grepl("bud stage", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Gastrula")
  # }
  
  ## also adding prim and pec
  if (grepl("prim 5", entry, ignore.case = TRUE) == TRUE | grepl("prim 15", entry, ignore.case = TRUE) == TRUE | grepl("prim 25", entry, ignore.case = TRUE) == TRUE | 
      grepl("prim5", entry, ignore.case = TRUE) == TRUE  | grepl("prim15", entry, ignore.case = TRUE) == TRUE  | grepl("prim25", entry, ignore.case = TRUE) == TRUE  | grepl("high pec", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pharyngula")
  }
  if (grepl("long pec", entry, ignore.case = TRUE) == TRUE | grepl("pec fin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hatching")
  }
  
  # # Use regmatches and regexpr to find and extract the matched pattern - moved to further down
  # matches <- regmatches(entry, regexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))
  
  # JUNE 2025 UPDATE - TO FIND ALL OF THE MATCHES
#  3) Extract *all* the matches
  #all_matches <- regmatches(entry,gregexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))[[1]]
  all_matches <- regmatches(entry,gregexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))[[1]]
  
  

  # Check if any match was found if (length(all_matches) > 0 && nzchar(all_matches[1]))
#  if (length(matches) > 0 && nzchar(matches)) {
#  if (length(matches) > 0 && nzchar(matches[1])) {
    # Extract the number from the match
    # num <- as.numeric(unlist(regmatches(matches, gregexpr("\\d+\\.?\\d*", matches))))
    # 
    # # Classification based on the number and keywords
    # if (!is.na(num)) {
    #   # Determine the keyword involved for specific classification
    #   keyword <- tolower(unlist(regmatches(matches, gregexpr("(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf)", matches, ignore.case = TRUE))))

  if (length(all_matches) > 0 && nzchar(all_matches[1])) {
    for (m in all_matches) {
      # extract the numeric part
      num <- as.numeric(
        unlist(regmatches(m, gregexpr("\\d+\\.?\\d*", m)))
      )
      if (is.na(num)) next
      
      # extract the keyword
      ## plus h only when followed by | or end "(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf|h(?=\\||$))",
#      keyword <- tolower(unlist(regmatches(m,gregexpr("(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf)",m, ignore.case = TRUE))))
      ## Both 96 h and 7h will result in keyword == "h". d(?=\\||$)|
        ## for first stage ONLY adding both singlular and plural
      keyword <- tolower(unlist(regmatches(m,gregexpr("(hpf|hfp|week|wpf|day|dfp|dpf|pdf|epiboly|hours|hrs|somite|month|weeks|days|hour|months|mpf|d(?=\\||$)|h(?=\\||$))",m, ignore.case = TRUE, perl = TRUE))))
      
      # Classify based on hours - but don't use just hour or hours, see above for combining if 'post-fert' is seen
      ## NEED TO FIX ALL LIKE if (num < 2.25 && num > 0.75) {
      ### NOTE 2025 MAKE 2 VERSIONS OF THIS - ONE WITH MORE KEYWORDS IN NEXT CHUNKS - include hour hrs maybe also h$
      if (any(keyword %in% c("hpf", "hfp", "hours", "hour", "h"))) {
        if (num < 0.75) classifications <- c(classifications, "Zygote")
        if (num < 2.25 && num >= 0.75) classifications <- c(classifications, "Cleavage")
        if (num < 5.25 && num >= 2.25) classifications <- c(classifications, "Blastula")
        if (num < 10.33 && num >= 5.25) classifications <- c(classifications, "Gastrula")
        if (num < 24 && num >= 10.33) classifications <- c(classifications, "Segmentation")
        if (num < 48 && num >= 24) classifications <- c(classifications, "Pharyngula")
        if (num < 72 && num >= 48) classifications <- c(classifications, "Hatching")
        if (num < 720 && num >= 72) classifications <- c(classifications, "Larval")
        #classifications <- c(classifications, "Adult")
      }
      
      # Classify based on days
      if (any(keyword %in% c("dpf", "dfp", "day", "days", "pdf", "d"))) {
        if (num < 0.2) classifications <- c(classifications, "Blastula")
        if (num < 0.4 && num >= 0.2) classifications <- c(classifications, "Gastrula")
        if (num < 1 && num >= 0.4) classifications <- c(classifications, "Segmentation")
        if (num < 2 && num >= 1) classifications <- c(classifications, "Pharyngula")
        if (num < 3 && num >= 2) classifications <- c(classifications, "Hatching")
        if (num < 30 && num >= 3) classifications <- c(classifications, "Larval")
        if (num < 90 && num >= 30) classifications <- c(classifications, "Juvenile")
        if (num < 990 && num >= 90) classifications <- c(classifications, "Adult")
        #classifications <- c(classifications, "Adult")
      }
      
      # Classify based on "week" or "wpf"
      if (any(keyword %in% c("week", "weeks", "wpf"))) {
        if (num < 4.29) classifications <- c(classifications, "Larval")
        if (num < 12.86 && num >= 4.29) classifications <- c(classifications, "Juvenile")
        if (num < 199 && num >= 12.86) classifications <- c(classifications, "Adult")
        #classifications <- c(classifications, "Adult")
      }
      # moving month to numbers because 1-3 is juvenile, only leaving if undetermined in coarse
      if (any(keyword %in% c("month", "months", "mpf"))) {
        if (num < 1) classifications <- c(classifications, "Larval")
        if (num < 3 && num >= 1) classifications <- c(classifications, "Juvenile")
        if (num < 99 && num >= 3) classifications <- c(classifications, "Adult")
        #classifications <- c(classifications, "Adult")
      }
      
    }
  }
  
  ## bringing back a few of these 7/16/24 ADDING LAST!!, also oocyte adding last here - many from PRJNA529241
  ## aug 1 adding back dome, shield, tailbud, some cells be careful with zf4
  if (grepl("128/256 cell", entry, ignore.case = TRUE) == TRUE | grepl("\\bdome\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("1k cell", entry, ignore.case = TRUE) == TRUE | grepl("\\b1000 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b1000cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("oblong", entry, ignore.case = TRUE) == TRUE | grepl("\\bsphere\\b", entry, ignore.case = TRUE) == TRUE | grepl(" sphere", entry, ignore.case = TRUE) == TRUE | grepl("WT 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("1Kc p300", entry, ignore.case = TRUE) == TRUE | grepl("1Kc trip", entry, ignore.case = TRUE) == TRUE | grepl("a Am 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("TinyLNA430 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("a Am 256c", entry, ignore.case = TRUE) == TRUE | grepl("2N 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("a Am 512c", entry, ignore.case = TRUE) == TRUE | grepl("1N 512c", entry, ignore.case = TRUE) == TRUE | grepl("WT 256c", entry, ignore.case = TRUE) == TRUE | grepl("WT dome", entry, ignore.case = TRUE) == TRUE | grepl("1Kcell", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Blastula")
  }
  if (grepl("a Am 75%epi", entry, ignore.case = TRUE) == TRUE | grepl("shield", entry, ignore.case = TRUE) == TRUE | grepl("WT 50%epi", entry, ignore.case = TRUE) == TRUE | grepl("WT 75%epi", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  ## adding shield as a full word here almost last for blastula "\\bshield\\b" just bfore zygote
  if (grepl("\\bshield\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\btailbud\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  if (grepl("\\b1cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("oocyte", entry, ignore.case = TRUE) == TRUE | grepl("WT 1c", entry, ignore.case = TRUE) == TRUE | grepl("a Am 1c", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Zygote")
  }
  ## note "2 cell" has to be after "512 cell" - FIXING ALL IN AUGUST WITH \\B, 4 can get both 4 and 64 though (not 4 because zf4 also will ping), also for zygote remvoing "1 cell" only keeping 1cell
  if (grepl("\\b4 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b4cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b4 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b4cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("16/32 cell", entry, ignore.case = TRUE) == TRUE | grepl("16 cell", entry, ignore.case = TRUE) == TRUE | grepl("64 cell", entry, ignore.case = TRUE) == TRUE | grepl("16cell", entry, ignore.case = TRUE) == TRUE | grepl("64cell", entry, ignore.case = TRUE) == TRUE | grepl("WT 2c", entry, ignore.case = TRUE) == TRUE | grepl("WT 4c", entry, ignore.case = TRUE) == TRUE | grepl("a Am 16c", entry, ignore.case = TRUE) == TRUE | grepl("WT 64c", entry, ignore.case = TRUE) == TRUE | grepl("WT 32c", entry, ignore.case = TRUE) == TRUE | grepl("TinyLNA430 64c", entry, ignore.case = TRUE) == TRUE | grepl("a Am 64c", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cleavage")
  }
  ## also adding adult larva juvenile terms from coarse function here, only embryo will be added at coarse now
  ## move larvae to ONLY in coarse, hundreds of cases where it gets added even though hpf shows it as embryo - BETTER IDEA, HAVE THESE INSIDE A  if (length(classifications) == 0) { STATEMENT!!
  if (length(classifications) == 0) {
    if (grepl("adult", entry, ignore.case = TRUE) == TRUE | grepl("age:1y", entry, ignore.case = TRUE) == TRUE | grepl("three month", entry, ignore.case = TRUE) == TRUE | grepl("three mpf", entry, ignore.case = TRUE) == TRUE | grepl("four month", entry, ignore.case = TRUE) == TRUE | grepl("four mpf", entry, ignore.case = TRUE) == TRUE | grepl("five month", entry, ignore.case = TRUE) == TRUE | grepl("five mpf", entry, ignore.case = TRUE) == TRUE | grepl("six month", entry, ignore.case = TRUE) == TRUE | grepl("six mpf", entry, ignore.case = TRUE) == TRUE | grepl("seven month", entry, ignore.case = TRUE) == TRUE | grepl("seven mpf", entry, ignore.case = TRUE) == TRUE | grepl("eight month", entry, ignore.case = TRUE) == TRUE | grepl("eight mpf", entry, ignore.case = TRUE) == TRUE | grepl("natal month three", entry, ignore.case = TRUE) == TRUE | grepl("year", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Adult")
    }
    if (grepl("larva", entry, ignore.case = TRUE) == TRUE | grepl("larval", entry, ignore.case = TRUE) == TRUE | grepl("larvae", entry, ignore.case = TRUE) == TRUE | grepl("eleutherolarva", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Larval")
    }
    if (grepl("juvenile", entry, ignore.case = TRUE) == TRUE | grepl("one month", entry, ignore.case = TRUE) == TRUE | grepl("two months", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Juvenile")
    }
  }
  
  if (length(classifications) == 0) {
    return("Undetermined")
  } else {
    # Split the string into words
    words <- unlist(strsplit(classifications, " "))
    # Remove duplicate words
    unique_words <- unique(words)
    # Combine the unique words back into a single string
    classifications <- paste(unique_words, collapse = ", ")
    return(paste(classifications, collapse = ", "))
  }
}

In [8]:
classify_stage2025 <- function(entry) {
  classifications <- c()
  # First - Replace dashes with spaces in the entry - instead doing this & rest in separate function clean_text_columns (but keeping basic dash replace just in case)-
  entry <- gsub("-", " ", entry)
  # ## fix post-fertilization - use agrep?? post fertilization - instead simpler fix (but add \s ??)
  # Regex pattern to match a number immediately before or after "hpf", "hfp", "week", or "wpf"
  ## if I add h at end need to also add it here
  # plus h only when followed by | or end "(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf|h(?=\\||$))",
  #  pattern <- "(\\d+(\\.\\d+)?\\s*(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf))|((hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf)\\s*\\d+(\\.\\d+)?)"
  pattern <- "(\\d+(\\.\\d+)?\\s*(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hours|hrs|somite|month|mpf|h(?=\\||$)))|((hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hours|hrs|somite|month|mpf|h(?=\\||$))\\s*\\d+(\\.\\d+)?)"
  
  # Use regmatches and regexpr to find and extract the matched pattern - moved to further down
  # matches <- regmatches(entry, regexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))
  
  
  ## first more basic grep searches - CHECK SOME OF THESE, MAY NOT WANT TO INCLUDE MORE GENERAL KEYWORDS...   15% epiboly 30% epiboly also move adult first, most likely to be additional term
  ## remove adult here, only adding to coarse category if not otherwise found
  # if (grepl("adult", entry, ignore.case = TRUE) == TRUE | grepl("mpf", entry, ignore.case = TRUE) == TRUE | grepl("month", entry, ignore.case = TRUE) == TRUE | grepl("year", entry, ignore.case = TRUE) == TRUE) {
  #   return("Adult Period")
  # }
  ## similarly add month & year to coarse category - also at this point 6/11 removing 'day' from keywords...could be
  ### moving mpf to numbers because 1-3 is juvenile, only leaving if undetermined in coarse
  ### also do same for juvenile & larval larva larvae - also removing 'cleavage', can be general term
  ## fixing 00044 to adult, removig 00045 00046 00047 which are only used with earlier stages
  ## aug 1 changing all else if to if - 'shield' and 'oblong' were not being caught??
  if (grepl("zfs:0000044", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Adult")
  }
  if (grepl("zygote", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000001", entry, ignore.case = TRUE) == TRUE | grepl("unfertilized", entry, ignore.case = TRUE) == TRUE | grepl("sperm ", entry, ignore.case = TRUE) == TRUE | grepl("spermatozoa", entry, ignore.case = TRUE) == TRUE | grepl("zygote", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Zygote")
  }
  if (grepl("zfs:0000002", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000003", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000004", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000005", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000006", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000007", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cleavage")
  }
  if (grepl("blastula", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000008", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000009", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000010", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000011", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000012", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000013", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000014", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000015", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000016", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Blastula")
  }
  if (grepl("gastrula", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000017", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000018", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000019", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000020", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000021", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000022", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  if (grepl("somite", entry, ignore.case = TRUE) == TRUE | grepl("segmentation", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000049", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000023", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000024", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000025", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000026", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000027", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000028", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Segmentation")
  }
  if (grepl("pharyngula", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000050", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000029", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000030", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000031", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000032", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pharyngula")
  }
  if (grepl("hatching", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0007000", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000033", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000034", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hatching")
  }
  if (grepl("protruding mouth", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000048", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000035", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000036", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000037", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000038", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000039", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000040", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000041", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Larval")
  }
  if (grepl("zfs:0000051", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000042", entry, ignore.case = TRUE) == TRUE | grepl("zfs:0000043", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Juvenile")
  }
  # if (grepl("10% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("15% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("20% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("25% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("30% epiboly", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Blastula")
  # }
  ## after above new gsubs, any remaining epiboly is Gastrula
  if (grepl("epiboly", entry, ignore.case = TRUE) == TRUE | grepl("germ ring", entry, ignore.case = TRUE) == TRUE | grepl("shield stage", entry, ignore.case = TRUE) == TRUE | grepl("bud stage", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  # if (grepl("50% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("55% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("60% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("65% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("70% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("75% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("80% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("85% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("90% epiboly", entry, ignore.case = TRUE) == TRUE | grepl("germ ring", entry, ignore.case = TRUE) == TRUE | grepl("shield stage", entry, ignore.case = TRUE) == TRUE | grepl("bud stage", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Gastrula")
  # }
  
  ## also adding prim and pec
  if (grepl("prim 5", entry, ignore.case = TRUE) == TRUE | grepl("prim 15", entry, ignore.case = TRUE) == TRUE | grepl("prim 25", entry, ignore.case = TRUE) == TRUE | 
      grepl("prim5", entry, ignore.case = TRUE) == TRUE  | grepl("prim15", entry, ignore.case = TRUE) == TRUE  | grepl("prim25", entry, ignore.case = TRUE) == TRUE  | grepl("high pec", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pharyngula")
  }
  if (grepl("long pec", entry, ignore.case = TRUE) == TRUE | grepl("pec fin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hatching")
  }
  
  # # Use regmatches and regexpr to find and extract the matched pattern - moved to further down
  # matches <- regmatches(entry, regexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))
  
  # JUNE 2025 UPDATE - TO FIND ALL OF THE MATCHES
  #  3) Extract *all* the matches
  #all_matches <- regmatches(entry,gregexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))[[1]]
  all_matches <- regmatches(entry,gregexpr(pattern, entry, ignore.case = TRUE, perl = TRUE))[[1]]
  
  
  
  # Check if any match was found if (length(all_matches) > 0 && nzchar(all_matches[1]))
  #  if (length(matches) > 0 && nzchar(matches)) {
  #  if (length(matches) > 0 && nzchar(matches[1])) {
  # Extract the number from the match
  # num <- as.numeric(unlist(regmatches(matches, gregexpr("\\d+\\.?\\d*", matches))))
  # 
  # # Classification based on the number and keywords
  # if (!is.na(num)) {
  #   # Determine the keyword involved for specific classification
  #   keyword <- tolower(unlist(regmatches(matches, gregexpr("(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf)", matches, ignore.case = TRUE))))
  
  if (length(all_matches) > 0 && nzchar(all_matches[1])) {
    for (m in all_matches) {
      # extract the numeric part
      num <- as.numeric(
        unlist(regmatches(m, gregexpr("\\d+\\.?\\d*", m)))
      )
      if (is.na(num)) next
      
      # extract the keyword
      ## plus h only when followed by | or end "(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf|h(?=\\||$))",
      #      keyword <- tolower(unlist(regmatches(m,gregexpr("(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hour|hrs|somite|month|mpf)",m, ignore.case = TRUE))))
      ## Both 96 h and 7h will result in keyword == "h".
      keyword <- tolower(unlist(regmatches(m,gregexpr("(hpf|hfp|week|wpf|day|dfp|dpf|epiboly|hours|hrs|somite|month|mpf|h(?=\\||$))",m, ignore.case = TRUE, perl = TRUE))))
      
      # Classify based on hours - but don't use just hour or hours, see above for combining if 'post-fert' is seen
      ## NEED TO FIX ALL LIKE if (num < 2.25 && num > 0.75) {
      ### NOTE 2025 MAKE 2 VERSIONS OF THIS - ONE WITH MORE KEYWORDS IN NEXT CHUNKS - include hour hrs maybe also h$
      if (any(keyword %in% c("hpf", "hfp"))) {
        if (num < 0.75) classifications <- c(classifications, "Zygote")
        if (num < 2.25 && num >= 0.75) classifications <- c(classifications, "Cleavage")
        if (num < 5.25 && num >= 2.25) classifications <- c(classifications, "Blastula")
        if (num < 10.33 && num >= 5.25) classifications <- c(classifications, "Gastrula")
        if (num < 24 && num >= 10.33) classifications <- c(classifications, "Segmentation")
        if (num < 48 && num >= 24) classifications <- c(classifications, "Pharyngula")
        if (num < 72 && num >= 48) classifications <- c(classifications, "Hatching")
        if (num < 720 && num >= 72) classifications <- c(classifications, "Larval")
        #classifications <- c(classifications, "Adult")
      }
      
      # Classify based on days
      if (any(keyword %in% c("dpf", "dfp"))) {
        if (num < 0.2) classifications <- c(classifications, "Blastula")
        if (num < 0.4 && num >= 0.2) classifications <- c(classifications, "Gastrula")
        if (num < 1 && num >= 0.4) classifications <- c(classifications, "Segmentation")
        if (num < 2 && num >= 1) classifications <- c(classifications, "Pharyngula")
        if (num < 3 && num >= 2) classifications <- c(classifications, "Hatching")
        if (num < 30 && num >= 3) classifications <- c(classifications, "Larval")
        if (num < 90 && num >= 30) classifications <- c(classifications, "Juvenile")
        if (num < 990 && num >= 90) classifications <- c(classifications, "Adult")
        #classifications <- c(classifications, "Adult")
      }
      
      # Classify based on "week" or "wpf"
      if (any(keyword %in% c("week", "wpf"))) {
        if (num < 4.29) classifications <- c(classifications, "Larval")
        if (num < 12.86 && num >= 4.29) classifications <- c(classifications, "Juvenile")
        if (num < 199 && num >= 12.86) classifications <- c(classifications, "Adult")
        #classifications <- c(classifications, "Adult")
      }
      # moving month to numbers because 1-3 is juvenile, only leaving if undetermined in coarse
      if (any(keyword %in% c("month", "mpf"))) {
        if (num < 1) classifications <- c(classifications, "Larval")
        if (num < 3 && num >= 1) classifications <- c(classifications, "Juvenile")
        if (num < 99 && num >= 3) classifications <- c(classifications, "Adult")
        #classifications <- c(classifications, "Adult")
      }
      
    }
  }
  
  ## bringing back a few of these 7/16/24 ADDING LAST!!, also oocyte adding last here
  ## aug 1 adding back dome, shield, tailbud, some cells be careful with zf4
  if (grepl("128/256 cell", entry, ignore.case = TRUE) == TRUE | grepl("\\bdome\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b512cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b128cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b256cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("1k cell", entry, ignore.case = TRUE) == TRUE | grepl("\\b1000 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b1000cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("oblong", entry, ignore.case = TRUE) == TRUE | grepl("\\bsphere\\b", entry, ignore.case = TRUE) == TRUE | grepl(" sphere", entry, ignore.case = TRUE) == TRUE | grepl("WT 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("1Kc p300", entry, ignore.case = TRUE) == TRUE | grepl("1Kc trip", entry, ignore.case = TRUE) == TRUE | grepl("a Am 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("TinyLNA430 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("a Am 256c", entry, ignore.case = TRUE) == TRUE | grepl("2N 1Kc", entry, ignore.case = TRUE) == TRUE | grepl("a Am 512c", entry, ignore.case = TRUE) == TRUE | grepl("1N 512c", entry, ignore.case = TRUE) == TRUE | grepl("WT 256c", entry, ignore.case = TRUE) == TRUE | grepl("WT dome", entry, ignore.case = TRUE) == TRUE | grepl("1Kcell", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Blastula")
  }
  if (grepl("a Am 75%epi", entry, ignore.case = TRUE) == TRUE | grepl("shield", entry, ignore.case = TRUE) == TRUE | grepl("WT 50%epi", entry, ignore.case = TRUE) == TRUE | grepl("WT 75%epi", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  ## adding shield as a full word here almost last for blastula "\\bshield\\b" just bfore zygote
  if (grepl("\\bshield\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\btailbud\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gastrula")
  }
  if (grepl("\\b1cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("oocyte", entry, ignore.case = TRUE) == TRUE | grepl("WT 1c", entry, ignore.case = TRUE) == TRUE | grepl("a Am 1c", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Zygote")
  }
  ## note "2 cell" has to be after "512 cell" - FIXING ALL IN AUGUST WITH \\B, 4 can get both 4 and 64 though (not 4 because zf4 also will ping), also for zygote remvoing "1 cell" only keeping 1cell
  if (grepl("\\b4 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b4cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8 cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8cell\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b4 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b4cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b2cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b32cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8 cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\b8cells\\b", entry, ignore.case = TRUE) == TRUE | grepl("16/32 cell", entry, ignore.case = TRUE) == TRUE | grepl("16 cell", entry, ignore.case = TRUE) == TRUE | grepl("64 cell", entry, ignore.case = TRUE) == TRUE | grepl("16cell", entry, ignore.case = TRUE) == TRUE | grepl("64cell", entry, ignore.case = TRUE) == TRUE | grepl("WT 2c", entry, ignore.case = TRUE) == TRUE | grepl("WT 4c", entry, ignore.case = TRUE) == TRUE | grepl("a Am 16c", entry, ignore.case = TRUE) == TRUE | grepl("WT 64c", entry, ignore.case = TRUE) == TRUE | grepl("WT 32c", entry, ignore.case = TRUE) == TRUE | grepl("TinyLNA430 64c", entry, ignore.case = TRUE) == TRUE | grepl("a Am 64c", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cleavage")
  }
  ## also adding adult larva juvenile terms from coarse function here, only embryo will be added at coarse now
  ## move larvae to ONLY in coarse, hundreds of cases where it gets added even though hpf shows it as embryo - BETTER IDEA, HAVE THESE INSIDE A  if (length(classifications) == 0) { STATEMENT!!
  if (length(classifications) == 0) {
    if (grepl("adult", entry, ignore.case = TRUE) == TRUE | grepl("three month", entry, ignore.case = TRUE) == TRUE | grepl("three mpf", entry, ignore.case = TRUE) == TRUE | grepl("four month", entry, ignore.case = TRUE) == TRUE | grepl("four mpf", entry, ignore.case = TRUE) == TRUE | grepl("five month", entry, ignore.case = TRUE) == TRUE | grepl("five mpf", entry, ignore.case = TRUE) == TRUE | grepl("six month", entry, ignore.case = TRUE) == TRUE | grepl("six mpf", entry, ignore.case = TRUE) == TRUE | grepl("seven month", entry, ignore.case = TRUE) == TRUE | grepl("seven mpf", entry, ignore.case = TRUE) == TRUE | grepl("eight month", entry, ignore.case = TRUE) == TRUE | grepl("eight mpf", entry, ignore.case = TRUE) == TRUE | grepl("natal month three", entry, ignore.case = TRUE) == TRUE | grepl("year", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Adult")
    }
    if (grepl("larva", entry, ignore.case = TRUE) == TRUE | grepl("larval", entry, ignore.case = TRUE) == TRUE | grepl("larvae", entry, ignore.case = TRUE) == TRUE | grepl("eleutherolarva", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Larval")
    }
    if (grepl("juvenile", entry, ignore.case = TRUE) == TRUE | grepl("one month", entry, ignore.case = TRUE) == TRUE | grepl("two months", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Juvenile")
    }
  }
  
  if (length(classifications) == 0) {
    return("Undetermined")
  } else {
    # Split the string into words
    words <- unlist(strsplit(classifications, " "))
    # Remove duplicate words
    unique_words <- unique(words)
    # Combine the unique words back into a single string
    classifications <- paste(unique_words, collapse = ", ")
    return(paste(classifications, collapse = ", "))
  }
}

In [9]:
classify_stage_coarse2025 <- function(entry, devstage_full1) {
  classifications <- c()
  if (grepl("Undetermined", devstage_full1, ignore.case = TRUE) == TRUE) {
    ## moved these except for embryo into main devstage function, but also want to leave here for tertiary coarse-only
    ## but for adult, leave out year, even "adult", use instead "adult zebrafish" and "adult fish" ADDING 8/21 "adult stage" adding all mpf to adult...ONLY TO COARSE BTW
    # if (grepl("adult", entry, ignore.case = TRUE) == TRUE) {
    if (grepl("adult fish", entry, ignore.case = TRUE) == TRUE | grepl("adult zebrafish", entry, ignore.case = TRUE) == TRUE | grepl("adult stage", entry, ignore.case = TRUE) == TRUE | grepl("three month", entry, ignore.case = TRUE) == TRUE | grepl("mpf", entry, ignore.case = TRUE) == TRUE | grepl("four month", entry, ignore.case = TRUE) == TRUE | grepl("four mpf", entry, ignore.case = TRUE) == TRUE | grepl("five month", entry, ignore.case = TRUE) == TRUE | grepl("five mpf", entry, ignore.case = TRUE) == TRUE | grepl("six month", entry, ignore.case = TRUE) == TRUE | grepl("six mpf", entry, ignore.case = TRUE) == TRUE | grepl("seven month", entry, ignore.case = TRUE) == TRUE | grepl("seven mpf", entry, ignore.case = TRUE) == TRUE | grepl("eight month", entry, ignore.case = TRUE) == TRUE | grepl("eight mpf", entry, ignore.case = TRUE) == TRUE | grepl("natal month three", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Adult")
    }
    if (grepl("embryo", entry, ignore.case = TRUE) == TRUE | grepl("mzt", entry, ignore.case = TRUE) == TRUE | grepl("embyro", entry, ignore.case = TRUE) == TRUE | grepl("embryro", entry, ignore.case = TRUE) == TRUE | grepl("embroy", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Embryo")
    }
    if (grepl("larva", entry, ignore.case = TRUE) == TRUE | grepl("larval", entry, ignore.case = TRUE) == TRUE | grepl("larvae", entry, ignore.case = TRUE) == TRUE | grepl("eleutherolarva", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Larval")
    }
    if (grepl("juvenile", entry, ignore.case = TRUE) == TRUE | grepl("one month", entry, ignore.case = TRUE) == TRUE | grepl("two months", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Juvenile")
    }
    if (length(classifications) == 0) {
      return("Undetermined")
    } else {
      # Split the string into words
      words <- unlist(strsplit(classifications, " "))
      # Remove duplicate words
      unique_words <- unique(words)
      # Combine the unique words back into a single string
      classifications <- paste(unique_words, collapse = ", ")
      return(paste(classifications, collapse = ", "))
    }
  }
  if (grepl("Adult", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Adult")
  }
  if (grepl("Juvenile", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Juvenile")
  }
  if (grepl("Larval", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Larval")
  }
  if (grepl("Zygote", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Cleavage", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Blastula", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Gastrula", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Segmentation", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Pharyngula", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Hatching", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (grepl("Embryo", devstage_full1, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Embryo")
  }
  if (length(classifications) == 0) {
    return("Undetermined")
  } else {
    # Split the string into words
    words <- unlist(strsplit(classifications, " "))
    # Remove duplicate words
    unique_words <- unique(words)
    # Combine the unique words back into a single string
    classifications <- paste(unique_words, collapse = ", ")
    return(paste(classifications, collapse = ", "))
  }
  
}

In [10]:
## tissue function here
## first a version for tissue-specific columns that doesn't require word boundaries

classify_tissue2025first <- function(entry) {
  classifications <- c()
  # First - Replace dashes with spaces in the entry - instead doing this & rest in separate function clean_text_columns (but keeping basic dash replace just in case) Oocyte microinjection
  removed1 <- "\\b\\w+ removed\\b"
  removed2 <- "\\b\\w+ was removed\\b"
  # Use gsub to apply the pattern
  entry <- gsub(removed1, "removed", entry)
  entry <- gsub(removed2, "removed", entry)
  entry <- gsub("cardiomyocyte ablation", "card cell ablation", entry)
  entry <- gsub("Oocyte microinjection", "egg microinjection", entry)
  entry <- gsub("except the heads", "except the fore", entry)
  entry <- gsub("pec fin", "pecfin", entry)
  entry <- gsub("thyroid hormone", "thyr hormone", entry)
  entry <- gsub("head kidney", "kidney", entry)
  entry <- gsub("headkidney", "kidney", entry)
  entry <- gsub("whole zebrafish brain", "whole zfish brain", entry)
  entry <- gsub("Paris Brain Institute", "Paris B Institute", entry)
  entry <- gsub("kidney marrow", "kidney", entry)
  entry <- gsub("head removed", "hd was removed", entry)
  entry <- gsub("tailfin cut", "xx cut", entry)
  entry <- gsub("head region cut", "xx cut", entry)
  entry <- gsub("removing gill  fin and tail tissue", "removing xx", entry)
  entry <- gsub("poly A tail", "poly A tai", entry)
  entry <- gsub("-", " ", entry)
  if (grepl("pituitary", entry, ignore.case = TRUE) == TRUE | grepl("hypophysis", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pituitary Gland")
  }
  if (grepl("testis", entry, ignore.case = TRUE) == TRUE | grepl("testes", entry, ignore.case = TRUE) == TRUE | grepl("testicle", entry, ignore.case = TRUE) == TRUE | grepl("follicle", entry, ignore.case = TRUE) == TRUE | grepl("follicular", entry, ignore.case = TRUE) == TRUE | grepl("germ cell", entry, ignore.case = TRUE) == TRUE | grepl("gonad", entry, ignore.case = TRUE) == TRUE | grepl("ovary", entry, ignore.case = TRUE) == TRUE | grepl("ovaries", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gonad")
  }
  if (grepl("sperm ", entry, ignore.case = TRUE) == TRUE | grepl("spermatozoa", entry, ignore.case = TRUE) == TRUE | grepl("zygote", entry, ignore.case = TRUE) == TRUE | grepl("unfertilized", entry, ignore.case = TRUE) == TRUE | grepl("oocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Oocyte")
  }
  if (grepl("hepatocyte", entry, ignore.case = TRUE) == TRUE | grepl("liver", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Liver")
  }
  if (grepl("spinal cord", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Spinal Cord")
  }
  if (grepl("thyroid", entry, ignore.case = TRUE) == TRUE | grepl("thyrocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Thyroid")
  }
  if (grepl("melanoma", entry, ignore.case = TRUE) == TRUE | grepl("\\bcancer\\b", entry, ignore.case = TRUE) == TRUE | grepl("oncogene", entry, ignore.case = TRUE) == TRUE | grepl("malignanc", entry, ignore.case = TRUE) == TRUE | grepl("neuroblastoma", entry, ignore.case = TRUE) == TRUE | grepl("leukemia", entry, ignore.case = TRUE) == TRUE | grepl("carcinoma", entry, ignore.case = TRUE) == TRUE | grepl("tumour", entry, ignore.case = TRUE) == TRUE | grepl("tumor", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cancer or Tumor") ## for firstpass only adding "cancer" and only full word to avoid precancerous
  }
  if (grepl("bone marrow", entry, ignore.case = TRUE) == TRUE | grepl("marrow", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Marrow")
  }
  if (grepl("pancreas", entry, ignore.case = TRUE) == TRUE | grepl("beta cells", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pancreas")
  }
  if (grepl("spleen", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Spleen")
  }
  if (grepl("heart", entry, ignore.case = TRUE) == TRUE | grepl("cardiomyocyte", entry, ignore.case = TRUE) == TRUE | grepl("cardium", entry, ignore.case = TRUE) == TRUE | grepl("aorta", entry, ignore.case = TRUE) == TRUE | grepl("atrium", entry, ignore.case = TRUE) == TRUE | grepl("cardiac", entry, ignore.case = TRUE) == TRUE | grepl("bulbus arteriosus", entry, ignore.case = TRUE) == TRUE | grepl("ventricle", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Heart")
  }
  if (grepl("muscle", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Muscle")
  }
  if (grepl("intestin", entry, ignore.case = TRUE) == TRUE | grepl("digestive", entry, ignore.case = TRUE) == TRUE | grepl("gastrointestinal", entry, ignore.case = TRUE) == TRUE | grepl("\\bgut\\b", entry, ignore.case = TRUE) == TRUE | grepl("gut ", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gut") ## first pass only changing to "intestin" and adding whole word "gut"
  }
  if (grepl("neuromast", entry, ignore.case = TRUE) == TRUE | grepl("zebrafish neuromast hair cells", entry, ignore.case = TRUE) == TRUE | grepl("lateral line", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Lateral Line")
  }
  if (grepl("blood cell", entry, ignore.case = TRUE) == TRUE | grepl("matopoie", entry, ignore.case = TRUE) == TRUE | grepl("blood", entry, ignore.case = TRUE) == TRUE | grepl("macrophage", entry, ignore.case = TRUE) == TRUE | grepl("granuloma", entry, ignore.case = TRUE) == TRUE | grepl("granulocyte", entry, ignore.case = TRUE) == TRUE | grepl("phagocyte", entry, ignore.case = TRUE) == TRUE | grepl(" mast cell", entry, ignore.case = TRUE) == TRUE | grepl("eosinophil", entry, ignore.case = TRUE) == TRUE | grepl("basophil", entry, ignore.case = TRUE) == TRUE | grepl("neutrophil", entry, ignore.case = TRUE) == TRUE | grepl("erythroblast", entry, ignore.case = TRUE) == TRUE | grepl("erythroid cell", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Blood")
  }
  # if (grepl("macrophage", entry, ignore.case = TRUE) == TRUE | grepl("microglia", entry, ignore.case = TRUE) == TRUE | grepl("granuloma", entry, ignore.case = TRUE) == TRUE | grepl("granulocyte", entry, ignore.case = TRUE) == TRUE | grepl("phagocyte", entry, ignore.case = TRUE) == TRUE | grepl(" mast cell", entry, ignore.case = TRUE) == TRUE | grepl("eosinophil", entry, ignore.case = TRUE) == TRUE | grepl("basophil", entry, ignore.case = TRUE) == TRUE | grepl("neutrophil", entry, ignore.case = TRUE) == TRUE | grepl("erythroblast", entry, ignore.case = TRUE) == TRUE | grepl("erythroid cell", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Monocytes")
  # }
  if (grepl("kidney marrow", entry, ignore.case = TRUE) == TRUE | grepl("pronephros", entry, ignore.case = TRUE) == TRUE | grepl("mesonephros", entry, ignore.case = TRUE) == TRUE | grepl("DL segment", entry, ignore.case = TRUE) == TRUE | grepl("podocyte", entry, ignore.case = TRUE) == TRUE | grepl("nephrocyte", entry, ignore.case = TRUE) == TRUE | grepl("kidney", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Kidney")
  }
  if (grepl("pharyngeal arch", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pharyngeal Arch")
  }
  if (grepl("swim bladder", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Swim Bladder")
  }
  if (grepl("pineal gland", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pineal Gland")
  }
  if (grepl("cartilage", entry, ignore.case = TRUE) == TRUE | grepl("osteoblast", entry, ignore.case = TRUE) == TRUE | grepl("chondrocyte", entry, ignore.case = TRUE) == TRUE | grepl("osteoclast", entry, ignore.case = TRUE) == TRUE | grepl("bone", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Bone or Cartilage")
    ## terms chondrocyte & osteoclast do not pick up any additional rows - adding anyway!
  }
  if (grepl("jaw", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Jaw")
  }
  if (grepl("elasmoid", entry, ignore.case = TRUE) == TRUE | grepl("scale", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Scale") ## for firstpass only adding "scale"
  }
  if (grepl("melanocyte", entry, ignore.case = TRUE) == TRUE | grepl("keratinocyte", entry, ignore.case = TRUE) == TRUE | grepl("epidermal", entry, ignore.case = TRUE) == TRUE | grepl("epidermis", entry, ignore.case = TRUE) == TRUE | grepl("skin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Skin")
  }
  if (grepl("adipose", entry, ignore.case = TRUE) == TRUE | grepl("adipocyte", entry, ignore.case = TRUE) == TRUE | grepl("fat ", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Adipose Tissue")
  }
  if (grepl("otolith", entry, ignore.case = TRUE) == TRUE | grepl("utricule", entry, ignore.case = TRUE) == TRUE | grepl("saccule", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Ear")
  }
  if ( grepl("lymphatic", entry, ignore.case = TRUE) == TRUE | grepl("lymph", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Lymphatic System")
  }
  if (grepl("thymus", entry, ignore.case = TRUE) == TRUE | grepl("thymocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Thymus")
  }
  if (grepl("endothelium", entry, ignore.case = TRUE) == TRUE | grepl("endothelial cells", entry, ignore.case = TRUE) == TRUE | grepl("perivascular", entry, ignore.case = TRUE) == TRUE | grepl("endothelial", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Endothelium")
  }
  if (grepl("BCR", entry, ignore.case = TRUE) == TRUE | grepl("TCR", entry, ignore.case = TRUE) == TRUE | grepl("immunoglobulin", entry, ignore.case = TRUE) == TRUE | grepl(" IgH ", entry, ignore.case = FALSE) == TRUE) {
    classifications <- c(classifications, "BCR TCR repertoire")
  }
  if (grepl("telencephalon", entry, ignore.case = TRUE) == TRUE | grepl("microglia", entry, ignore.case = TRUE) == TRUE | grepl("optic nerve", entry, ignore.case = TRUE) == TRUE | grepl("optic tectum", entry, ignore.case = TRUE) == TRUE | grepl("meninge", entry, ignore.case = TRUE) == TRUE | grepl("ependymoglial", entry, ignore.case = TRUE) == TRUE | grepl("cerebellum", entry, ignore.case = TRUE) == TRUE | grepl("cerebrum", entry, ignore.case = TRUE) == TRUE | grepl("notochord", entry, ignore.case = TRUE) == TRUE | grepl("olfactory", entry, ignore.case = TRUE) == TRUE | grepl("neuron", entry, ignore.case = TRUE) == TRUE | grepl("neural crest", entry, ignore.case = TRUE) == TRUE | grepl("brain", entry, ignore.case = TRUE) == TRUE | grepl("hypothalamus", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Brain") ## adding optic nerve optic tectum meninge only to first
  }
  ## only using word boundaries for these sets - note for first pass removing word boundaries!
  if (grepl("trunk", entry, ignore.case = TRUE) == TRUE | grepl("abdomen", entry, ignore.case = TRUE) == TRUE | grepl("posterior half", entry, ignore.case = TRUE) == TRUE | grepl("abdominal", entry, ignore.case = TRUE) == TRUE | grepl("body", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Trunk")
  }
  if (grepl("fin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Fin")
  }
  if (grepl("gill", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gill")
  }
  if (grepl("tail", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Tail")
  }
  if (grepl("head", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Head")
  }
  if (grepl("retina", entry, ignore.case = TRUE) == TRUE | grepl("eye", entry, ignore.case = TRUE) == TRUE | grepl("photoreceptors", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Eye")
  }
  ### adding whole organism ONLY IF NOTHING ELSE FOUND
  if (length(classifications) == 0) {
    if (grepl("clutch", entry, ignore.case = TRUE) == TRUE | grepl("whole body", entry, ignore.case = TRUE) == TRUE | grepl("whole individual", entry, ignore.case = TRUE) == TRUE | grepl("whole tissue", entry, ignore.case = TRUE) == TRUE | grepl("whole eleutherolarvae", entry, ignore.case = TRUE) == TRUE | grepl("total fish", entry, ignore.case = TRUE) == TRUE | grepl("whole organism", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Whole Organism")
    }
    if (grepl("whole animal", entry, ignore.case = TRUE) == TRUE | grepl("whole fish", entry, ignore.case = TRUE) == TRUE | grepl("entire embryo", entry, ignore.case = TRUE) == TRUE | grepl("whole embryo", entry, ignore.case = TRUE) == TRUE | grepl("entire larvae", entry, ignore.case = TRUE) == TRUE | grepl("entire larva", entry, ignore.case = TRUE) == TRUE | grepl("whole larvae", entry, ignore.case = TRUE) == TRUE | grepl("complete larva", entry, ignore.case = TRUE) == TRUE | grepl("whole larva", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Whole Organism") ## only first pass changing "whole larva " to "whole larva" and adding "complete larva"
    }
    if (grepl("pooled male and female", entry, ignore.case = TRUE) == TRUE | grepl("pooled embryos", entry, ignore.case = TRUE) == TRUE | grepl("pooled larva", entry, ignore.case = TRUE) == TRUE | grepl("larvae total", entry, ignore.case = TRUE) == TRUE | grepl("pooled fish", entry, ignore.case = TRUE) == TRUE | grepl("pooled extract", entry, ignore.case = TRUE) == TRUE | grepl("pool of", entry, ignore.case = TRUE) == TRUE | grepl("whole adult", entry, ignore.case = TRUE) == TRUE | grepl("whole zebrafish", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Whole Organism")
    }
    ## moving cell line to only if nothing else found
    if (grepl("zf4", entry, ignore.case = TRUE) == TRUE | grepl("zfl", entry, ignore.case = TRUE) == TRUE |  grepl("AB9", entry, ignore.case = FALSE) == TRUE |  grepl("sjd", entry, ignore.case = TRUE) == TRUE | grepl("cell line", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Cell Line")
    }  
    ## moving imprecise embryo down to here without word boundaries
    if (grepl("embryo", entry, ignore.case = TRUE) == TRUE | grepl("embyro", entry, ignore.case = TRUE) == TRUE | grepl("embryro", entry, ignore.case = TRUE) == TRUE | grepl("embroy", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Embryo Imprecise")
    }
    
  }
  ## now if any whole organism is found, it removes other calls
  if ("Whole Organism" %in% classifications) {
    return("Whole Organism")
  }
  if (length(classifications) == 0) {
    return("Undetermined")
  } else {
    return(paste(classifications, collapse = ", "))
  }
}

In [11]:
## also OG version - updated for 2025 though with a few new gsub

classify_tissue2025 <- function(entry) {
  classifications <- c()
  # First - Replace dashes with spaces in the entry - instead doing this & rest in separate function clean_text_columns (but keeping basic dash replace just in case) Oocyte microinjection
  removed1 <- "\\b\\w+ removed\\b"
  removed2 <- "\\b\\w+ was removed\\b"
  # Use gsub to apply the pattern
  entry <- gsub(removed1, "removed", entry)
  entry <- gsub(removed2, "removed", entry)
  entry <- gsub("cardiomyocyte ablation", "card cell ablation", entry)
  entry <- gsub("Oocyte microinjection", "egg microinjection", entry)
  entry <- gsub("except the heads", "except the fore", entry)
  entry <- gsub("pec fin", "pecfin", entry)
  entry <- gsub("thyroid hormone", "thyr hormone", entry)
  entry <- gsub("head kidney", "kidney", entry)
  entry <- gsub("headkidney", "kidney", entry)
  entry <- gsub("whole zebrafish brain", "whole zfish brain", entry)
  entry <- gsub("Paris Brain Institute", "Paris B Institute", entry)
  entry <- gsub("kidney marrow", "kidney", entry)
  entry <- gsub("head removed", "hd was removed", entry)
  entry <- gsub("tailfin cut", "xx cut", entry)
  entry <- gsub("head region cut", "xx cut", entry)
  entry <- gsub("removing gill  fin and tail tissue", "removing xx", entry)
  entry <- gsub("poly A tail", "poly A tai", entry)
  entry <- gsub("-", " ", entry)
  if (grepl("pituitary", entry, ignore.case = TRUE) == TRUE | grepl("hypophysis", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pituitary Gland")
  }
  if (grepl("testis", entry, ignore.case = TRUE) == TRUE | grepl("testes", entry, ignore.case = TRUE) == TRUE | grepl("testicle", entry, ignore.case = TRUE) == TRUE | grepl("follicle", entry, ignore.case = TRUE) == TRUE | grepl("follicular", entry, ignore.case = TRUE) == TRUE | grepl("germ cell", entry, ignore.case = TRUE) == TRUE | grepl("gonad", entry, ignore.case = TRUE) == TRUE | grepl("ovary", entry, ignore.case = TRUE) == TRUE | grepl("ovaries", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gonad")
  }
  if (grepl("sperm ", entry, ignore.case = TRUE) == TRUE | grepl("spermatozoa", entry, ignore.case = TRUE) == TRUE | grepl("zygote", entry, ignore.case = TRUE) == TRUE | grepl("unfertilized", entry, ignore.case = TRUE) == TRUE | grepl("oocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Oocyte")
  }
  if (grepl("hepatocyte", entry, ignore.case = TRUE) == TRUE | grepl("liver", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Liver")
  }
  if (grepl("spinal cord", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Spinal Cord")
  }
  if (grepl("thyroid", entry, ignore.case = TRUE) == TRUE | grepl("thyrocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Thyroid")
  }
  if (grepl("zf4", entry, ignore.case = TRUE) == TRUE | grepl("zfl", entry, ignore.case = TRUE) == TRUE |  grepl("AB9", entry, ignore.case = FALSE) == TRUE |  grepl("sjd", entry, ignore.case = TRUE) == TRUE | grepl("cell line", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cell Line")
  }
  if (grepl("melanoma", entry, ignore.case = TRUE) == TRUE | grepl("oncogene", entry, ignore.case = TRUE) == TRUE | grepl("malignanc", entry, ignore.case = TRUE) == TRUE | grepl("neuroblastoma", entry, ignore.case = TRUE) == TRUE | grepl("leukemia", entry, ignore.case = TRUE) == TRUE | grepl("carcinoma", entry, ignore.case = TRUE) == TRUE | grepl("tumour", entry, ignore.case = TRUE) == TRUE | grepl("tumor", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cancer or Tumor")
  }
  if (grepl("bone marrow", entry, ignore.case = TRUE) == TRUE | grepl("marrow", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Marrow")
  }
  if (grepl("pancreas", entry, ignore.case = TRUE) == TRUE | grepl("beta cells", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pancreas")
  }
  if (grepl("spleen", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Spleen")
  }
  if (grepl("heart", entry, ignore.case = TRUE) == TRUE | grepl("cardiomyocyte", entry, ignore.case = TRUE) == TRUE | grepl("cardium", entry, ignore.case = TRUE) == TRUE | grepl("aorta", entry, ignore.case = TRUE) == TRUE | grepl("atrium", entry, ignore.case = TRUE) == TRUE | grepl("cardiac", entry, ignore.case = TRUE) == TRUE | grepl("bulbus arteriosus", entry, ignore.case = TRUE) == TRUE | grepl("ventricle", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Heart")
  }
  if (grepl("muscle", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Muscle")
  }
  if (grepl("intestine", entry, ignore.case = TRUE) == TRUE | grepl("digestive", entry, ignore.case = TRUE) == TRUE | grepl("gastrointestinal", entry, ignore.case = TRUE) == TRUE | grepl("gut ", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gut")
  }
  if (grepl("neuromast", entry, ignore.case = TRUE) == TRUE | grepl("zebrafish neuromast hair cells", entry, ignore.case = TRUE) == TRUE | grepl("lateral line", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Lateral Line")
  }
  if (grepl("blood cell", entry, ignore.case = TRUE) == TRUE | grepl("matopoie", entry, ignore.case = TRUE) == TRUE | grepl("blood", entry, ignore.case = TRUE) == TRUE | grepl("macrophage", entry, ignore.case = TRUE) == TRUE | grepl("granuloma", entry, ignore.case = TRUE) == TRUE | grepl("granulocyte", entry, ignore.case = TRUE) == TRUE | grepl("phagocyte", entry, ignore.case = TRUE) == TRUE | grepl(" mast cell", entry, ignore.case = TRUE) == TRUE | grepl("eosinophil", entry, ignore.case = TRUE) == TRUE | grepl("basophil", entry, ignore.case = TRUE) == TRUE | grepl("neutrophil", entry, ignore.case = TRUE) == TRUE | grepl("erythroblast", entry, ignore.case = TRUE) == TRUE | grepl("erythroid cell", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Blood")
  }
  # if (grepl("macrophage", entry, ignore.case = TRUE) == TRUE | grepl("microglia", entry, ignore.case = TRUE) == TRUE | grepl("granuloma", entry, ignore.case = TRUE) == TRUE | grepl("granulocyte", entry, ignore.case = TRUE) == TRUE | grepl("phagocyte", entry, ignore.case = TRUE) == TRUE | grepl(" mast cell", entry, ignore.case = TRUE) == TRUE | grepl("eosinophil", entry, ignore.case = TRUE) == TRUE | grepl("basophil", entry, ignore.case = TRUE) == TRUE | grepl("neutrophil", entry, ignore.case = TRUE) == TRUE | grepl("erythroblast", entry, ignore.case = TRUE) == TRUE | grepl("erythroid cell", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Monocytes")
  # }
  if (grepl("kidney marrow", entry, ignore.case = TRUE) == TRUE | grepl("pronephros", entry, ignore.case = TRUE) == TRUE | grepl("mesonephros", entry, ignore.case = TRUE) == TRUE | grepl("DL segment", entry, ignore.case = TRUE) == TRUE | grepl("podocyte", entry, ignore.case = TRUE) == TRUE | grepl("nephrocyte", entry, ignore.case = TRUE) == TRUE | grepl("kidney", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Kidney")
  }
  if (grepl("pharyngeal arch", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pharyngeal Arch")
  }
  if (grepl("swim bladder", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Swim Bladder")
  }
  if (grepl("pineal gland", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Pineal Gland")
  }
  if (grepl("cartilage", entry, ignore.case = TRUE) == TRUE | grepl("osteoblast", entry, ignore.case = TRUE) == TRUE | grepl("bone", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Bone or Cartilage")
    ## terms chondrocyte & osteoclast do not pick up any additional rows
  }
  if (grepl("jaw", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Jaw")
  }
  if (grepl("elasmoid", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Scale")
  }
  if (grepl("melanocyte", entry, ignore.case = TRUE) == TRUE | grepl("keratinocyte", entry, ignore.case = TRUE) == TRUE | grepl("epidermal", entry, ignore.case = TRUE) == TRUE | grepl("epidermis", entry, ignore.case = TRUE) == TRUE | grepl("skin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Skin")
  }
  if (grepl("adipose", entry, ignore.case = TRUE) == TRUE | grepl("adipocyte", entry, ignore.case = TRUE) == TRUE | grepl("fat ", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Adipose Tissue")
  }
  if (grepl("otolith", entry, ignore.case = TRUE) == TRUE | grepl("utricule", entry, ignore.case = TRUE) == TRUE | grepl("saccule", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Ear")
  }
  if ( grepl("lymphatic", entry, ignore.case = TRUE) == TRUE | grepl("lymph", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Lymphatic System")
  }
  if (grepl("thymus", entry, ignore.case = TRUE) == TRUE | grepl("thymocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Thymus")
  }
  if (grepl("endothelium", entry, ignore.case = TRUE) == TRUE | grepl("endothelial cells", entry, ignore.case = TRUE) == TRUE | grepl("perivascular", entry, ignore.case = TRUE) == TRUE | grepl("endothelial", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Endothelium")
  }
  if (grepl("BCR", entry, ignore.case = TRUE) == TRUE | grepl("TCR", entry, ignore.case = TRUE) == TRUE | grepl("immunoglobulin", entry, ignore.case = TRUE) == TRUE | grepl(" IgH ", entry, ignore.case = FALSE) == TRUE) {
    classifications <- c(classifications, "BCR TCR repertoire")
  }
  if (grepl("telencephalon", entry, ignore.case = TRUE) == TRUE | grepl("microglia", entry, ignore.case = TRUE) == TRUE | grepl("optic nerve", entry, ignore.case = TRUE) == TRUE | grepl("optic tectum", entry, ignore.case = TRUE) == TRUE | grepl("meninge", entry, ignore.case = TRUE) == TRUE | grepl("ependymoglial", entry, ignore.case = TRUE) == TRUE | grepl("cerebellum", entry, ignore.case = TRUE) == TRUE | grepl("cerebrum", entry, ignore.case = TRUE) == TRUE | grepl("notochord", entry, ignore.case = TRUE) == TRUE | grepl("olfactory", entry, ignore.case = TRUE) == TRUE | grepl("\\bneuron\\b", entry, ignore.case = TRUE) == TRUE | grepl("neural crest", entry, ignore.case = TRUE) == TRUE | grepl("brain", entry, ignore.case = TRUE) == TRUE | grepl("hypothalamus", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Brain") ## adding optic nerve optic tectum meninge
  }
  ## only using word boundaries for these sets
  if (grepl("\\btrunk\\b", entry, ignore.case = TRUE) == TRUE | grepl("abdomen", entry, ignore.case = TRUE) == TRUE | grepl("posterior half", entry, ignore.case = TRUE) == TRUE | grepl("abdominal", entry, ignore.case = TRUE) == TRUE | grepl("\\bbody\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Trunk")
  }
  if (grepl("\\bfin\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\bfins\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Fin")
  }
  if (grepl("\\bgill\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\bgills\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Gill")
  }
  if (grepl("\\btail\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\btails\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Tail")
  }
  if (grepl("\\bhead\\b", entry, ignore.case = TRUE) == TRUE | grepl("whole head", entry, ignore.case = TRUE) == TRUE | grepl("head  without eyes", entry, ignore.case = TRUE) == TRUE | grepl("\\bheads\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Head")
  }
  if (grepl("retina", entry, ignore.case = TRUE) == TRUE | grepl("\\beye\\b", entry, ignore.case = TRUE) == TRUE | grepl("\\beyes\\b", entry, ignore.case = TRUE) == TRUE | grepl("photoreceptors", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Eye")
  }
  ## moving whole fish up, but adding whole zebrafish here - 2025 update moving back down...
  # if (grepl("embryo", entry, ignore.case = TRUE) == TRUE | grepl("embyro", entry, ignore.case = TRUE) == TRUE | grepl("embryro", entry, ignore.case = TRUE) == TRUE | grepl("embroy", entry, ignore.case = TRUE) == TRUE) {
  #   classifications <- c(classifications, "Embryo Imprecise")
  # }
  ### adding whole organism ONLY IF NOTHING ELSE FOUND
  if (length(classifications) == 0) {
    if (grepl("clutch", entry, ignore.case = TRUE) == TRUE | grepl("whole body", entry, ignore.case = TRUE) == TRUE | grepl("whole individual", entry, ignore.case = TRUE) == TRUE | grepl("whole tissue", entry, ignore.case = TRUE) == TRUE | grepl("whole eleutherolarvae", entry, ignore.case = TRUE) == TRUE | grepl("total fish", entry, ignore.case = TRUE) == TRUE | grepl("whole organism", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Whole Organism")
    }
    if (grepl("whole animal", entry, ignore.case = TRUE) == TRUE | grepl("whole fish", entry, ignore.case = TRUE) == TRUE | grepl("entire embryo", entry, ignore.case = TRUE) == TRUE | grepl("whole embryo", entry, ignore.case = TRUE) == TRUE | grepl("entire larvae", entry, ignore.case = TRUE) == TRUE | grepl("entire larva", entry, ignore.case = TRUE) == TRUE | grepl("whole larvae", entry, ignore.case = TRUE) == TRUE | grepl("whole larva ", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Whole Organism")
    }
    if (grepl("pooled male and female", entry, ignore.case = TRUE) == TRUE | grepl("pooled embryos", entry, ignore.case = TRUE) == TRUE | grepl("pooled larva", entry, ignore.case = TRUE) == TRUE | grepl("larvae total", entry, ignore.case = TRUE) == TRUE | grepl("pooled fish", entry, ignore.case = TRUE) == TRUE | grepl("pooled extract", entry, ignore.case = TRUE) == TRUE | grepl("pool of", entry, ignore.case = TRUE) == TRUE | grepl("whole adult", entry, ignore.case = TRUE) == TRUE | grepl("whole zebrafish", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Whole Organism")
    }
   ## moving cell line & imprecise embryo to only if nothing else found
    if (grepl("zf4", entry, ignore.case = TRUE) == TRUE | grepl("zfl", entry, ignore.case = TRUE) == TRUE |  grepl("AB9", entry, ignore.case = FALSE) == TRUE |  grepl("sjd", entry, ignore.case = TRUE) == TRUE | grepl("cell line", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Cell Line")
    }  
    if (grepl("embryo", entry, ignore.case = TRUE) == TRUE | grepl("embyro", entry, ignore.case = TRUE) == TRUE | grepl("embryro", entry, ignore.case = TRUE) == TRUE | grepl("embroy", entry, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Embryo Imprecise")
    }
  }
  ## now if any whole organism is found, it removes other calls
  if ("Whole Organism" %in% classifications) {
    return("Whole Organism")
  }
  if (length(classifications) == 0) {
    return("Undetermined")
  } else {
    return(paste(classifications, collapse = ", "))
  }
}

In [12]:
## note a few get changed to Multi-tissue, instead lets skip ahead and go straight to Multi-system for coarse!!
classify_tissue_coarse2025 <- function(entry, devstage_full) {
  classifications <- c()
  if (grepl("Undetermined", entry, ignore.case = TRUE) == TRUE) {
    if (grepl("Embryo", devstage_full, ignore.case = TRUE) == TRUE) {
      classifications <- c(classifications, "Embryo Imprecise")
    }
  }
  if (grepl("Gonad", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Reproductive System")
  }
  if (grepl("Head", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Nervous System")
  }
  if (grepl("Trunk", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Surface Structure")
  }
  if (grepl("Swim Bladder", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Swim Bladder")
  }
  if (grepl("Brain", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Nervous System")
  }
  if (grepl("Heart", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cardiovascular System")
  }
  if (grepl("Kidney", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Renal System")
  }
  if (grepl("Oocyte", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Reproductive System")
  }
  if (grepl("BCR TCR repertoire", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hematopoietic System")
  }
  if (grepl("Liver", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Liver and Biliary System")
  }
  if (grepl("Eye", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Sensory System")
  }
  if (grepl("Skin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Surface Structure")
  }
  if (grepl("Tail", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Multi-system")
  }
  if (grepl("Muscle", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Muscular System")
  }
  if (grepl("Pineal Gland", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Endocrine System")
  }
  if (grepl("Lymphatic System", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cardiovascular System")
  }
  if (grepl("Thymus", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hematopoietic System")
  }
  if (grepl("Endothelium", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cardiovascular System")
  }
  if (grepl("Fin", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Surface Structure")
  }
  if (grepl("Blood", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hematopoietic System")
  }
  if (grepl("Gut", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Digestive System")
  }
  if (grepl("Gill", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Respiratory System")
  }
  if (grepl("Bone or Cartilage", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Skeletal Element")
  }
  if (grepl("Jaw", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Surface Structure")
  }
  if (grepl("Scale", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Surface Structure")
  }
  if (grepl("Pharyngeal Arch", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Multi-system")
  }
  if (grepl("Spleen", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Hematopoietic System")
  }
  if (grepl("Thyroid", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Endocrine System")
  }
  if (grepl("Pancreas", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Endocrine System")
  }
  if (grepl("Spinal Cord", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Nervous System")
  }
  if (grepl("Marrow", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Renal System")
  }
  if (grepl("\\bEar\\b", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Sensory System")
  }
  if (grepl("Pituitary Gland", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Endocrine System")
  }
  if (grepl("Lateral Line", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Sensory System")
  }
  if (grepl("Adipose Tissue", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Adipose Tissue")
  }
  if (grepl("Multi-tissue", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Multi-system")
  }
  if (grepl("Cancer or Tumor", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cancer or Tumor")
  }
  if (grepl("Cell Line", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "Cell Line")
  }
  if (grepl("Whole Organism", entry, ignore.case = TRUE) == TRUE) {
    classifications <- c(classifications, "All anatomical structures")
  }
  ## idea - we want to only add this if the entry is ONLY embryo imprecise!!
  if (entry == "Embryo Imprecise") {
    classifications <- c(classifications, "All anatomical structures")
  }
  if (length(classifications) == 0) {
    return("Undetermined")
  } else {
    return(paste(classifications, collapse = ", "))
  }
}

In [13]:
## also add a step to convert multiple systems to "Multiple Systems" - this is a separate code chunk but also a new chunk in coarse tissue function
## also want to simplify - if Embryo Imprecise found anywhere, make the coarse label just Embryo Imprecise
## similarly if All anatomical structures found anywhere, make coarse label just All anatomical structures

# Dev stage functions




## First run the _clean_text_columns_ function

In [14]:
metadata_curationstep1

      run.accession study.accession bioproject
1     DRR314108     DRP008373       PRJDB12134
2     DRR314107     DRP008373       PRJDB12134
3     DRR314106     DRP008373       PRJDB12134
4     DRR314105     DRP008373       PRJDB12134
5     DRR314104     DRP008373       PRJDB12134
6     DRR314103     DRP008373       PRJDB12134
7     DRR315802     DRP008318       PRJDB12206
8     DRR315801     DRP008318       PRJDB12206
9     DRR315800     DRP008318       PRJDB12206
10    DRR315799     DRP008318       PRJDB12206
11    DRR315798     DRP008318       PRJDB12206
12    DRR315797     DRP008318       PRJDB12206
13    DRR315796     DRP008318       PRJDB12206
14    DRR315795     DRP008318       PRJDB12206
15    DRR334977     DRP008001       PRJDB12578
16    DRR334976     DRP008001       PRJDB12578
17    DRR334975     DRP008001       PRJDB12578
18    DRR334974     DRP008001       PRJDB12578
19    DRR334973     DRP008001       PRJDB12578
20    DRR334972     DRP008001       PRJDB12578
21    DRR334971     DRP008001       PRJDB12578
22    DRR334970     DRP008001       PRJDB12578
23    DRR334969     DRP008001       PRJDB12578
24    DRR334968     DRP008001       PRJDB12578
25    DRR334967     DRP008001       PRJDB12578
26    DRR334966     DRP008001       PRJDB12578
27    DRR334965     DRP008001       PRJDB12578
28    DRR334964     DRP008001       PRJDB12578
29    DRR334963     DRP008001       PRJDB12578
30    DRR334962     DRP008001       PRJDB12578
⋮     ⋮             ⋮               ⋮
77300 SRR25438772   SRP451780       PRJNA999234
77301 SRR25438773   SRP451780       PRJNA999234
77302 SRR25445395   SRP451943       PRJNA999591
77303 SRR25445396   SRP451943       PRJNA999591
77304 SRR25453755   SRP452071       PRJNA999746
77305 SRR25453756   SRP452071       PRJNA999746
77306 SRR25453758   SRP452071       PRJNA999746
77307 SRR25453759   SRP452071       PRJNA999746
77308 SRR25453761   SRP452071       PRJNA999746
77309 SRR25453762   SRP452071       PRJNA999746
77310 SRR25453764   SRP452071       PRJNA999746
77311 SRR25453765   SRP452071       PRJNA999746
77312 SRR25453757   SRP452071       PRJNA999746
77313 SRR25453760   SRP452071       PRJNA999746
77314 SRR25453763   SRP452071       PRJNA999746
77315 SRR25453766   SRP452071       PRJNA999746
77316 SRR25453690   SRP452067       PRJNA999747
77317 SRR25453691   SRP452067       PRJNA999747
77318 SRR25453692   SRP452067       PRJNA999747
77319 SRR25453693   SRP452067       PRJNA999747
77320 SRR25453694   SRP452067       PRJNA999747
77321 SRR25453695   SRP452067       PRJNA999747
77322 SRR25453696   SRP452067       PRJNA999747
77323 SRR25453697   SRP452067       PRJNA999747
77324 SRR25453698   SRP452067       PRJNA999747
77325 SRR25453699   SRP452067       PRJNA999747
77326 SRR25453700   SRP452067       PRJNA999747
77327 SRR25453701   SRP452067       PRJNA999747
77328 SRR065197     SRP003472       PRJXX3472
77329 SRR065196     SRP003472       PRJXX3472
      study.title
1     Comparison of expression profile between banp mutant and wildtype sibling.
2     Comparison of expression profile between banp mutant and wildtype sibling.
3     Comparison of expression profile between banp mutant and wildtype sibling.
4     Comparison of expression profile between banp mutant and wildtype sibling.
5     Comparison of expression profile between banp mutant and wildtype sibling.
6     Comparison of expression profile between banp mutant and wildtype sibling.
7     Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
8     Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
9     Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
10    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
11    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
12    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
13    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
14    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
15    Allometric scaling of RNA abundance from genes to communities
16    Allometric scaling of RNA abundance from genes to communities
17    Allometric scaling of RNA abundance from genes to communities
18    Allometric scaling of RNA abundance from genes to communities
19    Allometric scaling of RNA abundance from genes to communities
20    Allometric scaling of RNA abundance from genes to communities
21    Allometric scaling of RNA abundance from genes to communities
22    Allometric scaling of RNA abundance from genes to communities
23    Allometric scaling of RNA abundance from genes to communities
24    Allometric scaling of RNA abundance from genes to communities
25    Allometric scaling of RNA abundance from genes to communities
26    Allometric scaling of RNA abundance from genes to communities
27    Allometric scaling of RNA abundance from genes to communities
28    Allometric scaling of RNA abundance from genes to communities
29    Allometric scaling of RNA abundance from genes to communities
30    Allometric scaling of RNA abundance from genes to communities
⋮     ⋮
77300 Common and divergent gene regulatory networks control injury-induced and developmental neurogenesis in zebrafish retina [snRNA-seq]
77301 Common and divergent gene regulatory networks control injury-induced and developmental neurogenesis in zebrafish retina [snRNA-seq]
77302 Transcriptome analysis of cardiac tissue from Wild-type (WT) andsalvianolate-treated  Zebrafish
77303 Transcriptome analysis of cardiac tissue from Wild-type (WT) andsalvianolate-treated  Zebrafish
77304 Transcriptomic differences between deeply quiescent and activated adult NSCs
77305 Transcriptomic differences between deeply quiescent and activated adult NSCs
77306 Transcriptomic differences between deeply quiescent and activated adult NSCs
77307 Transcriptomic differences between deeply quiescent and activated adult NSCs
77308 Transcriptomic differences between deeply quiescent and activated adult NSCs
77309 Transcriptomic differences between deeply quiescent and activated adult NSCs
77310 Transcriptomic differences between deeply quiescent and activated adult NSCs
77311 Transcriptomic differences between deeply quiescent and activated adult NSCs
77312 Transcriptomic differences between deeply quiescent and activated adult NSCs
77313 Transcriptomic differences between deeply quiescent and activated adult NSCs
77314 Transcriptomic differences between deeply quiescent and activated adult NSCs
77315 Transcriptomic differences between deeply quiescent and activated adult NSCs
77316 Transcriptomic differences between juvenile and adult quiescent NSCs
77317 Transcriptomic differences between juvenile and adult quiescent NSCs
77318 Transcriptomic differences between juvenile and adult quiescent NSCs
77319 Transcriptomic differences between juvenile and adult quiescent NSCs
77320 Transcriptomic differences between juvenile and adult quiescent NSCs
77321 Transcriptomic differences between juvenile and adult quiescent NSCs
77322 Transcriptomic differences between juvenile and adult quiescent NSCs
77323 Transcriptomic differences between juvenile and adult quiescent NSCs
77324 Transcriptomic differences between juvenile and adult quiescent NSCs
77325 Transcriptomic differences between juvenile and adult quiescent NSCs
77326 Transcriptomic differences between juvenile and adult quiescent NSCs
77327 Transcriptomic differences between juvenile and adult quiescent NSCs
77328 RNA-Seq analysis in mutant zebrafish reveals role of U1C protein in alternative splicing regulation
77329 RNA-Seq analysis in mutant zebrafish reveals role of U1C protein in alternative splicing regulation
      sample.accession experiment.accession earliest_date
1     DRS233566        DRX303511            2022-04-01
2     DRS233565        DRX303510            2022-04-01
3     DRS233564        DRX303509            2022-04-01
4     DRS233563        DRX303508            2022-04-01
5     DRS233562        DRX303507            2022-04-01
6     DRS233561        DRX303506            2022-04-01
7     DRS231989        DRX305194            2022-03-16
8     DRS231988        DRX305193            2022-03-16
9     DRS231987        DRX305192            2022-03-16
10    DRS231986        DRX305191            2022-03-16
11    DRS231985        DRX305190            2022-03-16
12    DRS231984        DRX305189            2022-03-16
13    DRS231983        DRX305188            2022-03-16
14    DRS231982        DRX305187            2022-03-16
15    DRS217313        DRX323973            2021-12-23
16    DRS217312        DRX323972            2021-12-23
17    DRS217311        DRX323971            2021-12-23
18    DRS217310        DRX323970            2021-12-23
19    DRS217309        DRX323969            2021-12-23
20    DRS217308        DRX323968            2021-12-23
21    DRS217307        DRX323967            2021-12-23
22    DRS217306        DRX323966            2021-12-23
23    DRS217305        DRX323965            2021-12-23
24    DRS217304        DRX323964            2021-12-23
25    DRS217303        DRX323963            2021-12-23
26    DRS217302        DRX323962            2021-12-23
27    DRS217318        DRX323961            2021-12-23
28    DRS217317        DRX323960            2021-12-23
29    DRS217316        DRX323959            2021-12-23
30    DRS217315        DRX323958            2021-12-23
⋮     ⋮                ⋮                    ⋮
77300 SRS18433956      SRX21172619          2023-07-27
77301 SRS18433956      SRX21172619          2023-07-27
77302 SRS18439483      SRX21178634          2023-07-28
77303 SRS18439482      SRX21178633          2023-07-28
77304 SRS18446706      SRX21186685          2023-07-28
77305 SRS18446705      SRX21186684          2023-07-28
77306 SRS18446703      SRX21186682          2023-07-28
77307 SRS18446702      SRX21186681          2023-07-28
77308 SRS18446700      SRX21186679          2023-07-28
77309 SRS18446699      SRX21186678          2023-07-28
77310 SRS18446697      SRX21186676          2023-07-28
77311 SRS18446696      SRX21186675          2023-07-28
77312 SRS18446704      SRX21186683          2023-07-28
77313 SRS18446701      SRX21186680          2023-07-28
77314 SRS18446698      SRX21186677          2023-07-28
77315 SRS18446695      SRX21186674          2023-07-28
77316 SRS18446641      SRX21186620          2023-07-28
77317 SRS18446640      SRX21186619          2023-07-28
77318 SRS18446639      SRX21186618          2023-07-28
77319 SRS18446638      SRX21186617          2023-07-28
77320 SRS18446637      SRX21186616          2023-07-28
77321 SRS18446636      SRX21186615          2023-07-28
77322 SRS18446635      SRX21186614          2023-07-28
77323 SRS18446634      SRX21186613          2023-07-28
77324 SRS18446633      SRX21186612          2023-07-28
77325 SRS18446632      SRX21186611          2023-07-28
77326 SRS18446631      SRX21186610          2023-07-28
77327 SRS18446630      SRX21186609          2023-07-28
77328 SRS114570        SRX026483            2011-03-31
77329 SRS114569        SRX026482            2011-03-31
      experiment.title
1     Illumina NovaSeq 6000 paired end sequencing of SAMD00399013
2     Illumina NovaSeq 6000 paired end sequencing of SAMD00399012
3     Illumina NovaSeq 6000 paired end sequencing of SAMD00399011
4     Illumina NovaSeq 6000 paired end sequencing of SAMD00399010
5     Illumina NovaSeq 6000 paired end sequencing of SAMD00399009
6     Illumina NovaSeq 6000 paired end sequencing of SAMD00399008
7     Illumina NovaSeq 6000 paired end sequencing of SAMD00400823
8     Illumina NovaSeq 6000 paired end sequencing of SAMD00400822
9     Illumina NovaSeq 6000 paired end sequencing of SAMD00400821
10    Illumina NovaSeq 6000 paired end sequencing of SAMD00400820
11    Illumina NovaSeq 6000 paired end sequencing of SAMD00400819
12    Illumina NovaSeq 6000 paired end sequencing of SAMD00400818
13    Illumina NovaSeq 6000 paired end sequencing of SAMD00400817
14    Illumina NovaSeq 6000 paired end sequencing of SAMD00400816
15    NextSeq 2000 sequencing of SAMD00422597
16    NextSeq 2000 sequencing of SAMD00422596
17    NextSeq 2000 sequencing of SAMD00422595
18    NextSeq 2000 sequencing of SAMD00422594
19    NextSeq 2000 sequencing of SAMD00422593
20    NextSeq 2000 sequencing of SAMD00422592
21    NextSeq 2000 sequencing of SAMD00422591
22    NextSeq 2000 sequencing of SAMD00422590
23    NextSeq 2000 sequencing of SAMD00422589
24    NextSeq 2000 sequencing of SAMD00422588
25    NextSeq 2000 sequencing of SAMD00422587
26    NextSeq 2000 sequencing of SAMD00422586
27    NextSeq 2000 sequencing of SAMD00422602
28    NextSeq 2000 sequencing of SAMD00422601
29    NextSeq 2000 sequencing of SAMD00422600
30    NextSeq 2000 sequencing of SAMD00422599
⋮     ⋮
77300 GSM7664321: Injury Control, snRNA-seq; Danio rerio; RNA-Seq
77301 GSM7664321: Injury Control, snRNA-seq; Danio rerio; RNA-Seq
77302 GSM7666321: salvianolate-treated zebrafish embryos; Danio rerio; RNA-Seq
77303 GSM7666320: WT; Danio rerio; RNA-Seq
77304 GSM7668467: Experiment 13, tg(her4:RFP-low); Danio rerio; RNA-Seq
77305 GSM7668466: Experiment 13, tg(her4:RFP-high); Danio rerio; RNA-Seq
77306 GSM7668464: Experiment 12, tg(her4:RFP-low); Danio rerio; RNA-Seq
77307 GSM7668463: Experiment 12, tg(her4:RFP-high); Danio rerio; RNA-Seq
77308 GSM7668461: Experiment 11, tg(her4:RFP-low); Danio rerio; RNA-Seq
77309 GSM7668460: Experiment 11, tg(her4:RFP-high); Danio rerio; RNA-Seq
77310 GSM7668458: Experiment 10, tg(her4:RFP-low); Danio rerio; RNA-Seq
77311 GSM7668457: Experiment 10, tg(her4:RFP-high); Danio rerio; RNA-Seq
77312 GSM7668465: Experiment 13, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77313 GSM7668462: Experiment 12, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77314 GSM7668459: Experiment 11, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77315 GSM7668456: Experiment 10, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77316 GSM7668494: Experiment 8, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77317 GSM7668493: Experiment 8, tg(her4:RFP); Danio rerio; RNA-Seq
77318 GSM7668492: Experiment 6, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77319 GSM7668491: Experiment 6, tg(her4:RFP); Danio rerio; RNA-Seq
77320 GSM7668490: Experiment 4, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77321 GSM7668489: Experiment 4, tg(her4:RFP); Danio rerio; RNA-Seq
77322 GSM7668488: Experiment 3, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77323 GSM7668487: Experiment 3, tg(her4:RFP); Danio rerio; RNA-Seq
77324 GSM7668486: Experiment 2, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77325 GSM7668485: Experiment 2, tg(her4:RFP); Danio rerio; RNA-Seq
77326 GSM7668484: Experiment 1, tg(her4:RFP), tg(mcm5:gfp); Danio rerio; RNA-Seq
77327 GSM7668483: Experiment 1, tg(her4:RFP); Danio rerio; RNA-Seq
77328 3-dpf mutant zebrafish embryos
77329 3-dpf wildtype embryos
      experiment.attributes sample.title                                    ⋯
1     NA                    RNA-seq of wild-type sibling sample3            ⋯
2     NA                    RNA-seq of wild-type sibling sample2            ⋯
3     NA                    RNA-seq of wild-type sibling sample1            ⋯
4     NA                    RNA-seq of banp mutant sample3                  ⋯
5     NA                    RNA-seq of banp mutant sample2                  ⋯
6     NA                    RNA-seq of banp mutant sample1                  ⋯
7     NA                    wildtype sibling sample4                        ⋯
8     NA                    wildtype sibling sample3                        ⋯
9     NA                    wildtype sibling sample2                        ⋯
10    NA                    wildtype sibling sample1                        ⋯
11    NA                    strip1 mutant sample4                           ⋯
12    NA                    strip1 mutant sample3                           ⋯
13    NA                    strip1 mutant sample2                           ⋯
14    NA                    strip1 mutant sample1                           ⋯
15    NA                    rRNA mock community at 28 degrees rep 3         ⋯
16    NA                    rRNA mock community at 28 degrees rep 2         ⋯
17    NA                    rRNA mock community at 28 degrees rep 1         ⋯
18    NA                    rRNA mock community at 19 degrees rep 3         ⋯
19    NA                    rRNA mock community at 19 degrees rep 2         ⋯
20    NA                    rRNA mock community at 19 degrees rep 1         ⋯
21    NA                    rRNA mock community at 10 degrees rep 3         ⋯
22    NA                    rRNA mock community at 10 degrees rep 2         ⋯
23    NA                    rRNA mock community at 10 degrees rep 1         ⋯
24    NA                    mRNA mock community at 28 degrees rep 3         ⋯
25    NA                    mRNA mock community at 28 degrees rep 2         ⋯
26    NA                    mRNA mock community at 28 degrees rep 1         ⋯
27    NA                    mRNA mock community at 19 degrees rep 3         ⋯
28    NA                    mRNA mock community at 19 degrees rep 2         ⋯
29    NA                    mRNA mock community at 19 degrees rep 1         ⋯
30    NA                    mRNA mock community at 10 degrees rep 3         ⋯
⋮     ⋮                     ⋮                                               ⋱
77300 NA                    Injury Control, snRNA-seq                       ⋯
77301 NA                    Injury Control, snRNA-seq                       ⋯
77302 NA                    salvianolate-treated zebrafish embryos          ⋯
77303 NA                    WT                                              ⋯
77304 NA                    Experiment 13, tg(her4:RFP-low)                 ⋯
77305 NA                    Experiment 13, tg(her4:RFP-high)                ⋯
77306 NA                    Experiment 12, tg(her4:RFP-low)                 ⋯
77307 NA                    Experiment 12, tg(her4:RFP-high)                ⋯
77308 NA                    Experiment 11, tg(her4:RFP-low)                 ⋯
77309 NA                    Experiment 11, tg(her4:RFP-high)                ⋯
77310 NA                    Experiment 10, tg(her4:RFP-low)                 ⋯
77311 NA                    Experiment 10, tg(her4:RFP-high)                ⋯
77312 NA                    Experiment 13, tg(her4:RFP), tg(mcm5:gfp)       ⋯
77313 NA                    Experiment 12, tg(her4:RFP), tg(mcm5:gfp)       ⋯
77314 NA                    Experiment 11, tg(her4:RFP), tg(mcm5:gfp)       ⋯
77315 NA                    Experiment 10, tg(her4:RFP), tg(mcm5:gfp)       ⋯
77316 NA                    Experiment 8, tg(her4:RFP), tg(mcm5:gfp)        ⋯
77317 NA                    Experiment 8, tg(her4:RFP)                      ⋯
77318 NA                    Experiment 6, tg(her4:RFP), tg(mcm5:gfp)        ⋯
77319 NA                    Experiment 6, tg(her4:RFP)                      ⋯
77320 NA                    Experiment 4, tg(her4:RFP), tg(mcm5:gfp)        ⋯
77321 NA                    Experiment 4, tg(her4:RFP)                      ⋯
77322 NA                    Experiment 3, tg(her4:RFP), tg(mcm5:gfp)        ⋯
77323 NA                    Experiment 3, tg(her4:RFP)                      ⋯
77324 NA                    Experiment 2, tg(her4:RFP), tg(mcm5:gfp)        ⋯
77325 NA                    Experiment 2, tg(her4:RFP)                      ⋯
77326 NA                    Experiment 1, tg(her4:RFP), tg(mcm5:gfp)        ⋯
77327 NA                    Experiment 1, tg(her4:RFP)                      ⋯
77328 NA                    Total RNA from 3-dpf mutant zebrafish embryos   ⋯
77329 NA                    Total RNA from 3-dpf wildtype zebrafish embryos ⋯
      experiment.library_construction_protocol
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    NEBNext Kit for Illumina
16    NEBNext Kit for Illumina

In [15]:
### first run clean columns also add "study.title"
metadata_curationstep1clean <- clean_text_columns(metadata_curationstep1, c("study.title","experiment.title","experiment.attributes", "sample.title", "sample.attributes", "GEOsample.title", "GEOsample.characteristics", "run.title", "run.alias", "run.attributes", "experiment.alias", "experiment.library_name", "experiment.design_description", "experiment.library_construction_protocol", "sample.description", "sample.alias", "GEOsample.dataprocessing", "GEOsample.source", "GEOsample.treatmentprotocol", "GEOsample.extractprotocol", "GEOsample.growthprotocol", "study.abstract", "study.attributes"))

In [16]:
metadata_curationstep1clean

      run.accession study.accession bioproject
1     DRR314108     DRP008373       PRJDB12134
2     DRR314107     DRP008373       PRJDB12134
3     DRR314106     DRP008373       PRJDB12134
4     DRR314105     DRP008373       PRJDB12134
5     DRR314104     DRP008373       PRJDB12134
6     DRR314103     DRP008373       PRJDB12134
7     DRR315802     DRP008318       PRJDB12206
8     DRR315801     DRP008318       PRJDB12206
9     DRR315800     DRP008318       PRJDB12206
10    DRR315799     DRP008318       PRJDB12206
11    DRR315798     DRP008318       PRJDB12206
12    DRR315797     DRP008318       PRJDB12206
13    DRR315796     DRP008318       PRJDB12206
14    DRR315795     DRP008318       PRJDB12206
15    DRR334977     DRP008001       PRJDB12578
16    DRR334976     DRP008001       PRJDB12578
17    DRR334975     DRP008001       PRJDB12578
18    DRR334974     DRP008001       PRJDB12578
19    DRR334973     DRP008001       PRJDB12578
20    DRR334972     DRP008001       PRJDB12578
21    DRR334971     DRP008001       PRJDB12578
22    DRR334970     DRP008001       PRJDB12578
23    DRR334969     DRP008001       PRJDB12578
24    DRR334968     DRP008001       PRJDB12578
25    DRR334967     DRP008001       PRJDB12578
26    DRR334966     DRP008001       PRJDB12578
27    DRR334965     DRP008001       PRJDB12578
28    DRR334964     DRP008001       PRJDB12578
29    DRR334963     DRP008001       PRJDB12578
30    DRR334962     DRP008001       PRJDB12578
⋮     ⋮             ⋮               ⋮
77300 SRR25438772   SRP451780       PRJNA999234
77301 SRR25438773   SRP451780       PRJNA999234
77302 SRR25445395   SRP451943       PRJNA999591
77303 SRR25445396   SRP451943       PRJNA999591
77304 SRR25453755   SRP452071       PRJNA999746
77305 SRR25453756   SRP452071       PRJNA999746
77306 SRR25453758   SRP452071       PRJNA999746
77307 SRR25453759   SRP452071       PRJNA999746
77308 SRR25453761   SRP452071       PRJNA999746
77309 SRR25453762   SRP452071       PRJNA999746
77310 SRR25453764   SRP452071       PRJNA999746
77311 SRR25453765   SRP452071       PRJNA999746
77312 SRR25453757   SRP452071       PRJNA999746
77313 SRR25453760   SRP452071       PRJNA999746
77314 SRR25453763   SRP452071       PRJNA999746
77315 SRR25453766   SRP452071       PRJNA999746
77316 SRR25453690   SRP452067       PRJNA999747
77317 SRR25453691   SRP452067       PRJNA999747
77318 SRR25453692   SRP452067       PRJNA999747
77319 SRR25453693   SRP452067       PRJNA999747
77320 SRR25453694   SRP452067       PRJNA999747
77321 SRR25453695   SRP452067       PRJNA999747
77322 SRR25453696   SRP452067       PRJNA999747
77323 SRR25453697   SRP452067       PRJNA999747
77324 SRR25453698   SRP452067       PRJNA999747
77325 SRR25453699   SRP452067       PRJNA999747
77326 SRR25453700   SRP452067       PRJNA999747
77327 SRR25453701   SRP452067       PRJNA999747
77328 SRR065197     SRP003472       PRJXX3472
77329 SRR065196     SRP003472       PRJXX3472
      study.title
1     Comparison of expression profile between banp mutant and wildtype sibling.
2     Comparison of expression profile between banp mutant and wildtype sibling.
3     Comparison of expression profile between banp mutant and wildtype sibling.
4     Comparison of expression profile between banp mutant and wildtype sibling.
5     Comparison of expression profile between banp mutant and wildtype sibling.
6     Comparison of expression profile between banp mutant and wildtype sibling.
7     Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
8     Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
9     Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
10    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
11    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
12    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
13    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
14    Transcriptome analysis of strip1 mutant and wildtype zebrafish eyes
15    Allometric scaling of RNA abundance from genes to communities
16    Allometric scaling of RNA abundance from genes to communities
17    Allometric scaling of RNA abundance from genes to communities
18    Allometric scaling of RNA abundance from genes to communities
19    Allometric scaling of RNA abundance from genes to communities
20    Allometric scaling of RNA abundance from genes to communities
21    Allometric scaling of RNA abundance from genes to communities
22    Allometric scaling of RNA abundance from genes to communities
23    Allometric scaling of RNA abundance from genes to communities
24    Allometric scaling of RNA abundance from genes to communities
25    Allometric scaling of RNA abundance from genes to communities
26    Allometric scaling of RNA abundance from genes to communities
27    Allometric scaling of RNA abundance from genes to communities
28    Allometric scaling of RNA abundance from genes to communities
29    Allometric scaling of RNA abundance from genes to communities
30    Allometric scaling of RNA abundance from genes to communities
⋮     ⋮
77300 Common and divergent gene regulatory networks control injury induced and developmental neurogenesis in zebrafish retina [snRNA seq]
77301 Common and divergent gene regulatory networks control injury induced and developmental neurogenesis in zebrafish retina [snRNA seq]
77302 Transcriptome analysis of cardiac tissue from Wild type WT andsalvianolate treated  Zebrafish
77303 Transcriptome analysis of cardiac tissue from Wild type WT andsalvianolate treated  Zebrafish
77304 Transcriptomic differences between deeply quiescent and activated adult NSCs
77305 Transcriptomic differences between deeply quiescent and activated adult NSCs
77306 Transcriptomic differences between deeply quiescent and activated adult NSCs
77307 Transcriptomic differences between deeply quiescent and activated adult NSCs
77308 Transcriptomic differences between deeply quiescent and activated adult NSCs
77309 Transcriptomic differences between deeply quiescent and activated adult NSCs
77310 Transcriptomic differences between deeply quiescent and activated adult NSCs
77311 Transcriptomic differences between deeply quiescent and activated adult NSCs
77312 Transcriptomic differences between deeply quiescent and activated adult NSCs
77313 Transcriptomic differences between deeply quiescent and activated adult NSCs
77314 Transcriptomic differences between deeply quiescent and activated adult NSCs
77315 Transcriptomic differences between deeply quiescent and activated adult NSCs
77316 Transcriptomic differences between juvenile and adult quiescent NSCs
77317 Transcriptomic differences between juvenile and adult quiescent NSCs
77318 Transcriptomic differences between juvenile and adult quiescent NSCs
77319 Transcriptomic differences between juvenile and adult quiescent NSCs
77320 Transcriptomic differences between juvenile and adult quiescent NSCs
77321 Transcriptomic differences between juvenile and adult quiescent NSCs
77322 Transcriptomic differences between juvenile and adult quiescent NSCs
77323 Transcriptomic differences between juvenile and adult quiescent NSCs
77324 Transcriptomic differences between juvenile and adult quiescent NSCs
77325 Transcriptomic differences between juvenile and adult quiescent NSCs
77326 Transcriptomic differences between juvenile and adult quiescent NSCs
77327 Transcriptomic differences between juvenile and adult quiescent NSCs
77328 RNA Seq analysis in mutant zebrafish reveals role of U1C protein in alternative splicing regulation
77329 RNA Seq analysis in mutant zebrafish reveals role of U1C protein in alternative splicing regulation
      sample.accession experiment.accession earliest_date
1     DRS233566        DRX303511            2022-04-01
2     DRS233565        DRX303510            2022-04-01
3     DRS233564        DRX303509            2022-04-01
4     DRS233563        DRX303508            2022-04-01
5     DRS233562        DRX303507            2022-04-01
6     DRS233561        DRX303506            2022-04-01
7     DRS231989        DRX305194            2022-03-16
8     DRS231988        DRX305193            2022-03-16
9     DRS231987        DRX305192            2022-03-16
10    DRS231986        DRX305191            2022-03-16
11    DRS231985        DRX305190            2022-03-16
12    DRS231984        DRX305189            2022-03-16
13    DRS231983        DRX305188            2022-03-16
14    DRS231982        DRX305187            2022-03-16
15    DRS217313        DRX323973            2021-12-23
16    DRS217312        DRX323972            2021-12-23
17    DRS217311        DRX323971            2021-12-23
18    DRS217310        DRX323970            2021-12-23
19    DRS217309        DRX323969            2021-12-23
20    DRS217308        DRX323968            2021-12-23
21    DRS217307        DRX323967            2021-12-23
22    DRS217306        DRX323966            2021-12-23
23    DRS217305        DRX323965            2021-12-23
24    DRS217304        DRX323964            2021-12-23
25    DRS217303        DRX323963            2021-12-23
26    DRS217302        DRX323962            2021-12-23
27    DRS217318        DRX323961            2021-12-23
28    DRS217317        DRX323960            2021-12-23
29    DRS217316        DRX323959            2021-12-23
30    DRS217315        DRX323958            2021-12-23
⋮     ⋮                ⋮                    ⋮
77300 SRS18433956      SRX21172619          2023-07-27
77301 SRS18433956      SRX21172619          2023-07-27
77302 SRS18439483      SRX21178634          2023-07-28
77303 SRS18439482      SRX21178633          2023-07-28
77304 SRS18446706      SRX21186685          2023-07-28
77305 SRS18446705      SRX21186684          2023-07-28
77306 SRS18446703      SRX21186682          2023-07-28
77307 SRS18446702      SRX21186681          2023-07-28
77308 SRS18446700      SRX21186679          2023-07-28
77309 SRS18446699      SRX21186678          2023-07-28
77310 SRS18446697      SRX21186676          2023-07-28
77311 SRS18446696      SRX21186675          2023-07-28
77312 SRS18446704      SRX21186683          2023-07-28
77313 SRS18446701      SRX21186680          2023-07-28
77314 SRS18446698      SRX21186677          2023-07-28
77315 SRS18446695      SRX21186674          2023-07-28
77316 SRS18446641      SRX21186620          2023-07-28
77317 SRS18446640      SRX21186619          2023-07-28
77318 SRS18446639      SRX21186618          2023-07-28
77319 SRS18446638      SRX21186617          2023-07-28
77320 SRS18446637      SRX21186616          2023-07-28
77321 SRS18446636      SRX21186615          2023-07-28
77322 SRS18446635      SRX21186614          2023-07-28
77323 SRS18446634      SRX21186613          2023-07-28
77324 SRS18446633      SRX21186612          2023-07-28
77325 SRS18446632      SRX21186611          2023-07-28
77326 SRS18446631      SRX21186610          2023-07-28
77327 SRS18446630      SRX21186609          2023-07-28
77328 SRS114570        SRX026483            2011-03-31
77329 SRS114569        SRX026482            2011-03-31
      experiment.title
1     Illumina NovaSeq 6000 paired end sequencing of SAMD00399013
2     Illumina NovaSeq 6000 paired end sequencing of SAMD00399012
3     Illumina NovaSeq 6000 paired end sequencing of SAMD00399011
4     Illumina NovaSeq 6000 paired end sequencing of SAMD00399010
5     Illumina NovaSeq 6000 paired end sequencing of SAMD00399009
6     Illumina NovaSeq 6000 paired end sequencing of SAMD00399008
7     Illumina NovaSeq 6000 paired end sequencing of SAMD00400823
8     Illumina NovaSeq 6000 paired end sequencing of SAMD00400822
9     Illumina NovaSeq 6000 paired end sequencing of SAMD00400821
10    Illumina NovaSeq 6000 paired end sequencing of SAMD00400820
11    Illumina NovaSeq 6000 paired end sequencing of SAMD00400819
12    Illumina NovaSeq 6000 paired end sequencing of SAMD00400818
13    Illumina NovaSeq 6000 paired end sequencing of SAMD00400817
14    Illumina NovaSeq 6000 paired end sequencing of SAMD00400816
15    NextSeq 2000 sequencing of SAMD00422597
16    NextSeq 2000 sequencing of SAMD00422596
17    NextSeq 2000 sequencing of SAMD00422595
18    NextSeq 2000 sequencing of SAMD00422594
19    NextSeq 2000 sequencing of SAMD00422593
20    NextSeq 2000 sequencing of SAMD00422592
21    NextSeq 2000 sequencing of SAMD00422591
22    NextSeq 2000 sequencing of SAMD00422590
23    NextSeq 2000 sequencing of SAMD00422589
24    NextSeq 2000 sequencing of SAMD00422588
25    NextSeq 2000 sequencing of SAMD00422587
26    NextSeq 2000 sequencing of SAMD00422586
27    NextSeq 2000 sequencing of SAMD00422602
28    NextSeq 2000 sequencing of SAMD00422601
29    NextSeq 2000 sequencing of SAMD00422600
30    NextSeq 2000 sequencing of SAMD00422599
⋮     ⋮
77300 GSM7664321: Injury Control  snRNA seq; Danio rerio; RNA Seq
77301 GSM7664321: Injury Control  snRNA seq; Danio rerio; RNA Seq
77302 GSM7666321: salvianolate treated zebrafish embryos; Danio rerio; RNA Seq
77303 GSM7666320: WT; Danio rerio; RNA Seq
77304 GSM7668467: Experiment 13  tgher4:RFP low; Danio rerio; RNA Seq
77305 GSM7668466: Experiment 13  tgher4:RFP high; Danio rerio; RNA Seq
77306 GSM7668464: Experiment 12  tgher4:RFP low; Danio rerio; RNA Seq
77307 GSM7668463: Experiment 12  tgher4:RFP high; Danio rerio; RNA Seq
77308 GSM7668461: Experiment 11  tgher4:RFP low; Danio rerio; RNA Seq
77309 GSM7668460: Experiment 11  tgher4:RFP high; Danio rerio; RNA Seq
77310 GSM7668458: Experiment 10  tgher4:RFP low; Danio rerio; RNA Seq
77311 GSM7668457: Experiment 10  tgher4:RFP high; Danio rerio; RNA Seq
77312 GSM7668465: Experiment 13  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77313 GSM7668462: Experiment 12  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77314 GSM7668459: Experiment 11  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77315 GSM7668456: Experiment 10  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77316 GSM7668494: Experiment 8  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77317 GSM7668493: Experiment 8  tgher4:RFP; Danio rerio; RNA Seq
77318 GSM7668492: Experiment 6  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77319 GSM7668491: Experiment 6  tgher4:RFP; Danio rerio; RNA Seq
77320 GSM7668490: Experiment 4  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77321 GSM7668489: Experiment 4  tgher4:RFP; Danio rerio; RNA Seq
77322 GSM7668488: Experiment 3  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77323 GSM7668487: Experiment 3  tgher4:RFP; Danio rerio; RNA Seq
77324 GSM7668486: Experiment 2  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77325 GSM7668485: Experiment 2  tgher4:RFP; Danio rerio; RNA Seq
77326 GSM7668484: Experiment 1  tgher4:RFP  tgmcm5:gfp; Danio rerio; RNA Seq
77327 GSM7668483: Experiment 1  tgher4:RFP; Danio rerio; RNA Seq
77328 3 dpf mutant zebrafish embryos
77329 3 dpf wildtype embryos
      experiment.attributes sample.title                                    ⋯
1     NA                    RNA seq of wild type sibling sample3            ⋯
2     NA                    RNA seq of wild type sibling sample2            ⋯
3     NA                    RNA seq of wild type sibling sample1            ⋯
4     NA                    RNA seq of banp mutant sample3                  ⋯
5     NA                    RNA seq of banp mutant sample2                  ⋯
6     NA                    RNA seq of banp mutant sample1                  ⋯
7     NA                    wildtype sibling sample4                        ⋯
8     NA                    wildtype sibling sample3                        ⋯
9     NA                    wildtype sibling sample2                        ⋯
10    NA                    wildtype sibling sample1                        ⋯
11    NA                    strip1 mutant sample4                           ⋯
12    NA                    strip1 mutant sample3                           ⋯
13    NA                    strip1 mutant sample2                           ⋯
14    NA                    strip1 mutant sample1                           ⋯
15    NA                    rRNA mock community at 28 degrees rep 3         ⋯
16    NA                    rRNA mock community at 28 degrees rep 2         ⋯
17    NA                    rRNA mock community at 28 degrees rep 1         ⋯
18    NA                    rRNA mock community at 19 degrees rep 3         ⋯
19    NA                    rRNA mock community at 19 degrees rep 2         ⋯
20    NA                    rRNA mock community at 19 degrees rep 1         ⋯
21    NA                    rRNA mock community at 10 degrees rep 3         ⋯
22    NA                    rRNA mock community at 10 degrees rep 2         ⋯
23    NA                    rRNA mock community at 10 degrees rep 1         ⋯
24    NA                    mRNA mock community at 28 degrees rep 3         ⋯
25    NA                    mRNA mock community at 28 degrees rep 2         ⋯
26    NA                    mRNA mock community at 28 degrees rep 1         ⋯
27    NA                    mRNA mock community at 19 degrees rep 3         ⋯
28    NA                    mRNA mock community at 19 degrees rep 2         ⋯
29    NA                    mRNA mock community at 19 degrees rep 1         ⋯
30    NA                    mRNA mock community at 10 degrees rep 3         ⋯
⋮     ⋮                     ⋮                                               ⋱
77300 NA                    Injury Control  snRNA seq                       ⋯
77301 NA                    Injury Control  snRNA seq                       ⋯
77302 NA                    salvianolate treated zebrafish embryos          ⋯
77303 NA                    WT                                              ⋯
77304 NA                    Experiment 13  tgher4:RFP low                   ⋯
77305 NA                    Experiment 13  tgher4:RFP high                  ⋯
77306 NA                    Experiment 12  tgher4:RFP low                   ⋯
77307 NA                    Experiment 12  tgher4:RFP high                  ⋯
77308 NA                    Experiment 11  tgher4:RFP low                   ⋯
77309 NA                    Experiment 11  tgher4:RFP high                  ⋯
77310 NA                    Experiment 10  tgher4:RFP low                   ⋯
77311 NA                    Experiment 10  tgher4:RFP high                  ⋯
77312 NA                    Experiment 13  tgher4:RFP  tgmcm5:gfp           ⋯
77313 NA                    Experiment 12  tgher4:RFP  tgmcm5:gfp           ⋯
77314 NA                    Experiment 11  tgher4:RFP  tgmcm5:gfp           ⋯
77315 NA                    Experiment 10  tgher4:RFP  tgmcm5:gfp           ⋯
77316 NA                    Experiment 8  tgher4:RFP  tgmcm5:gfp            ⋯
77317 NA                    Experiment 8  tgher4:RFP                        ⋯
77318 NA                    Experiment 6  tgher4:RFP  tgmcm5:gfp            ⋯
77319 NA                    Experiment 6  tgher4:RFP                        ⋯
77320 NA                    Experiment 4  tgher4:RFP  tgmcm5:gfp            ⋯
77321 NA                    Experiment 4  tgher4:RFP                        ⋯
77322 NA                    Experiment 3  tgher4:RFP  tgmcm5:gfp            ⋯
77323 NA                    Experiment 3  tgher4:RFP                        ⋯
77324 NA                    Experiment 2  tgher4:RFP  tgmcm5:gfp            ⋯
77325 NA                    Experiment 2  tgher4:RFP                        ⋯
77326 NA                    Experiment 1  tgher4:RFP  tgmcm5:gfp            ⋯
77327 NA                    Experiment 1  tgher4:RFP                        ⋯
77328 NA                    Total RNA from 3 dpf mutant zebrafish embryos   ⋯
77329 NA                    Total RNA from 3 dpf wildtype zebrafish embryos ⋯
      experiment.library_construction_protocol
1     1
2     1
3     1
4     1
5     1
6     1
7     1
8     1
9     1
10    1
11    1
12    1
13    1
14    1
15    NEBNext Kit for Illumina
16    NEBNext Kit for Illumina
17    NEBNext Kit for Illumina
18    NEBNext Kit for Illumina
19    NEBNext Kit for Illumina

## Extracting terms from 'devstage:' 'age:' etc.

Not a function per se, but commands:

Note we are also pulling 'tissue:' for tissue step...

In [17]:
## next get _age _stage _tissue for the primary 6 columns
## adding hours post fertilization:97 conversion in replace string portion
metadata_curationstep2 <- metadata_curationstep1clean %>%
  mutate(
    across(
      c(experiment.title, experiment.attributes, sample.title, sample.attributes, GEOsample.title, GEOsample.characteristics),
      ~ .x %>%
        ## remove all tildes and parentheses also - & , to spaces (and further down _ to space)
        str_replace_all("[~()]", "") %>% 
        str_replace_all("-", " ") %>%
        str_replace_all(",", " ") %>% 
        str_replace_all("_", " ") %>% 
        str_replace_all(regex("thirty two", ignore_case = TRUE), "32") %>%
        str_replace_all(regex("thirty", ignore_case = TRUE), "30") %>%
        str_replace_all(regex("forty eight", ignore_case = TRUE), "48") %>%
        str_replace_all(regex("fourteen", ignore_case = TRUE), "14") %>%
        str_replace_all(regex("twenty nine", ignore_case = TRUE), "29") %>%
        str_replace_all(regex("twenty two", ignore_case = TRUE), "22") %>%
        str_replace_all(regex("one", ignore_case = TRUE), "1") %>%
        str_replace_all(regex("two", ignore_case = TRUE), "2") %>%
        str_replace_all(regex("three", ignore_case = TRUE), "3") %>%
        str_replace_all(regex("four", ignore_case = TRUE), "4") %>%
        str_replace_all(regex("five", ignore_case = TRUE), "5") %>%
        str_replace_all(regex("six", ignore_case = TRUE), "6") %>%
        str_replace_all(regex("seven", ignore_case = TRUE), "7") %>%
        str_replace_all(regex("eight", ignore_case = TRUE), "8") %>%
        str_replace_all(regex("nine", ignore_case = TRUE), "9") %>%
        # your existing “lesion stage” → “lesion stg”
        str_replace_all(regex("lesion stage", ignore_case = TRUE), "lesion stg") %>%
        # you can add more str_replace_all() lines here as needed disease_stage
        str_replace_all(regex("regeneration stage", ignore_case = TRUE), "regeneration stg") %>%
        str_replace_all(regex("at larval stage", ignore_case = TRUE), "at larval stg") %>%
        str_replace_all(regex("treatment /stage", ignore_case = TRUE), "treatment stg") %>%
        str_replace_all(regex("tumor stage", ignore_case = TRUE), "tumor stg") %>%
        str_replace_all(regex("age:4.5 MO", ignore_case = TRUE), "age:4.5 months") %>%
        str_replace_all(regex("age:4.6 MO", ignore_case = TRUE), "age:4.6 months") %>%
        str_replace_all(regex("age:4.7 MO", ignore_case = TRUE), "age:4.7 months") %>%
        str_replace_all(regex("age:5.0 MO", ignore_case = TRUE), "age:5.0 months") %>%
        str_replace_all(regex("age:5.O MO", ignore_case = TRUE), "age:5.0 months") %>%
        str_replace_all(regex("age:7.5 MO", ignore_case = TRUE), "age:7.5 months") %>%
        str_replace_all(regex("age:8.4 MO", ignore_case = TRUE), "age:8.4 months") %>%
        str_replace_all(regex("age:10.1 MO", ignore_case = TRUE), "age:10.1 months") %>%
        ## also 1-cell| with 1cell| note have to add \\ before pipe and only in these columns 1 cell embryos| and just fertilized 1 cell embryos also 1 cell embryo 
        str_replace_all(regex(":1 cell\\|", ignore_case = TRUE), ":1cell\\|") %>%
        str_replace_all(regex(":1 cell embryos\\|", ignore_case = TRUE), ":1cell embryos\\|") %>%
        str_replace_all(regex("just fertilized 1 cell embryos", ignore_case = TRUE), "just fertilized 1cell embryos") %>%
        str_replace_all(regex("1 cell embryo ", ignore_case = TRUE), "1cell embryo ") %>%
        # str_replace_all(regex(" MO\\|", ignore_case = FALSE), "months") %>% - hmm only replace in _age columns? better if adding a pipe? no best to skip
        ## note disease_stage is changed to disease stage above
        str_replace_all(regex("disease stage", ignore_case = TRUE), "disease stg") %>%
        # new rule: capture the digits after "hours post fertilization:" and append "hpf"
        #### match “hours post fertilization:”, capture digits, then a literal “|”
        #str_replace_all(regex("hours post fertilization:(\\d+)", ignore_case = TRUE), "\\1hpf") %>% 
        str_replace_all(regex("hours post fertilization:(\\d+)\\|", ignore_case = TRUE),
          # replace with “stage:<digits>hpf|”
          "stage:\\1hpf|") %>% 
        # new rule: “injection at 1-cell stage” → “injection at 1-cell stg”
        str_replace_all(regex("injection at 1-cell stage", ignore_case = TRUE), "injection at 1-cell stg")
      
    )
  ) %>%
# 1b) normalize "source name:" and "cell type:" to "tissue:" when "tissue:" is not present
## update - only should replace one term and cell type is always redundant with source name
  mutate(
    across(
      c(experiment.title, experiment.attributes, sample.title, sample.attributes, GEOsample.title, GEOsample.characteristics),
      ~ if_else(
        !str_detect(., regex("tissue:", ignore_case = TRUE)),
        str_replace_all(., regex("source name:", ignore_case = TRUE), "tissue:"),
        .
      )
    )
  ) %>%
  # 2) extract *all* tage: and age: patterns, collapsing with "|"
  mutate(
    across(
      c(experiment.title, experiment.attributes, sample.title, sample.attributes, GEOsample.title, GEOsample.characteristics),
      .fns = list(
        # 1) match "tage:" followed by anything up to | or end
        devstage = ~ map_chr(
          str_extract_all(., "(?<=tage:)[^|]+"),
          ~ if (length(.x)>0) paste(.x, collapse="|") else NA_character_
        ),
        # 2) match "age:" at start OR after a pipe 
        age = ~ map_chr(
          str_extract_all(., "(?<=^age:|\\|age:)[^|]+"),
          ~ if (length(.x)>0) paste(.x, collapse="|") else NA_character_
        ),
        # 3) match "tissue:" followed by anything up to | or end
        tissue = ~ map_chr(
          str_extract_all(., "(?<=tissue:)[^|]+"),
          ~ if (length(.x)>0) paste(.x, collapse="|") else NA_character_
        )
      ),
      .names = "{.col}_{.fn}"
    )
  )

In [18]:
## move the non six primary columns and their new versions to the end...
metadata_curationstep2 <- metadata_curationstep2 %>% relocate(run.title,run.alias,run.attributes,experiment.alias,experiment.library_name,experiment.design_description,experiment.library_construction_protocol,sample.description,sample.alias,GEOsample.dataprocessing,GEOsample.source,GEOsample.treatmentprotocol,GEOsample.extractprotocol,GEOsample.growthprotocol,study.abstract,study.attributes, .after = last_col())

In [19]:
## saving intermediate step
# update - saving the writing to the very end after renaming of columns...
#write.table(metadata_curationstep2, file = paste0("zf_metadata_curationstep2clean.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

## First dev stage pass - searching these _devstage and _age columns

Using the classify_stage2025first function

In [20]:
metadata_curationstep3 <- metadata_curationstep2

In [21]:
## iterate through many of the columns
# classify_stage2025first function on 6 x _devstage & _age columns
## work through the list c("experiment.title","experiment.attributes", "sample.title", "sample.attributes", "GEOsample.title", "GEOsample.characteristics", "run.title", "run.alias", "run.attributes", "experiment.alias", "experiment.library_name", "experiment.design_description", "experiment.library_construction_protocol", "sample.description", "sample.alias", "GEOsample.dataprocessing", "GEOsample.source", "GEOsample.treatmentprotocol", "GEOsample.extractprotocol", "GEOsample.growthprotocol", "study.abstract", "study.attributes"))

metadata_curationstep3$sample.attributes_devstage_curated <- sapply(metadata_curationstep3$sample.attributes_devstage, classify_stage2025first)
metadata_curationstep3$sample.attributes_age_curated <- sapply(metadata_curationstep3$sample.attributes_age, classify_stage2025first)
metadata_curationstep3$sample.title_devstage_curated <- sapply(metadata_curationstep3$sample.title_devstage, classify_stage2025first)
metadata_curationstep3$sample.title_age_curated <- sapply(metadata_curationstep3$sample.title_age, classify_stage2025first)


metadata_curationstep3$experiment.attributes_devstage_curated <- sapply(metadata_curationstep3$experiment.attributes_devstage, classify_stage2025first)
metadata_curationstep3$experiment.attributes_age_curated <- sapply(metadata_curationstep3$experiment.attributes_age, classify_stage2025first)
metadata_curationstep3$experiment.title_devstage_curated <- sapply(metadata_curationstep3$experiment.title_devstage, classify_stage2025first)
metadata_curationstep3$experiment.title_age_curated <- sapply(metadata_curationstep3$experiment.title_age, classify_stage2025first)

metadata_curationstep3$GEOsample.title_devstage_curated <- sapply(metadata_curationstep3$GEOsample.title_devstage, classify_stage2025first)
metadata_curationstep3$GEOsample.title_age_curated <- sapply(metadata_curationstep3$GEOsample.title_age, classify_stage2025first)
metadata_curationstep3$GEOsample.characteristics_devstage_curated <- sapply(metadata_curationstep3$GEOsample.characteristics_devstage, classify_stage2025first)
metadata_curationstep3$GEOsample.characteristics_age_curated <- sapply(metadata_curationstep3$GEOsample.characteristics_age, classify_stage2025first)

In [22]:
## now combine all of these terms into one column

metadata_curationstep3c <- metadata_curationstep3 %>% unite("runexpsample_devstage_curated_first0", ends_with("_curated"), sep = ",", remove = TRUE, na.rm = TRUE)
metadata_curationstep3c <- metadata_curationstep3c %>% arrange(runexpsample_devstage_curated_first0)

In [23]:
# Clean labels
# Function to clean a single label string
cleanlabels1 <- function(label_string) {
  parts <- str_split(label_string, ",")[[1]] %>%
    str_trim()
  deduped <- parts[!duplicated(parts)]
  cleaned <- deduped[deduped != "Undetermined"]
  if (length(cleaned) == 0) {
    return("Undetermined")
  } else {
    sorted <- sort(cleaned)  # <-- this makes the order consistent
    return(paste(sorted, collapse = ","))
  }
}

In [24]:
# Apply the cleaning function to the column
metadata_curationstep4 <- metadata_curationstep3c %>% mutate(runexpsample_devstage_curated_first = map_chr(runexpsample_devstage_curated_first0, cleanlabels1))

In [25]:
## check
metadata_curationstep4 %>% group_by(runexpsample_devstage_curated_first) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 29 × 2
   runexpsample_devstage_curated_first     n
   <chr>                               <int>
 1 Undetermined                        24676
 2 Larval                              15953
 3 Adult                               12571
 4 Pharyngula                           6708
 5 Hatching                             5179
 6 Gastrula                             4459
 7 Segmentation                         3471
 8 Blastula                             2163
 9 Juvenile                              984
10 Cleavage                              532
11 Zygote                                299
12 Juvenile,Larval                        79
13 Hatching,Larval                        76
14 Pharyngula,Segmentation                46
15 Adult,Juvenile                         39
16 Blastula,Gastrula                      15
17 Larval,Pharyngula                      15
18 Adult,Pharyngula                       12
19 Adult,Hatching                          8
20 Adult,Larval                            8
21 Hatching,Pharyngula                     8
22 Larval,Pharyngula,Segmentation          8
23 Pharyngula,Zygote                       6
24 Gastrula,Hatching                       5
25 Juvenile,Pharyngula,Segmentation        3
26 Adult,Blastula                          2
27 Hatching,Pharyngula,Segmentation        2
28 Adult,Pharyngula,Segmentation           1
29 Blastula,Cleavage                       1

## Second dev stage pass - searching all run/experiment/sample/GEOsample columns

Using the classify_stage2025 function

In [26]:
metadata_curationstep4$experiment.title_curated <- sapply(metadata_curationstep4$experiment.title, classify_stage2025)
metadata_curationstep4$experiment.attributes_curated <- sapply(metadata_curationstep4$experiment.attributes, classify_stage2025)
metadata_curationstep4$sample.title_curated <- sapply(metadata_curationstep4$sample.title, classify_stage2025)
metadata_curationstep4$sample.attributes_curated <- sapply(metadata_curationstep4$sample.attributes, classify_stage2025)
metadata_curationstep4$GEOsample.title_curated <- sapply(metadata_curationstep4$GEOsample.title, classify_stage2025)
metadata_curationstep4$GEOsample.characteristics_curated <- sapply(metadata_curationstep4$GEOsample.characteristics, classify_stage2025)

#metadata_curationstep4o <- metadata_curationstep4

metadata_curationstep4$run.title_curated <- sapply(metadata_curationstep4$run.title, classify_stage2025)
metadata_curationstep4$run.alias_curated <- sapply(metadata_curationstep4$run.alias, classify_stage2025)
metadata_curationstep4$run.attributes_curated <- sapply(metadata_curationstep4$run.attributes, classify_stage2025)
metadata_curationstep4$experiment.alias_curated <- sapply(metadata_curationstep4$experiment.alias, classify_stage2025)
metadata_curationstep4$experiment.library_name_curated <- sapply(metadata_curationstep4$experiment.library_name, classify_stage2025)
metadata_curationstep4$experiment.design_description_curated <- sapply(metadata_curationstep4$experiment.design_description, classify_stage2025)
metadata_curationstep4$experiment.library_construction_protocol_curated <- sapply(metadata_curationstep4$experiment.library_construction_protocol, classify_stage2025)


metadata_curationstep4$sample.description_curated <- sapply(metadata_curationstep4$sample.description, classify_stage2025)
metadata_curationstep4$sample.alias_curated <- sapply(metadata_curationstep4$sample.alias, classify_stage2025)
metadata_curationstep4$GEOsample.dataprocessing_curated <- sapply(metadata_curationstep4$GEOsample.dataprocessing, classify_stage2025)
metadata_curationstep4$GEOsample.source_curated <- sapply(metadata_curationstep4$GEOsample.source, classify_stage2025)
metadata_curationstep4$GEOsample.treatmentprotocol_curated <- sapply(metadata_curationstep4$GEOsample.treatmentprotocol, classify_stage2025)
metadata_curationstep4$GEOsample.extractprotocol_curated <- sapply(metadata_curationstep4$GEOsample.extractprotocol, classify_stage2025)
metadata_curationstep4$GEOsample.growthprotocol_curated <- sapply(metadata_curationstep4$GEOsample.growthprotocol, classify_stage2025)

In [27]:
## another round of uniting note only newest columns still end in _curated

metadata_curationstep4c <- metadata_curationstep4 %>% unite("runexpsample_devstage_curated_second0", ends_with("_curated"), sep = ",", remove = TRUE, na.rm = TRUE)

In [28]:
# Apply the cleaning function to the column
metadata_curationstep5 <- metadata_curationstep4c %>% mutate(runexpsample_devstage_curated_second = map_chr(runexpsample_devstage_curated_second0, cleanlabels1))

In [29]:
## now coalesce only after creating NAs from curated_first when Unclassified
metadata_curationstep5 <- metadata_curationstep5 %>% mutate(runexpsample_devstage_curated_first = na_if(runexpsample_devstage_curated_first, "Undetermined"))
metadata_curationstep5 <- metadata_curationstep5 %>% mutate(runexpsample_devstage_curated_firstandsecond = coalesce(runexpsample_devstage_curated_first,runexpsample_devstage_curated_second))

## moving some columns to back
metadata_curationstep5 <- metadata_curationstep5 %>% relocate(runexpsample_devstage_curated_first0, .after = last_col())
metadata_curationstep5 <- metadata_curationstep5 %>% relocate(runexpsample_devstage_curated_second0, .after = last_col())

In [30]:
## add undetermined back in 
metadata_curationstep5$runexpsample_devstage_curated_first <- metadata_curationstep5$runexpsample_devstage_curated_first %>% replace_na("Undetermined")

In [31]:
## check this result
metadata_curationstep5 %>% group_by(runexpsample_devstage_curated_firstandsecond) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 67 × 2
   runexpsample_devstage_curated_firstandsecond     n
   <chr>                                        <int>
 1 Larval                                       19709
 2 Adult                                        15670
 3 Undetermined                                 10064
 4 Pharyngula                                    7444
 5 Hatching                                      5782
 6 Gastrula                                      4676
 7 Segmentation                                  3626
 8 Juvenile                                      2710
 9 Blastula                                      2320
10 Blastula,Cleavage,Gastrula                    1157
11 Cleavage                                       676
12 Zygote                                         538
13 Larval,Pharyngula                              267
14 Adult,Larval                                   266
15 Gastrula,Larval                                204
16 Hatching,Larval                                199
17 Blastula,Larval                                164
18 Hatching,Pharyngula                            156
19 Juvenile,Larval                                151
20 Gastrula,Hatching                              131
21 Pharyngula,Segmentation                        118
22 Adult,Hatching                                 107
23 Blastula,Gastrula                               91
24 Adult,Juvenile                                  89
25 Adult,Juvenile,Larval                           86
26 Blastula,Gastrula,Hatching                      78
27 Blastula,Zygote                                 65
28 Gastrula,Pharyngula,Segmentation                60
29 Hatching,Larval,Pharyngula                      60
30 Adult,Cleavage,Hatching,Larval                  54
31 Gastrula,Pharyngula                             45
32 Cleavage,Larval,Pharyngula                      44
33 Gastrula,Segmentation                           38
34 Blastula,Gastrula,Hatching,Larval               32
35 Blastula,Larval,Zygote                          32
# ℹ 32 more rows

## Third dev stage pass - running coarse function on the same run/experiment/sample/GEOsample columns curation columns

Using the classify_stage_coarse2025 function

In [32]:
metadata_curationstep6 <- metadata_curationstep5

In [33]:
## note the coarse curation function looks at runexpsample_devstage_curated_firstandsecond column and both creates
## coarse category based on it, it also searches again for keywords if it is Undetermined

In [34]:
# coarse function on the 20 main run/experiment/sample/GEOsample columns
metadata_curationstep6$experiment.title_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$experiment.title, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$experiment.attributes_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$experiment.attributes, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$sample.title_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$sample.title, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)

metadata_curationstep6$sample.attributes_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$sample.attributes, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.title_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.title, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.characteristics_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.characteristics, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)


metadata_curationstep6$run.title_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$run.title, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$run.alias_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$run.alias, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$run.attributes_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$run.attributes, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$experiment.alias_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$experiment.alias, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$experiment.library_name_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$experiment.library_name, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$experiment.design_description_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$experiment.design_description, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$experiment.library_construction_protocol_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$experiment.library_construction_protocol, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)


metadata_curationstep6$sample.description_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$sample.description, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$sample.alias_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$sample.alias, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.dataprocessing_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.dataprocessing, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.source_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.source, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.treatmentprotocol_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.treatmentprotocol, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.extractprotocol_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.extractprotocol, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep6$GEOsample.growthprotocol_coarsecurated <- mapply(classify_stage_coarse2025, metadata_curationstep6$GEOsample.growthprotocol, metadata_curationstep6$runexpsample_devstage_curated_firstandsecond)

In [35]:
## another round of uniting this time on _coarsecurated columns

metadata_curationstep6c <- metadata_curationstep6 %>% unite("runexpsample_devstage_coarsecurated0", ends_with("_coarsecurated"), sep = ",", remove = TRUE, na.rm = TRUE)

In [36]:
# Apply the cleaning function to the column
metadata_curationstep7 <- metadata_curationstep6c %>% mutate(runexpsample_devstage_coarsecurated = map_chr(runexpsample_devstage_coarsecurated0, cleanlabels1))
metadata_curationstep7 %>% group_by(runexpsample_devstage_coarsecurated) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

## relocate some columns to the end
metadata_curationstep7 <- metadata_curationstep7 %>% relocate(runexpsample_devstage_curated_second, .after = last_col())
metadata_curationstep7 <- metadata_curationstep7 %>% relocate(runexpsample_devstage_curated_first0, .after = last_col())
metadata_curationstep7 <- metadata_curationstep7 %>% relocate(runexpsample_devstage_curated_second0, .after = last_col())
metadata_curationstep7 <- metadata_curationstep7 %>% relocate(runexpsample_devstage_coarsecurated0, .after = last_col())

# A tibble: 15 × 2
   runexpsample_devstage_coarsecurated     n
   <chr>                               <int>
 1 Embryo                              29716
 2 Larval                              19709
 3 Adult                               15684
 4 Undetermined                         7486
 5 Juvenile                             2710
 6 Embryo,Larval                        1082
 7 Adult,Larval                          266
 8 Adult,Embryo                          186
 9 Juvenile,Larval                       151
10 Adult,Juvenile                         89
11 Adult,Embryo,Larval                    88
12 Adult,Juvenile,Larval                  86
13 Embryo,Juvenile                        26
14 Embryo,Juvenile,Larval                 26
15 Adult,Embryo,Juvenile                  24

## Only now look at study-level columns

Also using the classify_stage_coarse2025 function

In [37]:
## coarse function on study columns
metadata_curationstep7$study.title_coarselastcurated <- mapply(classify_stage_coarse2025, metadata_curationstep7$study.title, metadata_curationstep7$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep7$study.abstract_coarselastcurated <- mapply(classify_stage_coarse2025, metadata_curationstep7$study.abstract, metadata_curationstep7$runexpsample_devstage_curated_firstandsecond)
metadata_curationstep7$study.attributes_coarselastcurated <- mapply(classify_stage_coarse2025, metadata_curationstep7$study.attributes, metadata_curationstep7$runexpsample_devstage_curated_firstandsecond)

In [38]:
metadata_curationstep7c <- metadata_curationstep7 %>% unite("runexpsample_devstage_coarselastcurated0", ends_with("_coarselastcurated"), sep = ",", remove = TRUE, na.rm = TRUE)

In [39]:
# Apply the cleaning function to the column
metadata_curationstep8 <- metadata_curationstep7c %>% mutate(runexpsample_devstage_coarselastcurated = map_chr(runexpsample_devstage_coarselastcurated0, cleanlabels1))
metadata_curationstep8 %>% group_by(runexpsample_devstage_coarselastcurated) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 15 × 2
   runexpsample_devstage_coarselastcurated     n
   <chr>                                   <int>
 1 Embryo                                  29609
 2 Larval                                  21149
 3 Adult                                   16923
 4 Undetermined                             4493
 5 Juvenile                                 2716
 6 Embryo,Larval                            1189
 7 Adult,Embryo                              412
 8 Adult,Larval                              320
 9 Juvenile,Larval                           159
10 Adult,Juvenile                            101
11 Adult,Embryo,Larval                        88
12 Adult,Juvenile,Larval                      86
13 Embryo,Juvenile                            34
14 Embryo,Juvenile,Larval                     26
15 Adult,Embryo,Juvenile                      24

In [40]:
## now coalesce only after creating NAs from runexpsample_devstage_coarsecurated when Unclassified
metadata_curationstep8 <- metadata_curationstep8 %>% mutate(runexpsample_devstage_coarsecurated = na_if(runexpsample_devstage_coarsecurated, "Undetermined"))
metadata_curationstep8 <- metadata_curationstep8 %>% mutate(runexpsample_devstage_coarsecurated_alsostudy = coalesce(runexpsample_devstage_coarsecurated,runexpsample_devstage_coarselastcurated))

In [41]:
## add undetermined back in 
metadata_curationstep8$runexpsample_devstage_coarsecurated <- metadata_curationstep8$runexpsample_devstage_coarsecurated %>% replace_na("Undetermined")
metadata_curationstep8 %>% group_by(runexpsample_devstage_coarsecurated_alsostudy) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 15 × 2
   runexpsample_devstage_coarsecurated_alsostudy     n
   <chr>                                         <int>
 1 Embryo                                        30056
 2 Larval                                        21006
 3 Adult                                         16849
 4 Undetermined                                   4327
 5 Juvenile                                       2716
 6 Embryo,Larval                                  1127
 7 Adult,Embryo                                    412
 8 Adult,Larval                                    318
 9 Juvenile,Larval                                 159
10 Adult,Juvenile                                  101
11 Adult,Embryo,Larval                              88
12 Adult,Juvenile,Larval                            86
13 Embryo,Juvenile                                  34
14 Embryo,Juvenile,Larval                           26
15 Adult,Embryo,Juvenile                            24

In [42]:
## now make versions of main curation columns with multi-stage
#    runexpsample_devstage_curated_first        runexpsample_devstage_curated_firstandsecond        runexpsample_devstage_coarsecurated        runexpsample_devstage_coarsecurated_alsostudy     
## first remove some extra columns for last version

## only remove in separate step just for saving - will keep full column set for raw summary saving at very end...
# metadata_curationstep9 <- metadata_curationstep8 %>% select(-runexpsample_devstage_curated_second)
# metadata_curationstep9 <- metadata_curationstep9 %>% select(-runexpsample_devstage_curated_first0)
# metadata_curationstep9 <- metadata_curationstep9 %>% select(-runexpsample_devstage_curated_second0)
# metadata_curationstep9 <- metadata_curationstep9 %>% select(-runexpsample_devstage_coarsecurated0)
# metadata_curationstep9 <- metadata_curationstep9 %>% select(-runexpsample_devstage_coarselastcurated0)
# metadata_curationstep9 <- metadata_curationstep9 %>% select(-runexpsample_devstage_coarselastcurated)
metadata_curationstep9 <- metadata_curationstep8

In [43]:
metadata_curationstep9

      run.accession study.accession bioproject
1     ERR1706522    ERP016002       PRJEB14364
2     SRR1873571    SRP056014       PRJNA277780
3     SRR1873570    SRP056014       PRJNA277780
4     SRR1873569    SRP056014       PRJNA277780
5     SRR1873568    SRP056014       PRJNA277780
6     SRR1873567    SRP056014       PRJNA277780
7     SRR1873566    SRP056014       PRJNA277780
8     SRR1873565    SRP056014       PRJNA277780
9     SRR4017375    SRP081209       PRJNA338400
10    SRR4017374    SRP081209       PRJNA338400
11    SRR4017373    SRP081209       PRJNA338400
12    SRR4017372    SRP081209       PRJNA338400
13    SRR4017371    SRP081209       PRJNA338400
14    SRR4017370    SRP081209       PRJNA338400
15    SRR8040452    SRP165277       PRJNA495917
16    SRR8040451    SRP165277       PRJNA495917
17    SRR8040450    SRP165277       PRJNA495917
18    SRR8040449    SRP165277       PRJNA495917
19    SRR8040448    SRP165277       PRJNA495917
20    SRR8040447    SRP165277       PRJNA495917
21    SRR8040446    SRP165277       PRJNA495917
22    SRR8040445    SRP165277       PRJNA495917
23    SRR8040444    SRP165277       PRJNA495917
24    SRR8040443    SRP165277       PRJNA495917
25    SRR8040442    SRP165277       PRJNA495917
26    SRR8040441    SRP165277       PRJNA495917
27    SRR8040440    SRP165277       PRJNA495917
28    SRR8040439    SRP165277       PRJNA495917
29    SRR8040438    SRP165277       PRJNA495917
30    SRR8040437    SRP165277       PRJNA495917
⋮     ⋮             ⋮               ⋮
77300 SRR23610254   SRP424410       PRJNA938397
77301 SRR23610255   SRP424410       PRJNA938397
77302 SRR23610256   SRP424410       PRJNA938397
77303 SRR23610257   SRP424410       PRJNA938397
77304 SRR26395043   SRP466518       PRJNA1028258
77305 SRR26395044   SRP466518       PRJNA1028258
77306 SRR26395045   SRP466518       PRJNA1028258
77307 SRR26395046   SRP466518       PRJNA1028258
77308 SRR26395047   SRP466518       PRJNA1028258
77309 SRR26395048   SRP466518       PRJNA1028258
77310 SRR26395049   SRP466518       PRJNA1028258
77311 SRR26395052   SRP466518       PRJNA1028258
77312 SRR26395063   SRP466518       PRJNA1028258
77313 SRR6818806    SRP134178       PRJNA437204
77314 SRR6818807    SRP134178       PRJNA437204
77315 SRR6818808    SRP134178       PRJNA437204
77316 SRR6818810    SRP134178       PRJNA437204
77317 SRR6818815    SRP134178       PRJNA437204
77318 SRR6818816    SRP134178       PRJNA437204
77319 SRR9849863    SRP216580       PRJNA556992
77320 SRR9849864    SRP216580       PRJNA556992
77321 SRR10863001   SRP241074       PRJNA597223
77322 SRR10863002   SRP241074       PRJNA597223
77323 SRR10863005   SRP241074       PRJNA597223
77324 SRR10863025   SRP241074       PRJNA597223
77325 SRR10863026   SRP241074       PRJNA597223
77326 SRR10863038   SRP241074       PRJNA597223
77327 SRR10863039   SRP241074       PRJNA597223
77328 SRR10863040   SRP241074       PRJNA597223
77329 SRR10863041   SRP241074       PRJNA597223
      study.title
1     Transcriptome profiling of zebrafish actin prl3 1 transgenic embryos
2     Identification of small non coding RNAs in zebrafish
3     Identification of small non coding RNAs in zebrafish
4     Identification of small non coding RNAs in zebrafish
5     Identification of small non coding RNAs in zebrafish
6     Identification of small non coding RNAs in zebrafish
7     Identification of small non coding RNAs in zebrafish
8     Identification of small non coding RNAs in zebrafish
9     Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
10    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
11    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
12    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
13    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
14    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
15    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
16    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
17    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
18    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
19    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
20    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
21    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
22    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
23    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
24    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
25    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
26    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
27    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
28    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
29    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
30    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
⋮     ⋮
77300 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77301 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77302 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77303 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77304 Zygotic activation of transposable elements during zebrafish early embryogenesis
77305 Zygotic activation of transposable elements during zebrafish early embryogenesis
77306 Zygotic activation of transposable elements during zebrafish early embryogenesis
77307 Zygotic activation of transposable elements during zebrafish early embryogenesis
77308 Zygotic activation of transposable elements during zebrafish early embryogenesis
77309 Zygotic activation of transposable elements during zebrafish early embryogenesis
77310 Zygotic activation of transposable elements during zebrafish early embryogenesis
77311 Zygotic activation of transposable elements during zebrafish early embryogenesis
77312 Zygotic activation of transposable elements during zebrafish early embryogenesis
77313 Danio rerio Raw sequence reads
77314 Danio rerio Raw sequence reads
77315 Danio rerio Raw sequence reads
77316 Danio rerio Raw sequence reads
77317 Danio rerio Raw sequence reads
77318 Danio rerio Raw sequence reads
77319 Global identification of circular RNAs during zebrafish embryogenesis
77320 Global identification of circular RNAs during zebrafish embryogenesis
77321 Danio rerio primordial germ cell expression pofiling
77322 Danio rerio primordial germ cell expression pofiling
77323 Danio rerio primordial germ cell expression pofiling
77324 Danio rerio primordial germ cell expression pofiling
77325 Danio rerio primordial germ cell expression pofiling
77326 Danio rerio primordial germ cell expression pofiling
77327 Danio rerio primordial germ cell expression pofiling
77328 Danio rerio primordial germ cell expression pofiling
77329 Danio rerio primordial germ cell expression pofiling
      sample.accession experiment.accession earliest_date
1     ERS1226910       ERX1776756           2016-06-28
2     SRS870223        SRX915251            2015-03-09
3     SRS870224        SRX915250            2015-03-09
4     SRS870225        SRX915249            2015-03-09
5     SRS870226        SRX915248            2015-03-09
6     SRS870227        SRX915247            2015-03-09
7     SRS870228        SRX915246            2015-03-09
8     SRS870229        SRX915245            2015-03-09
9     SRS1608493       SRX2011209           2016-08-10
10    SRS1608497       SRX2011208           2016-08-10
11    SRS1608495       SRX2011207           2016-08-10
12    SRS1608494       SRX2011206           2016-08-10
13    SRS1608492       SRX2011205           2016-08-10
14    SRS1608489       SRX2011204           2016-08-10
15    SRS3925946       SRX4870965           2018-10-12
16    SRS3925945       SRX4870964           2018-10-12
17    SRS3925943       SRX4870962           2018-10-12
18    SRS3925942       SRX4870961           2018-10-12
19    SRS3925941       SRX4870960           2018-10-12
20    SRS3925940       SRX4870959           2018-10-12
21    SRS3925939       SRX4870958           2018-10-12
22    SRS3925938       SRX4870957           2018-10-12
23    SRS3925937       SRX4870956           2018-10-12
24    SRS3925936       SRX4870955           2018-10-12
25    SRS3925988       SRX4870954           2018-10-12
26    SRS3925935       SRX4870953           2018-10-12
27    SRS3925934       SRX4870952           2018-10-12
28    SRS3925933       SRX4870951           2018-10-12
29    SRS3925932       SRX4870950           2018-10-12
30    SRS3925931       SRX4870949           2018-10-12
⋮     ⋮                ⋮                    ⋮
77300 SRS16885246      SRX19495177          2023-02-24
77301 SRS16885245      SRX19495176          2023-02-24
77302 SRS16885244      SRX19495175          2023-02-24
77303 SRS16885243      SRX19495174          2023-02-24
77304 SRS19166016      SRX22100890          2023-10-16
77305 SRS19166015      SRX22100889          2023-10-16
77306 SRS19166014      SRX22100888          2023-10-16
77307 SRS19166013      SRX22100887          2023-10-16
77308 SRS19166012      SRX22100886          2023-10-16
77309 SRS19166011      SRX22100885          2023-10-16
77310 SRS19166010      SRX22100884          2023-10-16
77311 SRS19166007      SRX22100881          2023-10-16
77312 SRS19165997      SRX22100871          2023-10-16
77313 SRS3029901       SRX3775757           2018-03-08
77314 SRS3029900       SRX3775756           2018-03-08
77315 SRS3029899       SRX3775755           2018-03-08
77316 SRS3029897       SRX3775753           2018-03-08
77317 SRS3029892       SRX3775748           2018-03-08
77318 SRS3029891       SRX3775747           2018-03-08
77319 SRS5169411       SRX6604465           2019-07-27
77320 SRS5169411       SRX6604464           2019-07-27
77321 SRS5972255       SRX7533067           2020-01-10
77322 SRS5972254       SRX7533066           2020-01-10
77323 SRS5972253       SRX7533064           2020-01-10
77324 SRS5972254       SRX7533044           2020-01-10
77325 SRS5972253       SRX7533043           2020-01-10
77326 SRS5972255       SRX7533030           2020-01-10
77327 SRS5972255       SRX7533029           2020-01-10
77328 SRS5972254       SRX7533028           2020-01-10
77329 SRS5972253       SRX7533027           2020-01-10
      experiment.title
1     Illumina HiSeq 2000 paired end sequencing
2     GSM1630515: fins; Danio rerio; miRNA Seq
3     GSM1630514: skin; Danio rerio; miRNA Seq
4     GSM1630513: heart; Danio rerio; miRNA Seq
5     GSM1630512: gills; Danio rerio; miRNA Seq
6     GSM1630511: eyes; Danio rerio; miRNA Seq
7     GSM1630510: brain; Danio rerio; miRNA Seq
8     GSM1630509: adult; Danio rerio; miRNA Seq
9     GSM2266462: adult muscle 2; Danio rerio; RNA Seq
10    GSM2266461: adult muscle 1; Danio rerio; RNA Seq
11    GSM2266460: adult muscle 0; Danio rerio; RNA Seq
12    GSM2266459: adult heart 2; Danio rerio; RNA Seq
13    GSM2266458: adult heart 1; Danio rerio; RNA Seq
14    GSM2266457: adult heart 0; Danio rerio; RNA Seq
15    GSM3427234: t32lps5 RNA seq; Danio rerio; RNA Seq
16    GSM3427233: t32lps4 RNA seq; Danio rerio; RNA Seq
17    GSM3427232: t32lps3 RNA seq; Danio rerio; RNA Seq
18    GSM3427231: t32lps2 RNA seq; Danio rerio; RNA Seq
19    GSM3427230: t32lps1 RNA seq; Danio rerio; RNA Seq
20    GSM3427229: t32ct10 RNA seq; Danio rerio; RNA Seq
21    GSM3427228: t32ct8 RNA seq; Danio rerio; RNA Seq
22    GSM3427227: t32ct6 RNA seq; Danio rerio; RNA Seq
23    GSM3427226: t32ct3 RNA seq; Danio rerio; RNA Seq
24    GSM3427225: t32ct2 RNA seq; Danio rerio; RNA Seq
25    GSM3427224: t28lps8 RNA seq; Danio rerio; RNA Seq
26    GSM3427223: t28lps4 RNA seq; Danio rerio; RNA Seq
27    GSM3427222: t28lps3 RNA seq; Danio rerio; RNA Seq
28    GSM3427221: t28lps2 RNA seq; Danio rerio; RNA Seq
29    GSM3427220: t28lps1 RNA seq; Danio rerio; RNA Seq
30    GSM3427219: t28ct7 RNA seq; Danio rerio; RNA Seq
⋮     ⋮
77300 GSM7061824: 1Cell  wildtype  replicate4; Danio rerio; RNA Seq
77301 GSM7061823: 1Cell  wildtype  replicate3; Danio rerio; RNA Seq
77302 GSM7061822: 1Cell  wildtype  replicate2; Danio rerio; RNA Seq
77303 GSM7061821: 1Cell  wildtype  replicate1; Danio rerio; RNA Seq
77304 Illumina RNA seq of zebrafish: 1 cell replicate8
77305 Illumina RNA seq of zebrafish: 1 cell replicate7
77306 Illumina RNA seq of zebrafish: 1 cell replicate6
77307 Illumina RNA seq of zebrafish: 1 cell replicate5
77308 Illumina RNA seq of zebrafish: 1 cell replicate4
77309 Illumina RNA seq of zebrafish: 1 cell replicate3
77310 Illumina RNA seq of zebrafish: 1 cell replicate2
77311 Illumina RNA seq of zebrafish: 1 cell replicate1
77312 PacBio Iso seq of zebrafish: 1 cell
77313 p15 /  unfertilized
77314 p15 /  unfertilized
77315 p15 /  unfertilized
77316 WT unfertilized
77317 WT unfertilized
77318 WT unfertilized
77319 circRNA 0h 1
77320 circRNA 0h 2
77321 totalRNA of Zebrafish: zygote 0hpf
77322 totalRNA of Zebrafish: zygote 0hpf
77323 totalRNA of Zebrafish: zygote 0hpf
77324 small RNA of Zebrafish: zygotes 0hpf
77325 small RNA of Zebrafish: zygotes 0hpf
77326 mRNA of Zebrafish: zygotes 0hpf
77327 small RNA of Zebrafish: zygotes 0hpf
77328 mRNA of Zebrafish: zygotes 0hpf
77329 mRNA of Zebrafish: zygotes 0hpf
      experiment.attributes    sample.title                ⋯
1     NA                       zmp ph260 B6                ⋯
2     GEO Accession:GSM1630515 fins                        ⋯
3     GEO Accession:GSM1630514 skin                        ⋯
4     GEO Accession:GSM1630513 heart                       ⋯
5     GEO Accession:GSM1630512 gills                       ⋯
6     GEO Accession:GSM1630511 eyes                        ⋯
7     GEO Accession:GSM1630510 brain                       ⋯
8     GEO Accession:GSM1630509 adult                       ⋯
9     GEO Accession:GSM2266462 adult muscle 2              ⋯
10    GEO Accession:GSM2266461 adult muscle 1              ⋯
11    GEO Accession:GSM2266460 adult muscle 0              ⋯
12    GEO Accession:GSM2266459 adult heart 2               ⋯
13    GEO Accession:GSM2266458 adult heart 1               ⋯
14    GEO Accession:GSM2266457 adult heart 0               ⋯
15    GEO Accession:GSM3427234 t32lps5 RNA seq             ⋯
16    GEO Accession:GSM3427233 t32lps4 RNA seq             ⋯
17    GEO Accession:GSM3427232 t32lps3 RNA seq             ⋯
18    GEO Accession:GSM3427231 t32lps2 RNA seq             ⋯
19    GEO Accession:GSM3427230 t32lps1 RNA seq             ⋯
20    GEO Accession:GSM3427229 t32ct10 RNA seq             ⋯
21    GEO Accession:GSM3427228 t32ct8 RNA seq              ⋯
22    GEO Accession:GSM3427227 t32ct6 RNA seq              ⋯
23    GEO Accession:GSM3427226 t32ct3 RNA seq              ⋯
24    GEO Accession:GSM3427225 t32ct2 RNA seq              ⋯
25    GEO Accession:GSM3427224 t28lps8 RNA seq             ⋯
26    GEO Accession:GSM3427223 t28lps4 RNA seq             ⋯
27    GEO Accession:GSM3427222 t28lps3 RNA seq             ⋯
28    GEO Accession:GSM3427221 t28lps2 RNA seq             ⋯
29    GEO Accession:GSM3427220 t28lps1 RNA seq             ⋯
30    GEO Accession:GSM3427219 t28ct7 RNA seq              ⋯
⋮     ⋮                        ⋮                           ⋱
77300 NA                       1Cell  wildtype  replicate4 ⋯
77301 NA                       1Cell  wildtype  replicate3 ⋯
77302 NA                       1Cell  wildtype  replicate2 ⋯
77303 NA                       1Cell  wildtype  replicate1 ⋯
77304 NA                       NA                          ⋯
77305 NA                       NA                          ⋯
77306 NA                       NA                          ⋯
77307 NA                       NA                          ⋯
77308 NA                       NA                          ⋯
77309 NA                       NA                          ⋯
77310 NA                       NA                          ⋯
77311 NA                       NA                          ⋯
77312 NA                       NA                          ⋯
77313 NA                       NA                          ⋯
77314 NA                       NA                          ⋯
77315 NA                       NA                          ⋯
77316 NA                       NA                          ⋯
77317 NA                       NA                          ⋯
77318 NA                       NA                          ⋯
77319 NA                       NA                          ⋯
77320 NA                       NA                          ⋯
77321 NA                       NA                          ⋯
77322 NA                       NA                          ⋯
77323 NA                       NA                          ⋯
77324 NA                       NA                          ⋯
77325 NA                       NA                          ⋯
77326 NA                       NA                          ⋯
77327 NA                       NA                          ⋯
77328 NA                       NA                          ⋯
77329 NA                       NA                          ⋯
      runexpsample_devstage_curated_first
1     Adult,Pharyngula,Segmentation
2     Adult
3     Adult
4     Adult
5     Adult
6     Adult
7     Adult
8     Adult
9     Adult
10    Adult
11    Adult
12    Adult
13    Adult
14    Adult
15    Adult
16    Adult
17    Adult
18    Adult
19    Adult
20    Adult
21    Adult
22    Adult
23    Adult
24    Adult
25    Adult
26    Adult
27    Adult
28    Adult
29    Adult
30    Adult
⋮     ⋮
77300 Zygote
77301 Zygote
77302 Zygote
77303 Zygote
77304 Zygote
77305 Zygote
77306 Zygote
77307 Zygote
77308 Zygote
77309 Zygote
77310 Zygote
77311 Zygote
77312 Zygote
77313 Zygote
77314 Zygote
77315 Zygote
77316 Zygote
77317 Zygote
77318 Zygote
77319 Zygote
77320 Zygote
77321 Zygote
77322 Zygote
77323 Zygote
77324 Zygote
77325 Zygote
77326 Zygote
77327 Zygote
77328 Zygote
77329 Zygote
      runexpsample_devstage_curated_firstandsecond
1     Adult,Pharyngula,Segmentation
2     Adult
3     Adult
4     Adult
5     Adult
6     Adult
7     Adult
8     Adult
9     Adult
10    Adult
11    Adult
12    Adult
13    Adult
14    Adult
15    Adult
16    Adult
17    Adult
18    Adult
19    Adult
20    Adult
21    Adult
22    Adult
23    Adult
24    Adult
25    Adult
26    Adult
27    Adult
28    Adult
29    Adult
30    Adult
⋮     ⋮
77300 Zygote
77301 Zygote
77302 Zygote
77303 Zygote
77304 Zygote
77305 Zygote
77306 Zygote
77307 Zygote
77308 Zygote
77309 Zygote
77310 Zygote
77311 Zygote
77312 Zygote
77313 Zygote
77314 Zygote
77315 Zygote
77316 Zygote
77317 Zygote
77318 Zygote
77319 Zygote
77320 Zygote
77321 Zygote
77322 Zygote
77323 Zygote
77324 Zygote
77325 Zygote
77326 Zygote
77327 Zygote
77328 Zygote
77329 Zygote
      runexpsample_devstage_coarsecurated runexpsample_devstage_curated_second
1     Adult,Embryo                        Adult,Pharyngula,Segmentation
2     Adult                               Adult,Juvenile,Larval,Pharyngula
3     Adult                               Adult,Juvenile,Larval,Pharyngula
4     Adult                               Adult,Juvenile,Larval,Pharyngula

In [44]:
## replace any string with a comma with "multi-stage UNLESS IT HAS TUMOR
# metadata_curationstep9 <- metadata_curationstep9 %>%
#   mutate(runexpsample_devstage_curated_first2 = if_else(grepl(",", runexpsample_devstage_curated_first), "Multi-stage", runexpsample_devstage_curated_first))

# metadata_curationstep9 <- metadata_curationstep9 %>%
#   mutate(runexpsample_devstage_curated_firstandsecond2 = if_else(grepl(",", runexpsample_devstage_curated_firstandsecond), "Multi-stage", runexpsample_devstage_curated_firstandsecond))

# metadata_curationstep9 <- metadata_curationstep9 %>%
#   mutate(runexpsample_devstage_coarsecurated2 = if_else(grepl(",", runexpsample_devstage_coarsecurated), "Multi-stage", runexpsample_devstage_coarsecurated))

# metadata_curationstep9 <- metadata_curationstep9 %>%
#   mutate(runexpsample_devstage_coarsecurated_alsostudy2 = if_else(grepl(",", runexpsample_devstage_coarsecurated_alsostudy), "Multi-stage", runexpsample_devstage_coarsecurated_alsostudy))


## replace any string with a comma with "multi-stage", except if it contains "Cancer or Tumor"
metadata_curationstep9 <- metadata_curationstep9 %>%
  mutate(runexpsample_devstage_curated_first2 = case_when(
    grepl("Cancer or Tumor", runexpsample_devstage_curated_first, ignore.case = TRUE) ~ "Cancer or Tumor",
    grepl(",", runexpsample_devstage_curated_first) ~ "Multi-stage",
    TRUE ~ runexpsample_devstage_curated_first
  ))

metadata_curationstep9 <- metadata_curationstep9 %>%
  mutate(runexpsample_devstage_curated_firstandsecond2 = case_when(
    grepl("Cancer or Tumor", runexpsample_devstage_curated_firstandsecond, ignore.case = TRUE) ~ "Cancer or Tumor",
    grepl(",", runexpsample_devstage_curated_firstandsecond) ~ "Multi-stage",
    TRUE ~ runexpsample_devstage_curated_firstandsecond
  ))

metadata_curationstep9 <- metadata_curationstep9 %>%
  mutate(runexpsample_devstage_coarsecurated2 = case_when(
    grepl("Cancer or Tumor", runexpsample_devstage_coarsecurated, ignore.case = TRUE) ~ "Cancer or Tumor",
    grepl(",", runexpsample_devstage_coarsecurated) ~ "Multi-stage",
    TRUE ~ runexpsample_devstage_coarsecurated
  ))

metadata_curationstep9 <- metadata_curationstep9 %>%
  mutate(runexpsample_devstage_coarsecurated_alsostudy2 = case_when(
    grepl("Cancer or Tumor", runexpsample_devstage_coarsecurated_alsostudy, ignore.case = TRUE) ~ "Cancer or Tumor",
    grepl(",", runexpsample_devstage_coarsecurated_alsostudy) ~ "Multi-stage",
    TRUE ~ runexpsample_devstage_coarsecurated_alsostudy
  ))

In [45]:
## last column relocates - this version has 55 columns so moving these 5 to end for viewing in RStudio

metadata_curationstep9 <- metadata_curationstep9 %>% relocate(study.abstract, .after = last_col())
metadata_curationstep9 <- metadata_curationstep9 %>% relocate(study.attributes, .after = last_col())
metadata_curationstep9 <- metadata_curationstep9 %>% relocate(run.alias, .after = last_col())
metadata_curationstep9 <- metadata_curationstep9 %>% relocate(experiment.alias, .after = last_col())
metadata_curationstep9 <- metadata_curationstep9 %>% relocate(sample.alias, .after = last_col())

In [46]:
## final numbers
metadata_curationstep9 %>% group_by(runexpsample_devstage_curated_first2) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)
metadata_curationstep9 %>% group_by(runexpsample_devstage_curated_firstandsecond2) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)
metadata_curationstep9 %>% group_by(runexpsample_devstage_coarsecurated2) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)
metadata_curationstep9 %>% group_by(runexpsample_devstage_coarsecurated_alsostudy2) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 12 × 2
   runexpsample_devstage_curated_first2     n
   <chr>                                <int>
 1 Undetermined                         24676
 2 Larval                               15953
 3 Adult                                12571
 4 Pharyngula                            6708
 5 Hatching                              5179
 6 Gastrula                              4459
 7 Segmentation                          3471
 8 Blastula                              2163
 9 Juvenile                               984
10 Cleavage                               532
11 Multi-stage                            334
12 Zygote                                 299
# A tibble: 12 × 2
   runexpsample_devstage_curated_firstandsecond2     n
   <chr>                                         <int>
 1 Larval                                        19709
 2 Adult                                         15670
 3 Undetermined                                  10064
 4 Pharyngula                                     7444
 5 Hatching                                       5782
 6 Gastrula                                       4676
 7 Multi-stage                                    4114
 8 Segmentation                                   3626
 9 Juvenile                                       2710
10 Blastula                                       2320
11 Cleavage                                        676
12 Zygote                                          538
# A tibble: 6 × 2
  runexpsample_devstage_coarsecurated2     n
  <chr>                                <int>
1 Embryo                               29716
2 Larval                               19709
3 Adult                                15684
4 Undetermined                          7486
5 Juvenile                              2710
6 Multi-stage                           2024
# A tibble: 6 × 2
  runexpsample_devstage_coarsecurated_alsostudy2     n
  <chr>                                          <int>
1 Embryo                                         30056
2 Larval                                         21006
3 Adult                                          16849
4 Undetermined                                    4327
5 Juvenile                                        2716
6 Multi-stage                                     2375

In [47]:
## save devstage curation
# ## moving removing of some columns here just for this saving step:
# metadata_curationstep9fewer <- metadata_curationstep9
# metadata_curationstep9fewer <- metadata_curationstep9fewer %>% select(-runexpsample_devstage_curated_second)
# metadata_curationstep9fewer <- metadata_curationstep9fewer %>% select(-runexpsample_devstage_curated_first0)
# metadata_curationstep9fewer <- metadata_curationstep9fewer %>% select(-runexpsample_devstage_curated_second0)
# metadata_curationstep9fewer <- metadata_curationstep9fewer %>% select(-runexpsample_devstage_coarsecurated0)
# metadata_curationstep9fewer <- metadata_curationstep9fewer %>% select(-runexpsample_devstage_coarselastcurated0)
# metadata_curationstep9fewer <- metadata_curationstep9fewer %>% select(-runexpsample_devstage_coarselastcurated)

# # update - saving the writing to the very end after renaming of columns...
# #write.table(metadata_curationstep9fewer, file = paste0("all_zf_dates_devstage_curated_withGEO.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

# #write.table(metadata_curationstep9, file = paste0("all_zf_dates_devstage_curated_withGEO.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

## Tissue curation

## First pass - using those curated columns with _tissue

In [48]:
#metadata_curationstep9 <- read_tsv("all_zf_dates_devstage_curated_withGEO.tsv")

In [49]:
metadata_curationstep9

      run.accession study.accession bioproject
1     ERR1706522    ERP016002       PRJEB14364
2     SRR1873571    SRP056014       PRJNA277780
3     SRR1873570    SRP056014       PRJNA277780
4     SRR1873569    SRP056014       PRJNA277780
5     SRR1873568    SRP056014       PRJNA277780
6     SRR1873567    SRP056014       PRJNA277780
7     SRR1873566    SRP056014       PRJNA277780
8     SRR1873565    SRP056014       PRJNA277780
9     SRR4017375    SRP081209       PRJNA338400
10    SRR4017374    SRP081209       PRJNA338400
11    SRR4017373    SRP081209       PRJNA338400
12    SRR4017372    SRP081209       PRJNA338400
13    SRR4017371    SRP081209       PRJNA338400
14    SRR4017370    SRP081209       PRJNA338400
15    SRR8040452    SRP165277       PRJNA495917
16    SRR8040451    SRP165277       PRJNA495917
17    SRR8040450    SRP165277       PRJNA495917
18    SRR8040449    SRP165277       PRJNA495917
19    SRR8040448    SRP165277       PRJNA495917
20    SRR8040447    SRP165277       PRJNA495917
21    SRR8040446    SRP165277       PRJNA495917
22    SRR8040445    SRP165277       PRJNA495917
23    SRR8040444    SRP165277       PRJNA495917
24    SRR8040443    SRP165277       PRJNA495917
25    SRR8040442    SRP165277       PRJNA495917
26    SRR8040441    SRP165277       PRJNA495917
27    SRR8040440    SRP165277       PRJNA495917
28    SRR8040439    SRP165277       PRJNA495917
29    SRR8040438    SRP165277       PRJNA495917
30    SRR8040437    SRP165277       PRJNA495917
⋮     ⋮             ⋮               ⋮
77300 SRR23610254   SRP424410       PRJNA938397
77301 SRR23610255   SRP424410       PRJNA938397
77302 SRR23610256   SRP424410       PRJNA938397
77303 SRR23610257   SRP424410       PRJNA938397
77304 SRR26395043   SRP466518       PRJNA1028258
77305 SRR26395044   SRP466518       PRJNA1028258
77306 SRR26395045   SRP466518       PRJNA1028258
77307 SRR26395046   SRP466518       PRJNA1028258
77308 SRR26395047   SRP466518       PRJNA1028258
77309 SRR26395048   SRP466518       PRJNA1028258
77310 SRR26395049   SRP466518       PRJNA1028258
77311 SRR26395052   SRP466518       PRJNA1028258
77312 SRR26395063   SRP466518       PRJNA1028258
77313 SRR6818806    SRP134178       PRJNA437204
77314 SRR6818807    SRP134178       PRJNA437204
77315 SRR6818808    SRP134178       PRJNA437204
77316 SRR6818810    SRP134178       PRJNA437204
77317 SRR6818815    SRP134178       PRJNA437204
77318 SRR6818816    SRP134178       PRJNA437204
77319 SRR9849863    SRP216580       PRJNA556992
77320 SRR9849864    SRP216580       PRJNA556992
77321 SRR10863001   SRP241074       PRJNA597223
77322 SRR10863002   SRP241074       PRJNA597223
77323 SRR10863005   SRP241074       PRJNA597223
77324 SRR10863025   SRP241074       PRJNA597223
77325 SRR10863026   SRP241074       PRJNA597223
77326 SRR10863038   SRP241074       PRJNA597223
77327 SRR10863039   SRP241074       PRJNA597223
77328 SRR10863040   SRP241074       PRJNA597223
77329 SRR10863041   SRP241074       PRJNA597223
      study.title
1     Transcriptome profiling of zebrafish actin prl3 1 transgenic embryos
2     Identification of small non coding RNAs in zebrafish
3     Identification of small non coding RNAs in zebrafish
4     Identification of small non coding RNAs in zebrafish
5     Identification of small non coding RNAs in zebrafish
6     Identification of small non coding RNAs in zebrafish
7     Identification of small non coding RNAs in zebrafish
8     Identification of small non coding RNAs in zebrafish
9     Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
10    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
11    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
12    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
13    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
14    Systematic identification and characterization of long non coding RNAs in zebrafish through RNA Seq
15    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
16    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
17    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
18    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
19    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
20    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
21    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
22    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
23    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
24    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
25    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
26    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
27    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
28    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
29    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
30    Embryonic incubation temperature has a long term effect on the immune response of adult zebrafish
⋮     ⋮
77300 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77301 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77302 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77303 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77304 Zygotic activation of transposable elements during zebrafish early embryogenesis
77305 Zygotic activation of transposable elements during zebrafish early embryogenesis
77306 Zygotic activation of transposable elements during zebrafish early embryogenesis
77307 Zygotic activation of transposable elements during zebrafish early embryogenesis
77308 Zygotic activation of transposable elements during zebrafish early embryogenesis
77309 Zygotic activation of transposable elements during zebrafish early embryogenesis
77310 Zygotic activation of transposable elements during zebrafish early embryogenesis
77311 Zygotic activation of transposable elements during zebrafish early embryogenesis
77312 Zygotic activation of transposable elements during zebrafish early embryogenesis
77313 Danio rerio Raw sequence reads
77314 Danio rerio Raw sequence reads
77315 Danio rerio Raw sequence reads
77316 Danio rerio Raw sequence reads
77317 Danio rerio Raw sequence reads
77318 Danio rerio Raw sequence reads
77319 Global identification of circular RNAs during zebrafish embryogenesis
77320 Global identification of circular RNAs during zebrafish embryogenesis
77321 Danio rerio primordial germ cell expression pofiling
77322 Danio rerio primordial germ cell expression pofiling
77323 Danio rerio primordial germ cell expression pofiling
77324 Danio rerio primordial germ cell expression pofiling
77325 Danio rerio primordial germ cell expression pofiling
77326 Danio rerio primordial germ cell expression pofiling
77327 Danio rerio primordial germ cell expression pofiling
77328 Danio rerio primordial germ cell expression pofiling
77329 Danio rerio primordial germ cell expression pofiling
      sample.accession experiment.accession earliest_date
1     ERS1226910       ERX1776756           2016-06-28
2     SRS870223        SRX915251            2015-03-09
3     SRS870224        SRX915250            2015-03-09
4     SRS870225        SRX915249            2015-03-09
5     SRS870226        SRX915248            2015-03-09
6     SRS870227        SRX915247            2015-03-09
7     SRS870228        SRX915246            2015-03-09
8     SRS870229        SRX915245            2015-03-09
9     SRS1608493       SRX2011209           2016-08-10
10    SRS1608497       SRX2011208           2016-08-10
11    SRS1608495       SRX2011207           2016-08-10
12    SRS1608494       SRX2011206           2016-08-10
13    SRS1608492       SRX2011205           2016-08-10
14    SRS1608489       SRX2011204           2016-08-10
15    SRS3925946       SRX4870965           2018-10-12
16    SRS3925945       SRX4870964           2018-10-12
17    SRS3925943       SRX4870962           2018-10-12
18    SRS3925942       SRX4870961           2018-10-12
19    SRS3925941       SRX4870960           2018-10-12
20    SRS3925940       SRX4870959           2018-10-12
21    SRS3925939       SRX4870958           2018-10-12
22    SRS3925938       SRX4870957           2018-10-12
23    SRS3925937       SRX4870956           2018-10-12
24    SRS3925936       SRX4870955           2018-10-12
25    SRS3925988       SRX4870954           2018-10-12
26    SRS3925935       SRX4870953           2018-10-12
27    SRS3925934       SRX4870952           2018-10-12
28    SRS3925933       SRX4870951           2018-10-12
29    SRS3925932       SRX4870950           2018-10-12
30    SRS3925931       SRX4870949           2018-10-12
⋮     ⋮                ⋮                    ⋮
77300 SRS16885246      SRX19495177          2023-02-24
77301 SRS16885245      SRX19495176          2023-02-24
77302 SRS16885244      SRX19495175          2023-02-24
77303 SRS16885243      SRX19495174          2023-02-24
77304 SRS19166016      SRX22100890          2023-10-16
77305 SRS19166015      SRX22100889          2023-10-16
77306 SRS19166014      SRX22100888          2023-10-16
77307 SRS19166013      SRX22100887          2023-10-16
77308 SRS19166012      SRX22100886          2023-10-16
77309 SRS19166011      SRX22100885          2023-10-16
77310 SRS19166010      SRX22100884          2023-10-16
77311 SRS19166007      SRX22100881          2023-10-16
77312 SRS19165997      SRX22100871          2023-10-16
77313 SRS3029901       SRX3775757           2018-03-08
77314 SRS3029900       SRX3775756           2018-03-08
77315 SRS3029899       SRX3775755           2018-03-08
77316 SRS3029897       SRX3775753           2018-03-08
77317 SRS3029892       SRX3775748           2018-03-08
77318 SRS3029891       SRX3775747           2018-03-08
77319 SRS5169411       SRX6604465           2019-07-27
77320 SRS5169411       SRX6604464           2019-07-27
77321 SRS5972255       SRX7533067           2020-01-10
77322 SRS5972254       SRX7533066           2020-01-10
77323 SRS5972253       SRX7533064           2020-01-10
77324 SRS5972254       SRX7533044           2020-01-10
77325 SRS5972253       SRX7533043           2020-01-10
77326 SRS5972255       SRX7533030           2020-01-10
77327 SRS5972255       SRX7533029           2020-01-10
77328 SRS5972254       SRX7533028           2020-01-10
77329 SRS5972253       SRX7533027           2020-01-10
      experiment.title
1     Illumina HiSeq 2000 paired end sequencing
2     GSM1630515: fins; Danio rerio; miRNA Seq
3     GSM1630514: skin; Danio rerio; miRNA Seq
4     GSM1630513: heart; Danio rerio; miRNA Seq
5     GSM1630512: gills; Danio rerio; miRNA Seq
6     GSM1630511: eyes; Danio rerio; miRNA Seq
7     GSM1630510: brain; Danio rerio; miRNA Seq
8     GSM1630509: adult; Danio rerio; miRNA Seq
9     GSM2266462: adult muscle 2; Danio rerio; RNA Seq
10    GSM2266461: adult muscle 1; Danio rerio; RNA Seq
11    GSM2266460: adult muscle 0; Danio rerio; RNA Seq
12    GSM2266459: adult heart 2; Danio rerio; RNA Seq
13    GSM2266458: adult heart 1; Danio rerio; RNA Seq
14    GSM2266457: adult heart 0; Danio rerio; RNA Seq
15    GSM3427234: t32lps5 RNA seq; Danio rerio; RNA Seq
16    GSM3427233: t32lps4 RNA seq; Danio rerio; RNA Seq
17    GSM3427232: t32lps3 RNA seq; Danio rerio; RNA Seq
18    GSM3427231: t32lps2 RNA seq; Danio rerio; RNA Seq
19    GSM3427230: t32lps1 RNA seq; Danio rerio; RNA Seq
20    GSM3427229: t32ct10 RNA seq; Danio rerio; RNA Seq
21    GSM3427228: t32ct8 RNA seq; Danio rerio; RNA Seq
22    GSM3427227: t32ct6 RNA seq; Danio rerio; RNA Seq
23    GSM3427226: t32ct3 RNA seq; Danio rerio; RNA Seq
24    GSM3427225: t32ct2 RNA seq; Danio rerio; RNA Seq
25    GSM3427224: t28lps8 RNA seq; Danio rerio; RNA Seq
26    GSM3427223: t28lps4 RNA seq; Danio rerio; RNA Seq
27    GSM3427222: t28lps3 RNA seq; Danio rerio; RNA Seq
28    GSM3427221: t28lps2 RNA seq; Danio rerio; RNA Seq
29    GSM3427220: t28lps1 RNA seq; Danio rerio; RNA Seq
30    GSM3427219: t28ct7 RNA seq; Danio rerio; RNA Seq
⋮     ⋮
77300 GSM7061824: 1Cell  wildtype  replicate4; Danio rerio; RNA Seq
77301 GSM7061823: 1Cell  wildtype  replicate3; Danio rerio; RNA Seq
77302 GSM7061822: 1Cell  wildtype  replicate2; Danio rerio; RNA Seq
77303 GSM7061821: 1Cell  wildtype  replicate1; Danio rerio; RNA Seq
77304 Illumina RNA seq of zebrafish: 1 cell replicate8
77305 Illumina RNA seq of zebrafish: 1 cell replicate7
77306 Illumina RNA seq of zebrafish: 1 cell replicate6
77307 Illumina RNA seq of zebrafish: 1 cell replicate5
77308 Illumina RNA seq of zebrafish: 1 cell replicate4
77309 Illumina RNA seq of zebrafish: 1 cell replicate3
77310 Illumina RNA seq of zebrafish: 1 cell replicate2
77311 Illumina RNA seq of zebrafish: 1 cell replicate1
77312 PacBio Iso seq of zebrafish: 1 cell
77313 p15 /  unfertilized
77314 p15 /  unfertilized
77315 p15 /  unfertilized
77316 WT unfertilized
77317 WT unfertilized
77318 WT unfertilized
77319 circRNA 0h 1
77320 circRNA 0h 2
77321 totalRNA of Zebrafish: zygote 0hpf
77322 totalRNA of Zebrafish: zygote 0hpf
77323 totalRNA of Zebrafish: zygote 0hpf
77324 small RNA of Zebrafish: zygotes 0hpf
77325 small RNA of Zebrafish: zygotes 0hpf
77326 mRNA of Zebrafish: zygotes 0hpf
77327 small RNA of Zebrafish: zygotes 0hpf
77328 mRNA of Zebrafish: zygotes 0hpf
77329 mRNA of Zebrafish: zygotes 0hpf
      experiment.attributes    sample.title                ⋯
1     NA                       zmp ph260 B6                ⋯
2     GEO Accession:GSM1630515 fins                        ⋯
3     GEO Accession:GSM1630514 skin                        ⋯
4     GEO Accession:GSM1630513 heart                       ⋯
5     GEO Accession:GSM1630512 gills                       ⋯
6     GEO Accession:GSM1630511 eyes                        ⋯
7     GEO Accession:GSM1630510 brain                       ⋯
8     GEO Accession:GSM1630509 adult                       ⋯
9     GEO Accession:GSM2266462 adult muscle 2              ⋯
10    GEO Accession:GSM2266461 adult muscle 1              ⋯
11    GEO Accession:GSM2266460 adult muscle 0              ⋯
12    GEO Accession:GSM2266459 adult heart 2               ⋯
13    GEO Accession:GSM2266458 adult heart 1               ⋯
14    GEO Accession:GSM2266457 adult heart 0               ⋯
15    GEO Accession:GSM3427234 t32lps5 RNA seq             ⋯
16    GEO Accession:GSM3427233 t32lps4 RNA seq             ⋯
17    GEO Accession:GSM3427232 t32lps3 RNA seq             ⋯
18    GEO Accession:GSM3427231 t32lps2 RNA seq             ⋯
19    GEO Accession:GSM3427230 t32lps1 RNA seq             ⋯
20    GEO Accession:GSM3427229 t32ct10 RNA seq             ⋯
21    GEO Accession:GSM3427228 t32ct8 RNA seq              ⋯
22    GEO Accession:GSM3427227 t32ct6 RNA seq              ⋯
23    GEO Accession:GSM3427226 t32ct3 RNA seq              ⋯
24    GEO Accession:GSM3427225 t32ct2 RNA seq              ⋯
25    GEO Accession:GSM3427224 t28lps8 RNA seq             ⋯
26    GEO Accession:GSM3427223 t28lps4 RNA seq             ⋯
27    GEO Accession:GSM3427222 t28lps3 RNA seq             ⋯
28    GEO Accession:GSM3427221 t28lps2 RNA seq             ⋯
29    GEO Accession:GSM3427220 t28lps1 RNA seq             ⋯
30    GEO Accession:GSM3427219 t28ct7 RNA seq              ⋯
⋮     ⋮                        ⋮                           ⋱
77300 NA                       1Cell  wildtype  replicate4 ⋯
77301 NA                       1Cell  wildtype  replicate3 ⋯
77302 NA                       1Cell  wildtype  replicate2 ⋯
77303 NA                       1Cell  wildtype  replicate1 ⋯
77304 NA                       NA                          ⋯
77305 NA                       NA                          ⋯
77306 NA                       NA                          ⋯
77307 NA                       NA                          ⋯
77308 NA                       NA                          ⋯
77309 NA                       NA                          ⋯
77310 NA                       NA                          ⋯
77311 NA                       NA                          ⋯
77312 NA                       NA                          ⋯
77313 NA                       NA                          ⋯
77314 NA                       NA                          ⋯
77315 NA                       NA                          ⋯
77316 NA                       NA                          ⋯
77317 NA                       NA                          ⋯
77318 NA                       NA                          ⋯
77319 NA                       NA                          ⋯
77320 NA                       NA                          ⋯
77321 NA                       NA                          ⋯
77322 NA                       NA                          ⋯
77323 NA                       NA                          ⋯
77324 NA                       NA                          ⋯
77325 NA                       NA                          ⋯
77326 NA                       NA                          ⋯
77327 NA                       NA                          ⋯
77328 NA                       NA                          ⋯
77329 NA                       NA                          ⋯
      runexpsample_devstage_coarsecurated_alsostudy
1     Adult,Embryo
2     Adult
3     Adult
4     Adult
5     Adult
6     Adult
7     Adult
8     Adult
9     Adult
10    Adult
11    Adult
12    Adult
13    Adult
14    Adult
15    Adult
16    Adult
17    Adult
18    Adult
19    Adult
20    Adult
21    Adult
22    Adult
23    Adult
24    Adult
25    Adult
26    Adult
27    Adult
28    Adult
29    Adult
30    Adult
⋮     ⋮
77300 Embryo
77301 Embryo
77302 Embryo
77303 Embryo
77304 Embryo
77305 Embryo
77306 Embryo
77307 Embryo
77308 Embryo
77309 Embryo
77310 Embryo
77311 Embryo
77312 Embryo
77313 Embryo
77314 Embryo
77315 Embryo
77316 Embryo
77317 Embryo
77318 Embryo
77319 Embryo
77320 Embryo
77321 Embryo
77322 Embryo
77323 Embryo
77324 Embryo
77325 Embryo
77326 Embryo
77327 Embryo
77328 Embryo
77329 Embryo
      runexpsample_devstage_curated_first2
1     Multi-stage
2     Adult
3     Adult
4     Adult
5     Adult
6     Adult
7     Adult
8     Adult
9     Adult
10    Adult
11    Adult
12    Adult
13    Adult
14    Adult
15    Adult
16    Adult
17    Adult
18    Adult
19    Adult
20    Adult
21    Adult
22    Adult
23    Adult
24    Adult
25    Adult
26    Adult
27    Adult
28    Adult
29    Adult
30    Adult
⋮     ⋮
77300 Zygote
77301 Zygote
77302 Zygote
77303 Zygote
77304 Zygote
77305 Zygote
77306 Zygote
77307 Zygote
77308 Zygote
77309 Zygote
77310 Zygote
77311 Zygote
77312 Zygote
77313 Zygote
77314 Zygote
77315 Zygote
77316 Zygote
77317 Zygote
77318 Zygote
77319 Zygote
77320 Zygote
77321 Zygote
77322 Zygote
77323 Zygote
77324 Zygote
77325 Zygote
77326 Zygote
77327 Zygote
77328 Zygote
77329 Zygote
      runexpsample_devstage_curated_firstandsecond2
1     Multi-stage
2     Adult
3     Adult
4     Adult
5     Adult
6     Adult
7     Adult
8     Adult
9     Adult
10    Adult
11    Adult
12    Adult
13    Adult
14    Adult
15    Adult
16    Adult
17    Adult
18    Adult
19    Adult
20    Adult
21    Adult
22    Adult
23    Adult
24    Adult
25    Adult
26    Adult
27    Adult
28    Adult
29    Adult
30    Adult
⋮     ⋮
77300 Zygote

In [50]:
metadata_curationstep10 <- metadata_curationstep9

In [51]:
############ now somewhat similar strategy for tissue
## run the classify_tissue2025first function for the 6 _tissue columns separately
## then the classify_tissue2025 'regular' function for the other 20
## then coarse tissue function
## lastly for 3 study columns run coarse function


metadata_curationstep10$sample.attributes_tissue_curated <- sapply(metadata_curationstep10$sample.attributes_tissue, classify_tissue2025first)
metadata_curationstep10$sample.title_tissue_curated <- sapply(metadata_curationstep10$sample.title_tissue, classify_tissue2025first)

metadata_curationstep10$experiment.attributes_tissue_curated <- sapply(metadata_curationstep10$experiment.attributes_tissue, classify_tissue2025first)
metadata_curationstep10$experiment.title_tissue_curated <- sapply(metadata_curationstep10$experiment.title_tissue, classify_tissue2025first)

metadata_curationstep10$GEOsample.title_tissue_curated <- sapply(metadata_curationstep10$GEOsample.title_tissue, classify_tissue2025first)
metadata_curationstep10$GEOsample.characteristics_tissue_curated <- sapply(metadata_curationstep10$GEOsample.characteristics_tissue, classify_tissue2025first)

In [52]:
## for first pass unite & clean


metadata_curationstep10c <- metadata_curationstep10 %>% unite("runexpsample_tissue_curated_first0", ends_with("_curated"), sep = ",", remove = TRUE, na.rm = TRUE)
metadata_curationstep10c <- metadata_curationstep10c %>% arrange(runexpsample_tissue_curated_first0)

# Apply the cleaning function to the column
metadata_curationstep11 <- metadata_curationstep10c %>% mutate(runexpsample_tissue_curated_first = map_chr(runexpsample_tissue_curated_first0, cleanlabels1))

metadata_curationstep11 %>% group_by(runexpsample_tissue_curated_first) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 79 × 2
   runexpsample_tissue_curated_first     n
   <chr>                             <int>
 1 Undetermined                      28976
 2 Whole Organism                    11202
 3 Embryo Imprecise                   6234
 4 Brain                              6122
 5 Trunk                              3480
 6 Heart                              3091
 7 Pancreas                           2507
 8 Spinal Cord                        2221
 9 Liver                              1776
10 Eye                                1435
11 Cancer or Tumor                    1032
12 Gonad                              1021
13 Kidney                              873
14 Gut                                 833
15 Tail                                802
16 Spleen                              748
17 Fin                                 627
18 Muscle                              574
19 Blood                               547
20 Head                                475
21 Head,Swim Bladder                   420
22 Endothelium                         374
23 Skin                                333
24 Lateral Line                        200
25 Gill                                184
26 Oocyte                              150
27 Eye,Head                            101
28 Jaw                                  85
29 Kidney,Marrow                        79
30 Thymus                               79
31 Bone or Cartilage                    75
32 Adipose Tissue                       57
33 Marrow                               49
34 Gonad,Heart                          48
35 Cell Line                            41
# ℹ 44 more rows

## Second pass - all main run/experiment/sample/GEOsample columns

In [53]:
getwd()

[1] "/hpc/projects/balla_group/sra_experiments/SRA_metadata/dec2025_75k_submitteradded"

In [54]:
metadata_curationstep11o <- metadata_curationstep11
metadata_curationstep11o

      run.accession study.accession bioproject
1     SRR9735192    SRP216059       PRJNA556239
2     SRR9735191    SRP216059       PRJNA556239
3     SRR9735190    SRP216059       PRJNA556239
4     SRR9735189    SRP216059       PRJNA556239
5     SRR9735188    SRP216059       PRJNA556239
6     SRR9735187    SRP216059       PRJNA556239
7     SRR9735186    SRP216059       PRJNA556239
8     SRR9735185    SRP216059       PRJNA556239
9     SRR9735184    SRP216059       PRJNA556239
10    SRR9735183    SRP216059       PRJNA556239
11    SRR9735182    SRP216059       PRJNA556239
12    SRR9735181    SRP216059       PRJNA556239
13    SRR9735180    SRP216059       PRJNA556239
14    SRR9735179    SRP216059       PRJNA556239
15    SRR9735178    SRP216059       PRJNA556239
16    SRR9735177    SRP216059       PRJNA556239
17    SRR9735176    SRP216059       PRJNA556239
18    SRR9735175    SRP216059       PRJNA556239
19    SRR9735174    SRP216059       PRJNA556239
20    SRR9735173    SRP216059       PRJNA556239
21    SRR9735172    SRP216059       PRJNA556239
22    SRR9735171    SRP216059       PRJNA556239
23    SRR9735170    SRP216059       PRJNA556239
24    SRR9735169    SRP216059       PRJNA556239
25    SRR19548855   SRP378691       PRJNA846095
26    SRR26902472   SRP428087       PRJNA946307
27    SRR26902473   SRP428087       PRJNA946307
28    SRR26902474   SRP428087       PRJNA946307
29    SRR26902475   SRP428087       PRJNA946307
30    SRR26902476   SRP428087       PRJNA946307
⋮     ⋮             ⋮               ⋮
77300 SRR25076628   SRP446602       PRJNA989221
77301 SRR25076629   SRP446602       PRJNA989221
77302 SRR25223172   SRP448380       PRJNA993229
77303 SRR25223173   SRP448380       PRJNA993229
77304 SRR25223174   SRP448380       PRJNA993229
77305 SRR25223175   SRP448380       PRJNA993229
77306 SRR25223176   SRP448380       PRJNA993229
77307 SRR25223177   SRP448380       PRJNA993229
77308 SRR7942606    SRP162874       PRJNA493827
77309 SRR7942605    SRP162874       PRJNA493827
77310 SRR8937006    SRP162876       PRJNA493828
77311 SRR8937003    SRP162876       PRJNA493828
77312 SRR8937002    SRP162876       PRJNA493828
77313 SRR8936999    SRP162876       PRJNA493828
77314 SRR8936998    SRP162876       PRJNA493828
77315 SRR7942622    SRP162875       PRJNA493829
77316 SRR7942621    SRP162875       PRJNA493829
77317 SRR28348938   SRP495323       PRJNA1088158
77318 SRR28348939   SRP495323       PRJNA1088158
77319 SRR28348940   SRP495323       PRJNA1088158
77320 SRR4423757    SRP091576       PRJNA348537
77321 SRR4423750    SRP091576       PRJNA348537
77322 SRR4423744    SRP091576       PRJNA348537
77323 SRR23610251   SRP424410       PRJNA938397
77324 SRR23610252   SRP424410       PRJNA938397
77325 SRR23610253   SRP424410       PRJNA938397
77326 SRR23610254   SRP424410       PRJNA938397
77327 SRR23610255   SRP424410       PRJNA938397
77328 SRR23610256   SRP424410       PRJNA938397
77329 SRR23610257   SRP424410       PRJNA938397
      study.title
1     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
2     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
3     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
4     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
5     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
6     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
7     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
8     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
9     Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
10    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
11    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
12    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
13    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
14    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
15    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
16    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
17    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
18    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
19    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
20    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
21    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
22    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
23    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
24    Adipocyte serine uptake curbs ROS generation and visceral adiposity [Zebrafish]
25    Transcriptomic evolution across bilaterian tissues
26    The zebrafish heart harbors a thermogenic beige fat depot analog of human epicardial adipose tissue
27    The zebrafish heart harbors a thermogenic beige fat depot analog of human epicardial adipose tissue
28    The zebrafish heart harbors a thermogenic beige fat depot analog of human epicardial adipose tissue
29    The zebrafish heart harbors a thermogenic beige fat depot analog of human epicardial adipose tissue
30    The zebrafish heart harbors a thermogenic beige fat depot analog of human epicardial adipose tissue
⋮     ⋮
77300 Silencing of the Stat1 bcl2 axis accelerates efficient apoptosis of immature T lymphocytes with DNA damage in zebrafish mcm5 mutants
77301 Silencing of the Stat1 bcl2 axis accelerates efficient apoptosis of immature T lymphocytes with DNA damage in zebrafish mcm5 mutants
77302 Transcriptome analysis of atad3 null zebrafish embryos elucidates possible disease mechanisms
77303 Transcriptome analysis of atad3 null zebrafish embryos elucidates possible disease mechanisms
77304 Transcriptome analysis of atad3 null zebrafish embryos elucidates possible disease mechanisms
77305 Transcriptome analysis of atad3 null zebrafish embryos elucidates possible disease mechanisms
77306 Transcriptome analysis of atad3 null zebrafish embryos elucidates possible disease mechanisms
77307 Transcriptome analysis of atad3 null zebrafish embryos elucidates possible disease mechanisms
77308 Transcriptomics analysis of gene expression in wide type  ybx1 MO  pabpc1a MO zebrafish embryo sample.
77309 Transcriptomics analysis of gene expression in wide type  ybx1 MO  pabpc1a MO zebrafish embryo sample.
77310 Ybx1 binding sites and Ybx1 binding m5C sites in zebrafish embryo sample.
77311 Ybx1 binding sites and Ybx1 binding m5C sites in zebrafish embryo sample.
77312 Ybx1 binding sites and Ybx1 binding m5C sites in zebrafish embryo sample.
77313 Ybx1 binding sites and Ybx1 binding m5C sites in zebrafish embryo sample.
77314 Ybx1 binding sites and Ybx1 binding m5C sites in zebrafish embryo sample.
77315 m5C profiles in zebrafish embryo sample.
77316 m5C profiles in zebrafish embryo sample.
77317 Protein profiling of zebrafish embryos unmasks regulatory layers during early embryogenesis.
77318 Protein profiling of zebrafish embryos unmasks regulatory layers during early embryogenesis.
77319 Protein profiling of zebrafish embryos unmasks regulatory layers during early embryogenesis.
77320 Polysome seq in zebrafish early embryonic development
77321 Polysome seq in zebrafish early embryonic development
77322 Polysome seq in zebrafish early embryonic development
77323 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77324 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77325 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77326 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77327 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77328 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
77329 The Effects of Rif1 Loss on Gene Expression During Early Zebrafish Development
      sample.accession experiment.accession earliest_date
1     SRS5140748       SRX6492152           2019-07-23
2     SRS5140747       SRX6492151           2019-07-23
3     SRS5140746       SRX6492150           2019-07-23
4     SRS5140745       SRX6492149           2019-07-23
5     SRS5140744       SRX6492148           2019-07-23
6     SRS5140743       SRX6492147           2019-07-23
7     SRS5140742       SRX6492146           2019-07-23
8     SRS5140741       SRX6492145           2019-07-23
9     SRS5140740       SRX6492144           2019-07-23
10    SRS5140739       SRX6492143           2019-07-23
11    SRS5140738       SRX6492142           2019-07-23
12    SRS5140737       SRX6492141           2019-07-23
13    SRS5140736       SRX6492140           2019-07-23
14    SRS5140735       SRX6492139           2019-07-23
15    SRS5140734       SRX6492138           2019-07-23
16    SRS5140733       SRX6492137           2019-07-23
17    SRS5140732       SRX6492136           2019-07-23
18    SRS5140731       SRX6492135           2019-07-23
19    SRS5140730       SRX6492134           2019-07-23
20    SRS5140729       SRX6492133           2019-07-23
21    SRS5140728       SRX6492132           2019-07-23
22    SRS5140727       SRX6492131           2019-07-23
23    SRS5140726       SRX6492130           2019-07-23
24    SRS5140725       SRX6492129           2019-07-23
25    SRS13301859      SRX15600909          2022-06-05
26    SRS19602930      SRX22596599          2023-11-21
27    SRS19602928      SRX22596598          2023-11-21
28    SRS19602929      SRX22596597          2023-11-21
29    SRS19602927      SRX22596596          2023-11-21
30    SRS19602926      SRX22596595          2023-11-21
⋮     ⋮                ⋮                    ⋮
77300 SRS18107952      SRX20830391          2023-06-29
77301 SRS18107953      SRX20830390          2023-06-29
77302 SRS18242557      SRX20969758          2023-07-10
77303 SRS18242558      SRX20969757          2023-07-10
77304 SRS18242556      SRX20969756          2023-07-10
77305 SRS18242554      SRX20969755          2023-07-10
77306 SRS18242555      SRX20969754          2023-07-10
77307 SRS18242553      SRX20969753          2023-07-10
77308 SRS3857410       SRX4776871           2018-09-28
77309 SRS3857409       SRX4776870           2018-09-28
77310 SRS4655939       SRX5717519           2019-04-22
77311 SRS4655936       SRX5717516           2019-04-22
77312 SRS4655935       SRX5717515           2019-04-22
77313 SRS4655932       SRX5717512           2019-04-22
77314 SRS4655931       SRX5717511           2019-04-22
77315 SRS3857428       SRX4776887           2018-09-28
77316 SRS3857426       SRX4776886           2018-09-28
77317 SRS20755379      SRX23954958          2024-03-14
77318 SRS20755378      SRX23954957          2024-03-14
77319 SRS20755377      SRX23954956          2024-03-14
77320 SRS1746324       SRX2245918           2016-10-14
77321 SRS1746318       SRX2245912           2016-10-14
77322 SRS1746312       SRX2245906           2016-10-14
77323 SRS16885249      SRX19495180          2023-02-24
77324 SRS16885248      SRX19495179          2023-02-24
77325 SRS16885247      SRX19495178          2023-02-24
77326 SRS16885246      SRX19495177          2023-02-24
77327 SRS16885245      SRX19495176          2023-02-24
77328 SRS16885244      SRX19495175          2023-02-24
77329 SRS16885243      SRX19495174          2023-02-24
      experiment.title
1     GSM3964281: Adipose KO A13; Danio rerio; RNA Seq
2     GSM3964280: Adipose KO A12; Danio rerio; RNA Seq
3     GSM3964279: Adipose KO A11; Danio rerio; RNA Seq
4     GSM3964278: Adipose KO A10; Danio rerio; RNA Seq
5     GSM3964277: Adipose KO A9; Danio rerio; RNA Seq
6     GSM3964276: Adipose KO A8; Danio rerio; RNA Seq
7     GSM3964275: Adipose KO A7; Danio rerio; RNA Seq
8     GSM3964274: Adipose KO A6; Danio rerio; RNA Seq
9     GSM3964273: Adipose KO A5; Danio rerio; RNA Seq
10    GSM3964272: Adipose KO A4; Danio rerio; RNA Seq
11    GSM3964271: Adipose KO A3; Danio rerio; RNA Seq
12    GSM3964270: Adipose KO A2; Danio rerio; RNA Seq
13    GSM3964269: Adipose KO A1; Danio rerio; RNA Seq
14    GSM3964268: Adipose WT A11; Danio rerio; RNA Seq
15    GSM3964267: Adipose WT A10; Danio rerio; RNA Seq
16    GSM3964266: Adipose WT A9; Danio rerio; RNA Seq
17    GSM3964265: Adipose WT A8; Danio rerio; RNA Seq
18    GSM3964264: Adipose WT A7; Danio rerio; RNA Seq
19    GSM3964263: Adipose WT A6; Danio rerio; RNA Seq
20    GSM3964262: Adipose WT A5; Danio rerio; RNA Seq
21    GSM3964261: Adipose WT A4; Danio rerio; RNA Seq
22    GSM3964260: Adipose WT A3; Danio rerio; RNA Seq
23    GSM3964259: Adipose WT A2; Danio rerio; RNA Seq
24    GSM3964258: Adipose WT A1; Danio rerio; RNA Seq
25    GSM6213744: RNA seq of adult Danio rerio adipose tissue [Dre Adipose a]; Danio rerio; RNA Seq
26    GSM7912825: cold eAT  epicardial fat 6; Danio rerio; RNA Seq
27    GSM7912824: cold eAT  epicardial fat 5; Danio rerio; RNA Seq
28    GSM7912823: cold eAT  epicardial fat 4; Danio rerio; RNA Seq
29    GSM7912822: control eAT  epicardial fat 3; Danio rerio; RNA Seq
30    GSM7912821: control eAT  epicardial fat 2; Danio rerio; RNA Seq
⋮     ⋮
77300 GSM7519453: Ctr rep2; Danio rerio; RNA Seq
77301 GSM7519452: Ctr rep1; Danio rerio; RNA Seq
77302 GSM7591512: wild type embryos pool of 5 3; Danio rerio; RNA Seq
77303 GSM7591511: wild type embryos pool of 5 2; Danio rerio; RNA Seq
77304 GSM7591510: wild type embryos pool of 5 1; Danio rerio; RNA Seq
77305 GSM7591508: mutant embryos pool of 5 3; Danio rerio; RNA Seq
77306 GSM7591507: mutant embryos pool of 5 2; Danio rerio; RNA Seq
77307 GSM7591506: mutant embryos pool of 5 1; Danio rerio; RNA Seq
77308 GSM3406870: WT 0hpf rep2; Danio rerio; RNA Seq
77309 GSM3406869: WT 0hpf rep1; Danio rerio; RNA Seq
77310 GSM3732426: RIP BS 0hpf; Danio rerio; OTHER
77311 GSM3732423: RIP INPUT 0hpf rep2; Danio rerio; RIP Seq
77312 GSM3732422: RIP INPUT 0hpf rep1; Danio rerio; RIP Seq
77313 GSM3732419: RIP 0hpf rep2; Danio rerio; RIP Seq
77314 GSM3732418: RIP 0hpf rep1; Danio rerio; RIP Seq
77315 GSM3406888: WT 0hpf m5C rep2; Danio rerio; OTHER
77316 GSM3406887: WT 0hpf m5C rep1; Danio rerio; OTHER
77317 GSM8147855: Zebrafish Embryo  0hpf  rep3; Danio rerio; RNA Seq
77318 GSM8147854: Zebrafish Embryo  0hpf  rep2; Danio rerio; RNA Seq
77319 GSM8147853: Zebrafish Embryo  0hpf  rep1; Danio rerio; RNA Seq
77320 GSM2345440: 1 cell  unfractionated; Danio rerio; RNA Seq
77321 GSM2345434: 1 cell  polysome unbound; Danio rerio; RNA Seq
77322 GSM2345428: 1 cell  polysome bound; Danio rerio; RNA Seq
77323 GSM7061827: 1Cell  omf201  replicate3; Danio rerio; RNA Seq
77324 GSM7061826: 1Cell  omf201  replicate2; Danio rerio; RNA Seq
77325 GSM7061825: 1Cell  omf201  replicate1; Danio rerio; RNA Seq
77326 GSM7061824: 1Cell  wildtype  replicate4; Danio rerio; RNA Seq
77327 GSM7061823: 1Cell  wildtype  replicate3; Danio rerio; RNA Seq
77328 GSM7061822: 1Cell  wildtype  replicate2; Danio rerio; RNA Seq
77329 GSM7061821: 1Cell  wildtype  replicate1; Danio rerio; RNA Seq
      experiment.attributes
1     GEO Accession:GSM3964281
2     GEO Accession:GSM3964280
3     GEO Accession:GSM3964279
4     GEO Accession:GSM3964278
5     GEO Accession:GSM3964277
6     GEO Accession:GSM3964276
7     GEO Accession:GSM3964275
8     GEO Accession:GSM3964274
9     GEO Accession:GSM3964273
10    GEO Accession:GSM3964272
11    GEO Accession:GSM3964271
12    GEO Accession:GSM3964270
13    GEO Accession:GSM3964269
14    GEO Accession:GSM3964268
15    GEO Accession:GSM3964267
16    GEO Accession:GSM3964266
17    GEO Accession:GSM3964265
18    GEO Accession:GSM3964264
19    GEO Accession:GSM3964263
20    GEO Accession:GSM3964262
21    GEO Accession:GSM3964261
22    GEO Accession:GSM3964260
23    GEO Accession:GSM3964259
24    GEO Accession:GSM3964258
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
⋮     ⋮
77300 NA
77301 NA
77302 NA
77303 NA
77304 NA
77305 NA
77306 NA
77307 NA
77308 GEO Accession:GSM3406870
77309 GEO Accession:GSM3406869
77310 GEO Accession:GSM3732426
77311 GEO Accession:GSM3732423
77312 GEO Accession:GSM3732422
77313 GEO Accession:GSM3732419
77314 GEO Accession:GSM3732418
77315 GEO Accession:GSM3406888
77316 GEO Accession:GSM3406887
77317 NA
77318 NA
77319 NA
77320 GEO Accession:GSM2345440
77321 GEO Accession:GSM2345434
77322 GEO Accession:GSM2345428
77323 NA
77324 NA
77325 NA
77326 NA
77327 NA
77328 NA
77329 NA
      sample.title                                                ⋯
1     Adipose KO A13                                              ⋯
2     Adipose KO A12                                              ⋯
3     Adipose KO A11                                              ⋯
4     Adipose KO A10                                              ⋯
5     Adipose KO A9                                               ⋯
6     Adipose KO A8                                               ⋯
7     Adipose KO A7                                               ⋯
8     Adipose KO A6                                               ⋯
9     Adipose KO A5                                               ⋯
10    Adipose KO A4                                               ⋯
11    Adipose KO A3                                               ⋯
12    Adipose KO A2                                               ⋯
13    Adipose KO A1                                               ⋯
14    Adipose WT A11                                              ⋯
15    Adipose WT A10                                              ⋯
16    Adipose WT A9                                               ⋯
17    Adipose WT A8                                               ⋯
18    Adipose WT A7                                               ⋯
19    Adipose WT A6                                               ⋯
20    Adipose WT A5                                               ⋯
21    Adipose WT A4                                               ⋯
22    Adipose WT A3                                               ⋯
23    Adipose WT A2                                               ⋯
24    Adipose WT A1                                               ⋯
25    RNA seq of adult Danio rerio adipose tissue [Dre Adipose a] ⋯
26    cold eAT  epicardial fat 6                                  ⋯
27    cold eAT  epicardial fat 5                                  ⋯
28    cold eAT  epicardial fat 4                                  ⋯
29    control eAT  epicardial fat 3                               ⋯
30    control eAT  epicardial fat 2                               ⋯
⋮     ⋮                                                           ⋱
77300 Ctr rep2                                                    ⋯
77301 Ctr rep1                                                    ⋯
77302 wild type embryos pool of 5 3                               ⋯
77303 wild type embryos pool of 5 2                               ⋯
77304 wild type embryos pool of 5 1                               ⋯
77305 mutant embryos pool of 5 3                                  ⋯
77306 mutant embryos pool of 5 2                                  ⋯
77307 mutant embryos pool of 5 1                                  ⋯
77308 WT 0hpf rep2                                                ⋯
77309 WT 0hpf rep1                                                ⋯
77310 RIP BS 0hpf                                                 ⋯
77311 RIP INPUT 0hpf rep2                                         ⋯
77312 RIP INPUT 0hpf rep1                                         ⋯
77313 RIP 0hpf rep2                                               ⋯
77314 RIP 0hpf rep1                                               ⋯
77315 WT 0hpf m5C rep2                                            ⋯

In [55]:
## then all 20 for main tissue curation...classify_tissue2025
#metadata_curationstep11 <- metadata_curationstep11o

## changing column end to _tcurated

metadata_curationstep11$experiment.title_tcurated <- sapply(metadata_curationstep11$experiment.title, classify_tissue2025)
metadata_curationstep11$experiment.attributes_tcurated <- sapply(metadata_curationstep11$experiment.attributes, classify_tissue2025)
metadata_curationstep11$sample.title_tcurated <- sapply(metadata_curationstep11$sample.title, classify_tissue2025)
metadata_curationstep11$sample.attributes_tcurated <- sapply(metadata_curationstep11$sample.attributes, classify_tissue2025)
metadata_curationstep11$GEOsample.title_tcurated <- sapply(metadata_curationstep11$GEOsample.title, classify_tissue2025)
metadata_curationstep11$GEOsample.characteristics_tcurated <- sapply(metadata_curationstep11$GEOsample.characteristics, classify_tissue2025)

metadata_curationstep11$run.title_tcurated <- sapply(metadata_curationstep11$run.title, classify_tissue2025)
metadata_curationstep11$run.alias_tcurated <- sapply(metadata_curationstep11$run.alias, classify_tissue2025)
metadata_curationstep11$run.attributes_tcurated <- sapply(metadata_curationstep11$run.attributes, classify_tissue2025)
metadata_curationstep11$experiment.alias_tcurated <- sapply(metadata_curationstep11$experiment.alias, classify_tissue2025)
metadata_curationstep11$experiment.library_name_tcurated <- sapply(metadata_curationstep11$experiment.library_name, classify_tissue2025)
metadata_curationstep11$experiment.design_description_tcurated <- sapply(metadata_curationstep11$experiment.design_description, classify_tissue2025)
metadata_curationstep11$experiment.library_construction_protocol_tcurated <- sapply(metadata_curationstep11$experiment.library_construction_protocol, classify_tissue2025)

metadata_curationstep11$sample.description_tcurated <- sapply(metadata_curationstep11$sample.description, classify_tissue2025)
metadata_curationstep11$sample.alias_tcurated <- sapply(metadata_curationstep11$sample.alias, classify_tissue2025)
metadata_curationstep11$GEOsample.dataprocessing_tcurated <- sapply(metadata_curationstep11$GEOsample.dataprocessing, classify_tissue2025)
metadata_curationstep11$GEOsample.source_tcurated <- sapply(metadata_curationstep11$GEOsample.source, classify_tissue2025)
metadata_curationstep11$GEOsample.treatmentprotocol_tcurated <- sapply(metadata_curationstep11$GEOsample.treatmentprotocol, classify_tissue2025)
metadata_curationstep11$GEOsample.extractprotocol_tcurated <- sapply(metadata_curationstep11$GEOsample.extractprotocol, classify_tissue2025)
metadata_curationstep11$GEOsample.growthprotocol_tcurated <- sapply(metadata_curationstep11$GEOsample.growthprotocol, classify_tissue2025)

In [56]:
## unite and clean

## another round of uniting

metadata_curationstep11c <- metadata_curationstep11 %>% unite("runexpsample_tissue_curated_second0", ends_with("_tcurated"), sep = ",", remove = TRUE, na.rm = TRUE)
#metadata_curationstep4c <- metadata_curationstep4c %>% arrange(runexpsample_tissue_curated_second0)

# Apply the cleaning function to the column
metadata_curationstep12 <- metadata_curationstep11c %>% mutate(runexpsample_tissue_curated_second = map_chr(runexpsample_tissue_curated_second0, cleanlabels1))

## now coalesce only after creating NAs from curated_first when Unclassified
metadata_curationstep12 <- metadata_curationstep12 %>% mutate(runexpsample_tissue_curated_first = na_if(runexpsample_tissue_curated_first, "Undetermined"))
metadata_curationstep12 <- metadata_curationstep12 %>% mutate(runexpsample_tissue_curated_firstandsecond = coalesce(runexpsample_tissue_curated_first,runexpsample_tissue_curated_second))


metadata_curationstep12 <- metadata_curationstep12 %>% relocate(runexpsample_tissue_curated_first0, .after = last_col())
metadata_curationstep12 <- metadata_curationstep12 %>% relocate(runexpsample_tissue_curated_second0, .after = last_col())

## add undetermined back in 
metadata_curationstep12$runexpsample_tissue_curated_first <- metadata_curationstep12$runexpsample_tissue_curated_first %>% replace_na("Undetermined")

metadata_curationstep12 %>% group_by(runexpsample_tissue_curated_firstandsecond) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=35)

# A tibble: 165 × 2
   runexpsample_tissue_curated_firstandsecond               n
   <chr>                                                <int>
 1 Whole Organism                                       24803
 2 Embryo Imprecise                                      8312
 3 Brain                                                 6454
 4 Undetermined                                          4325
 5 Trunk                                                 3555
 6 Heart                                                 3173
 7 Pancreas                                              2522
 8 Spinal Cord                                           2275
 9 Blood,Fin,Gonad,Kidney                                2015
10 Liver                                                 1826
11 Eye                                                   1527
12 Fin                                                   1280
13 Gonad                                                 1126
14 Cancer or Tumor                                       1116
15 Blood,Gill,Gut,Kidney,Lymphatic System,Spleen,Thymus  1056
16 Kidney                                                1056
17 Spleen                                                 948
18 Gut                                                    899
19 Head                                                   838
20 Tail                                                   804
21 Heart,Kidney                                           672
22 Muscle                                                 605
23 Embryo Imprecise,Whole Organism                        575
24 Blood                                                  574
25 Head,Swim Bladder                                      420
26 Skin                                                   398
27 Cell Line                                              387
28 Endothelium                                            374
29 Embryo Imprecise,Fin,Lymphatic System,Thymus           276
30 Oocyte                                                 276
31 Gill                                                   261
32 Lateral Line                                           200
33 Cell Line,Embryo Imprecise,Whole Organism              170
34 Bone or Cartilage                                      119
35 Eye,Head                                               101
# ℹ 130 more rows

### Code to convert to multi-tissue also embryo imprecise and also whole organism taking priority (and not multi-tissue)

In [57]:
metadata_curationstep12b <- metadata_curationstep12

## first two replace firstandsecond column!!
## let's first replicate firstandsecond
metadata_curationstep12b$runexpsample_tissue_curated_firstandsecond2 <- metadata_curationstep12b$runexpsample_tissue_curated_firstandsecond

In [58]:
metadata_curationstep12b <- metadata_curationstep12b %>%
  mutate(runexpsample_tissue_curated_firstandsecond2 = case_when(
    grepl("Embryo Imprecise", runexpsample_tissue_curated_firstandsecond) & grepl("Whole Organism", runexpsample_tissue_curated_firstandsecond) ~ "Whole Organism",
    grepl("Embryo Imprecise", runexpsample_tissue_curated_firstandsecond) ~ "Embryo Imprecise",
    grepl("Whole Organism", runexpsample_tissue_curated_firstandsecond) ~ "Whole Organism",
    TRUE ~ runexpsample_tissue_curated_firstandsecond
  ))

## now this command will replace all other firstandsecond2
metadata_curationstep12b <- metadata_curationstep12b %>%
  mutate(runexpsample_tissue_curated_firstandsecond2 = if_else(grepl(",", runexpsample_tissue_curated_firstandsecond2), "Multi-tissue", runexpsample_tissue_curated_firstandsecond2))

## now summarize
metadata_curationstep12b %>% group_by(runexpsample_tissue_curated_firstandsecond2) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=45)

# A tibble: 41 × 2
   runexpsample_tissue_curated_firstandsecond2     n
   <chr>                                       <int>
 1 Whole Organism                              25682
 2 Embryo Imprecise                             8973
 3 Brain                                        6454
 4 Multi-tissue                                 5171
 5 Undetermined                                 4325
 6 Trunk                                        3555
 7 Heart                                        3173
 8 Pancreas                                     2522
 9 Spinal Cord                                  2275
10 Liver                                        1826
11 Eye                                          1527
12 Fin                                          1280
13 Gonad                                        1126
14 Cancer or Tumor                              1116
15 Kidney                                       1056
16 Spleen                                        948
17 Gut                                           899
18 Head                                          838
19 Tail                                          804
20 Muscle                                        605
21 Blood                                         574
22 Skin                                          398
23 Cell Line                                     387
24 Endothelium                                   374
25 Oocyte                                        276
26 Gill                                          261
27 Lateral Line                                  200
28 Bone or Cartilage                             119
29 Jaw                                            85
30 Thymus                                         79
31 BCR TCR repertoire                             65
32 Lymphatic System                               64
33 Adipose Tissue                                 57
34 Marrow                                         49
35 Pineal Gland                                   40
36 Pituitary Gland                                40
37 Pharyngeal Arch                                34
38 Scale                                          32
39 Ear                                            18
40 Swim Bladder                                   12
41 Thyroid                                        10

In [59]:

## repeat for runexpsample_tissue_curated_first
metadata_curationstep12c <- metadata_curationstep12b
metadata_curationstep12c$runexpsample_tissue_curated_first2 <- metadata_curationstep12c$runexpsample_tissue_curated_first

metadata_curationstep12c <- metadata_curationstep12c %>%
  mutate(runexpsample_tissue_curated_first2 = case_when(
    grepl("Embryo Imprecise", runexpsample_tissue_curated_first) & grepl("Whole Organism", runexpsample_tissue_curated_first) ~ "Whole Organism",
    grepl("Embryo Imprecise", runexpsample_tissue_curated_first) ~ "Embryo Imprecise",
    grepl("Whole Organism", runexpsample_tissue_curated_first) ~ "Whole Organism",
    TRUE ~ runexpsample_tissue_curated_first
  ))

## now this command will replace all other first2
metadata_curationstep12c <- metadata_curationstep12c %>%
  mutate(runexpsample_tissue_curated_first2 = if_else(grepl(",", runexpsample_tissue_curated_first2), "Multi-tissue", runexpsample_tissue_curated_first2))

## now summarize
metadata_curationstep12c %>% group_by(runexpsample_tissue_curated_first2) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=45)

# A tibble: 40 × 2
   runexpsample_tissue_curated_first2     n
   <chr>                              <int>
 1 Undetermined                       28976
 2 Whole Organism                     11202
 3 Embryo Imprecise                    6240
 4 Brain                               6122
 5 Trunk                               3480
 6 Heart                               3091
 7 Pancreas                            2507
 8 Spinal Cord                         2221
 9 Liver                               1776
10 Eye                                 1435
11 Cancer or Tumor                     1032
12 Gonad                               1021
13 Multi-tissue                         967
14 Kidney                               873
15 Gut                                  833
16 Tail                                 802
17 Spleen                               748
18 Fin                                  627
19 Muscle                               574
20 Blood                                547
21 Head                                 475
22 Endothelium                          374
23 Skin                                 333
24 Lateral Line                         200
25 Gill                                 184
26 Oocyte                               150
27 Jaw                                   85
28 Thymus                                79
29 Bone or Cartilage                     75
30 Adipose Tissue                        57
31 Marrow                                49
32 Cell Line                             41
33 Pharyngeal Arch                       34
34 Pituitary Gland                       34
35 Lymphatic System                      32
36 Scale                                 20
37 Thyroid                               10
38 Swim Bladder                           9
39 Pineal Gland                           8
40 Ear                                    6

## Coarse functions - this time just on curated _curated_firstandsecond

But with different tissue coarse columns to check for embryo imprecise

In [60]:
## coarse function 
## devstage_full in this case is runexpsample_devstage_coarsecurated2
metadata_curationstep13 <- metadata_curationstep12c
#metadata_curationstep13 <- metadata_curationstep12b
metadata_curationstep13$runexpsample_tissue_coarsecurated <- mapply(classify_tissue_coarse2025, metadata_curationstep13$runexpsample_tissue_curated_firstandsecond2, metadata_curationstep13$runexpsample_devstage_coarsecurated2)

In [61]:
### then repeat with study included runexpsample_devstage_coarsecurated_alsostudy2

metadata_curationstep13$runexpsample_tissue_coarsecurated_alsostudy <- mapply(classify_tissue_coarse2025, metadata_curationstep13$runexpsample_tissue_curated_firstandsecond2, metadata_curationstep13$runexpsample_devstage_coarsecurated_alsostudy2)

In [62]:

## final summaries - might not need to remove commas now!


metadata_curationstep13 %>% group_by(runexpsample_tissue_coarsecurated) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=45)

metadata_curationstep13 %>% group_by(runexpsample_tissue_coarsecurated_alsostudy) %>% summarize(n = n()) %>% arrange(desc(n)) %>% print(n=45)

# A tibble: 21 × 2
   runexpsample_tissue_coarsecurated     n
   <chr>                             <int>
 1 All anatomical structures         34655
 2 Nervous System                     9567
 3 Multi-system                       6009
 4 Surface Structure                  5350
 5 Cardiovascular System              3611
 6 Endocrine System                   2612
 7 Embryo Imprecise                   2455
 8 Undetermined                       1870
 9 Liver and Biliary System           1826
10 Sensory System                     1745
11 Hematopoietic System               1666
12 Reproductive System                1402
13 Cancer or Tumor                    1116
14 Renal System                       1105
15 Digestive System                    899
16 Muscular System                     605
17 Cell Line                           387
18 Respiratory System                  261
19 Skeletal Element                    119
20 Adipose Tissue                       57
21 Swim Bladder                         12
# A tibble: 21 × 2
   runexpsample_tissue_coarsecurated_alsostudy     n
   <chr>                                       <int>
 1 All anatomical structures                   34655
 2 Nervous System                               9567
 3 Multi-system                                 6009
 4 Surface Structure                            5350
 5 Cardiovascular System                        3611
 6 Endocrine System                             2612
 7 Embryo Imprecise                             2580
 8 Liver and Biliary System                     1826
 9 Sensory System                               1745
10 Undetermined                                 1745
11 Hematopoietic System                         1666
12 Reproductive System                          1402
13 Cancer or Tumor                              1116
14 Renal System                                 1105
15 Digestive System                              899
16 Muscular System                               605
17 Cell Line                                     387
18 Respiratory System                            261
19 Skeletal Element                              119
20 Adipose Tissue                                 57
21 Swim Bladder                                   12

In [63]:
colnames(metadata_curationstep13)

 [1] "run.accession"
 [2] "study.accession"
 [3] "bioproject"
 [4] "study.title"
 [5] "sample.accession"
 [6] "experiment.accession"
 [7] "earliest_date"
 [8] "experiment.title"
 [9] "experiment.attributes"
[10] "sample.title"
[11] "sample.attributes"
[12] "GEOsample.title"
[13] "GEOsample.characteristics"
[14] "experiment.title_devstage"
[15] "experiment.title_age"
[16] "experiment.title_tissue"
[17] "experiment.attributes_devstage"
[18] "experiment.attributes_age"
[19] "experiment.attributes_tissue"
[20] "sample.title_devstage"
[21] "sample.title_age"
[22] "sample.title_tissue"
[23] "sample.attributes_devstage"
[24] "sample.attributes_age"
[25] "sample.attributes_tissue"
[26] "GEOsample.title_devstage"
[27] "GEOsample.title_age"
[28] "GEOsample.title_tissue"
[29] "GEOsample.characteristics_devstage"
[30] "GEOsample.characteristics_age"
[31] "GEOsample.characteristics_tissue"
[32] "run.title"
[33] "run.attributes"
[34] "experiment.library_name"
[35] "experiment.design_description"
[36] "experiment.library_construction_protocol"
[37] "sample.description"
[38] "GEOsample.dataprocessing"
[39] "GEOsample.source"
[40] "GEOsample.treatmentprotocol"
[41] "GEOsample.extractprotocol"
[42] "GEOsample.growthprotocol"
[43] "runexpsample_devstage_curated_first"
[44] "runexpsample_devstage_curated_firstandsecond"
[45] "runexpsample_devstage_coarsecurated"
[46] "runexpsample_devstage_curated_second"
[47] "runexpsample_devstage_curated_first0"
[48] "runexpsample_devstage_curated_second0"
[49] "runexpsample_devstage_coarsecurated0"
[50] "runexpsample_devstage_coarselastcurated0"
[51] "runexpsample_devstage_coarselastcurated"
[52] "runexpsample_devstage_coarsecurated_alsostudy"
[53] "runexpsample_devstage_curated_first2"
[54] "runexpsample_devstage_curated_firstandsecond2"
[55] "runexpsample_devstage_coarsecurated2"
[56] "runexpsample_devstage_coarsecurated_alsostudy2"
[57] "study.abstract"
[58] "study.attributes"
[59] "run.alias"
[60] "experiment.alias"
[61] "sample.alias"
[62] "runexpsample_tissue_curated_first"
[63] "runexpsample_tissue_curated_second"
[64] "runexpsample_tissue_curated_firstandsecond"
[65] "runexpsample_tissue_curated_first0"
[66] "runexpsample_tissue_curated_second0"
[67] "runexpsample_tissue_curated_firstandsecond2"
[68] "runexpsample_tissue_curated_first2"
[69] "runexpsample_tissue_coarsecurated"
[70] "runexpsample_tissue_coarsecurated_alsostudy"

In [64]:
## rename a bunch of columns, save fullcolumns version, the remove many for final curation version
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns = runexpsample_devstage_curated_first)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns = runexpsample_devstage_curated_firstandsecond)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_coarse = runexpsample_devstage_coarsecurated)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_twentycolumns = runexpsample_devstage_curated_second)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0 = runexpsample_devstage_curated_first0)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_twentycolumns0 = runexpsample_devstage_curated_second0)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_coarse0 = runexpsample_devstage_coarsecurated0)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_coarselast0 = runexpsample_devstage_coarselastcurated0)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_coarselast = runexpsample_devstage_coarselastcurated)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse = runexpsample_devstage_coarsecurated_alsostudy)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns = runexpsample_devstage_curated_first2)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns = runexpsample_devstage_curated_firstandsecond2)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse = runexpsample_devstage_coarsecurated2)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse = runexpsample_devstage_coarsecurated_alsostudy2)

metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns = runexpsample_tissue_curated_first)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_twentycolumns = runexpsample_tissue_curated_second)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns = runexpsample_tissue_curated_firstandsecond)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0 = runexpsample_tissue_curated_first0)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_twentycolumns0 = runexpsample_tissue_curated_second0)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns = runexpsample_tissue_curated_firstandsecond2)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns = runexpsample_tissue_curated_first2)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse = runexpsample_tissue_coarsecurated)
metadata_curationstep13 <- metadata_curationstep13 %>% rename(tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse = runexpsample_tissue_coarsecurated_alsostudy)

In [65]:
## relocate( .after = )
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(study.abstract, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(study.attributes, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(run.alias, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(experiment.alias, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(sample.alias, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_twentycolumns0, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_coarselast0, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_coarse0, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_twentycolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_coarselast, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_coarse, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_twentycolumns0, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_twentycolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns, .after = last_col())
metadata_curationstep13 <- metadata_curationstep13 %>% relocate(tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse, .after = last_col())

## Adding technology

In [66]:
## INSTRUCTIONS FOR RUNNING Y TECHNOLOGY CURATION SCRIPT
# ## copied into //hpc/projects/balla_group/sra_experiments/SRA_metadata/dec2025_75k_submitteradded/intermediate
# ## also have to run these
# ## try loading anaconda first??
# module load anaconda
# module load data.science

# # now activate single-cell-base
# #conda activate /hpc/user_apps/data.science/conda_envs/single-cell-base
# conda activate single-cell-base

# module load ugrep
# #./metadata-annotate.py combine all_zf_metadata2_run.tsv all_zf_metadata2_sample.tsv all_zf_metadata2_experiment.tsv all_zf_metadata2_study.tsv

# ## results in new file all_metadata_combined.csv

In [67]:
## then add technology
intermediatepath <- str_c(workingpath, "/intermediate")
intermediatepathmetadata_techcuration <- str_c(intermediatepath, "/all_metadata_combined.csv")
metadata_techcuration <- read_csv(intermediatepathmetadata_techcuration)
metadata_techcuration <- metadata_techcuration %>% select(run.accession,technology)
metadata_techcuration <- metadata_techcuration %>% rename(technology_curation = technology)

metadata_curationstep13b <- left_join(metadata_curationstep13,metadata_techcuration)

Rows: 77329 Columns: 38
── Column specification ────────────────────────────────────────────────────────
Delimiter: ","
chr  (10): run.accession, run.experiment, run.pool_member, run.read_lengths,...
dbl  (27): run.total_spots, bulk, droncseq, dropseq, fluidigm, indrops, mars...
dttm  (1): run.published_date

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Joining with `by = join_by(run.accession)`

In [68]:
# ## first saving a fullcolumns version then removing ~10 columns
# write.table(metadata_curationstep13b, file = paste0("all_zf_dates_devstage_tissue_metatech_curated_withGEO_rawcolumns.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

In [69]:

## lost pubmed ids! they are in study.PMIDs
#metadata_curationstep0 <- read_tsv("all_zf_datescurated_withGEO.tsv")

## why lost? this step!
## metadata_curationstep1 <- metadata_curationstep0 %>% select(run.accession:earliest_date,experiment.title,experiment.attributes,sample.title,sample.attributes,GEOsample.title,GEOsample.characteristics,run.title,run.alias,run.attributes,experiment.alias,experiment.library_name,experiment.design_description,experiment.library_construction_protocol,sample.description,sample.alias,GEOsample.dataprocessing,GEOsample.source,GEOsample.treatmentprotocol,GEOsample.extractprotocol,GEOsample.growthprotocol,study.abstract,study.attributes)
colnames(metadata_curationstep0)
colnames(metadata_curationstep13b)

 [1] "run.accession"
 [2] "study.accession"
 [3] "bioproject"
 [4] "study.title"
 [5] "sample.accession"
 [6] "experiment.accession"
 [7] "earliest_date"
 [8] "run.title"
 [9] "run.alias"
[10] "run.attributes"
[11] "experiment.title"
[12] "experiment.alias"
[13] "experiment.library_name"
[14] "experiment.design_description"
[15] "experiment.library_construction_protocol"
[16] "experiment.attributes"
[17] "sample.description"
[18] "sample.title"
[19] "sample.alias"
[20] "sample.attributes"
[21] "sample.centername"
[22] "submission.bioprojectsource"
[23] "submission.srasource"
[24] "submission.accession"
[25] "run.filename"
[26] "run.semantic_name"
[27] "run.total_bases"
[28] "run.total_spots"
[29] "experiment.library_strategy"
[30] "experiment.library_source"
[31] "experiment.library_selection"
[32] "experiment.library_layout"
[33] "experiment.platform"
[34] "experiment.instrument_model"
[35] "experiment.spot_descriptor"
[36] "study.alias"
[37] "study.type"
[38] "study.abstract"
[39] "study.attributes"
[40] "study.PMIDs"
[41] "GEOsample.accession"
[42] "GEOsample.title"
[43] "GEOsample.dataprocessing"
[44] "GEOsample.source"
[45] "GEOsample.treatmentprotocol"
[46] "GEOsample.extractprotocol"
[47] "GEOsample.growthprotocol"
[48] "GEOsample.characteristics"
[49] "GEO_studyID"
[50] "GEO_sampleID_withrun"
[51] "run.read_lengths"
[52] "run.base_counts"
[53] "run.r1_length"
[54] "run.r2_length"
[55] "run.r3_length"
[56] "run.r4_length"
[57] "run.Acount"
[58] "run.Ccount"
[59] "run.Gcount"
[60] "run.Tcount"
[61] "run.Ncount"
[62] "run.experiment"
[63] "run.pool_member"
[64] "experiment.study_ref"
[65] "run.enafirstpublic_date"
[66] "run.enalastupdate_date"
[67] "run.lastSRAFile_date"
[68] "run.published_date"
[69] "run.SRAFile_date"
[70] "sample.enafirstpublic_date"
[71] "sample.enafirstpublic2_date"
[72] "sample.enalastupdate_date"
[73] "sample.enalastupdate2_date"
[74] "sample.insdcfirstpublic_date"
[75] "sample.insdclastupdate_date"
[76] "study.enafirstpublic_date"
[77] "study.enalastupdate_date"
[78] "GEOsample.submission_date"
[79] "GEOsample.release_date"
[80] "GEOsample.lastupdate_date"

 [1] "run.accession"
 [2] "study.accession"
 [3] "bioproject"
 [4] "study.title"
 [5] "sample.accession"
 [6] "experiment.accession"
 [7] "earliest_date"
 [8] "experiment.title"
 [9] "experiment.attributes"
[10] "sample.title"
[11] "sample.attributes"
[12] "GEOsample.title"
[13] "GEOsample.characteristics"
[14] "experiment.title_devstage"
[15] "experiment.title_age"
[16] "experiment.title_tissue"
[17] "experiment.attributes_devstage"
[18] "experiment.attributes_age"
[19] "experiment.attributes_tissue"
[20] "sample.title_devstage"
[21] "sample.title_age"
[22] "sample.title_tissue"
[23] "sample.attributes_devstage"
[24] "sample.attributes_age"
[25] "sample.attributes_tissue"
[26] "GEOsample.title_devstage"
[27] "GEOsample.title_age"
[28] "GEOsample.title_tissue"
[29] "GEOsample.characteristics_devstage"
[30] "GEOsample.characteristics_age"
[31] "GEOsample.characteristics_tissue"
[32] "run.title"
[33] "run.attributes"
[34] "experiment.library_name"
[35] "experiment.design_description"
[36] "experiment.library_construction_protocol"
[37] "sample.description"
[38] "GEOsample.dataprocessing"
[39] "GEOsample.source"
[40] "GEOsample.treatmentprotocol"
[41] "GEOsample.extractprotocol"
[42] "GEOsample.growthprotocol"
[43] "study.abstract"
[44] "study.attributes"
[45] "run.alias"
[46] "experiment.alias"
[47] "sample.alias"
[48] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
[49] "devstage_curation_runexperimentsampleGEOsample_twentycolumns0"
[50] "devstage_curation_runexperimentsampleGEOsample_coarselast0"
[51] "devstage_curation_runexperimentsampleGEOsample_coarse0"
[52] "devstage_curation_runexperimentsampleGEOsample_twentycolumns"
[53] "devstage_curation_runexperimentsampleGEOsample_coarselast"
[54] "devstage_curation_runexperimentsampleGEOsample_coarse"
[55] "devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse"
[56] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
[57] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
[58] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
[59] "devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse"
[60] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns"
[61] "devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse"
[62] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
[63] "tissue_curation_runexperimentsampleGEOsample_twentycolumns0"
[64] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
[65] "tissue_curation_runexperimentsampleGEOsample_twentycolumns"
[66] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
[67] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
[68] "tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse"
[69] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns"
[70] "tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse"
[71] "technology_curation"

In [70]:
## bring them back - instead use code just below 
# metadata_pmids <- metadata_curationstep0 %>% select(run.accession,study.PMIDs)

# metadata_curationstep13fewer2 <- left_join(metadata_curationstep13fewer,metadata_pmids)
# metadata_curationstep13fewer2 <- metadata_curationstep13fewer2 %>% relocate(study.PMIDs, .after = technology_curation)

In [71]:
# ## saving easier-to-read version with 52 columns
# #write.table(metadata_curationstep13b, file = paste0("all_zf_dates_devstage_tissue_metatech_curated_withGEO_rawcolumns.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)
# write.table(metadata_curationstep13fewer, file = paste0("all_zf_dates_devstage_tissue_metatech_curated_withGEO.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

In [72]:
# write.table(metadata_curationstep13fewer2, file = paste0("all_zf_dates_devstage_tissue_tech_curated_withGEO.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

In [73]:
## let's add many of these back, but not all, and re-order these ed_order
# 'sample.centername''submission.bioprojectsource''submission.srasource''submission.accession'
mt_toaddback <- c(
  "run.accession", "run.filename", "run.semantic_name", "run.total_bases", "run.total_spots",
  "run.read_lengths", "run.base_counts", "run.Acount", "run.Ccount", "run.Gcount", "run.Tcount", "run.Ncount",
  "run.r1_length", "run.r2_length", "run.r3_length", "run.r4_length", "run.experiment", "run.pool_member",
  "experiment.instrument_model", "experiment.library_layout", "experiment.library_selection",
  "experiment.library_source", "experiment.library_strategy", "experiment.platform", "experiment.spot_descriptor",
  "experiment.study_ref", "sample.centername", "GEOsample.accession", "GEO_studyID", "GEO_sampleID_withrun",
  "study.alias", "study.type", "study.PMIDs", "submission.bioprojectsource", "submission.srasource", "submission.accession"
)

In [74]:
metadata_toaddback <- metadata_curationstep0 %>%
  select(all_of(mt_toaddback))

In [75]:
metadata_curationstep14 <- left_join(metadata_toaddback,metadata_curationstep13b)

metadata_curationstep14 <- metadata_curationstep14 %>% rename(GEOsample.sampleID_withrun = GEO_sampleID_withrun) %>% rename(GEOsample.studyID = GEO_studyID)

Joining with `by = join_by(run.accession)`

In [76]:

## now we have 3 center/submitted columns
# sample.centername, submission.bioprojectsource, submission.srasource
# submission.bioprojectsource looks to be the best - except in the following case, when we should use submission.srasource

metadata_curationstep14 <- metadata_curationstep14 %>%
  mutate(submission.bioprojectsource = if_else(
    submission.bioprojectsource == "European Bioinformatics Institute",
    submission.srasource,
    submission.bioprojectsource
  ))

## also coalesce for handful of cases when submission.bioprojectsource is NA
metadata_curationstep14 <- metadata_curationstep14 %>% mutate(submission.bioprojectsource = coalesce(submission.bioprojectsource, submission.srasource))

## finally there are only 2 complete NAs - this is from the 2 runs without a known bioproject
## we used a dummy bioproject ID, but we can manually look it up and replace it:
#SRR065197
#SRR065196
## submission.bioprojectsource Justus-Liebig University Giessen
metadata_curationstep14 <- metadata_curationstep14 %>%
  mutate(submission.bioprojectsource = case_when(
    run.accession %in% c("SRR065196", "SRR065197") ~ "Justus-Liebig University Giessen",
    TRUE ~ submission.bioprojectsource
  ))

In [77]:
colnames(metadata_curationstep14)

  [1] "run.accession"
  [2] "run.filename"
  [3] "run.semantic_name"
  [4] "run.total_bases"
  [5] "run.total_spots"
  [6] "run.read_lengths"
  [7] "run.base_counts"
  [8] "run.Acount"
  [9] "run.Ccount"
 [10] "run.Gcount"
 [11] "run.Tcount"
 [12] "run.Ncount"
 [13] "run.r1_length"
 [14] "run.r2_length"
 [15] "run.r3_length"
 [16] "run.r4_length"
 [17] "run.experiment"
 [18] "run.pool_member"
 [19] "experiment.instrument_model"
 [20] "experiment.library_layout"
 [21] "experiment.library_selection"
 [22] "experiment.library_source"
 [23] "experiment.library_strategy"
 [24] "experiment.platform"
 [25] "experiment.spot_descriptor"
 [26] "experiment.study_ref"
 [27] "sample.centername"
 [28] "GEOsample.accession"
 [29] "GEOsample.studyID"
 [30] "GEOsample.sampleID_withrun"
 [31] "study.alias"
 [32] "study.type"
 [33] "study.PMIDs"
 [34] "submission.bioprojectsource"
 [35] "submission.srasource"
 [36] "submission.accession"
 [37] "study.accession"
 [38] "bioproject"
 [39] "study.title"
 [40] "sample.accession"
 [41] "experiment.accession"
 [42] "earliest_date"
 [43] "experiment.title"
 [44] "experiment.attributes"
 [45] "sample.title"
 [46] "sample.attributes"
 [47] "GEOsample.title"
 [48] "GEOsample.characteristics"
 [49] "experiment.title_devstage"
 [50] "experiment.title_age"
 [51] "experiment.title_tissue"
 [52] "experiment.attributes_devstage"
 [53] "experiment.attributes_age"
 [54] "experiment.attributes_tissue"
 [55] "sample.title_devstage"
 [56] "sample.title_age"
 [57] "sample.title_tissue"
 [58] "sample.attributes_devstage"
 [59] "sample.attributes_age"
 [60] "sample.attributes_tissue"
 [61] "GEOsample.title_devstage"
 [62] "GEOsample.title_age"
 [63] "GEOsample.title_tissue"
 [64] "GEOsample.characteristics_devstage"
 [65] "GEOsample.characteristics_age"
 [66] "GEOsample.characteristics_tissue"
 [67] "run.title"
 [68] "run.attributes"
 [69] "experiment.library_name"
 [70] "experiment.design_description"
 [71] "experiment.library_construction_protocol"
 [72] "sample.description"
 [73] "GEOsample.dataprocessing"
 [74] "GEOsample.source"
 [75] "GEOsample.treatmentprotocol"
 [76] "GEOsample.extractprotocol"
 [77] "GEOsample.growthprotocol"
 [78] "study.abstract"
 [79] "study.attributes"
 [80] "run.alias"
 [81] "experiment.alias"
 [82] "sample.alias"
 [83] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
 [84] "devstage_curation_runexperimentsampleGEOsample_twentycolumns0"
 [85] "devstage_curation_runexperimentsampleGEOsample_coarselast0"
 [86] "devstage_curation_runexperimentsampleGEOsample_coarse0"
 [87] "devstage_curation_runexperimentsampleGEOsample_twentycolumns"
 [88] "devstage_curation_runexperimentsampleGEOsample_coarselast"
 [89] "devstage_curation_runexperimentsampleGEOsample_coarse"
 [90] "devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse"
 [91] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
 [92] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
 [93] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
 [94] "devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse"
 [95] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns"
 [96] "devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse"
 [97] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
 [98] "tissue_curation_runexperimentsampleGEOsample_twentycolumns0"
 [99] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
[100] "tissue_curation_runexperimentsampleGEOsample_twentycolumns"
[101] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
[102] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
[103] "tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse"
[104] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns"
[105] "tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse"
[106] "technology_curation"

In [78]:
#write.table(metadata_curationstep14, file = paste0("all_zf_dates_devstage_tissue_tech_curated_withGEO_morecolumns.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

## ADD YTTRIA'S CURATION OF PAIRED VS SINGLE

## getting paired vs single this way:
# from /hpc/projects/balla_group/sra_experiments/SRA_metadata
# ls /hpc/projects/balla_group/sra_experiments/versioned_zf_output/75k_unstable/host_mapping/unmapped_reads/Single > zf75k_singleruns.txt
# ls /hpc/projects/balla_group/sra_experiments/versioned_zf_output/75k_unstable/host_mapping/unmapped_reads/Paired > zf75k_pairedruns.txt
# Then making new column called seqdetective.library_layout_curation


metadata_curationstep_seqdetpairedvssingle <- read_tsv("zf_runs_pairedvssingle.tsv")
metadata_curationstep14b <- left_join(metadata_curationstep14,metadata_curationstep_seqdetpairedvssingle)
metadata_curationstep14b <- metadata_curationstep14b %>% relocate(seqdetective.library_layout_curation, .after = technology_curation)

metadata_curationstep14b

Rows: 73955 Columns: 2
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (2): run.accession, seqdetective.library_layout_curation

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.
Joining with `by = join_by(run.accession)`

      run.accession
1     DRR314108
2     DRR314107
3     DRR314106
4     DRR314105
5     DRR314104
6     DRR314103
7     DRR315802
8     DRR315801
9     DRR315800
10    DRR315799
11    DRR315798
12    DRR315797
13    DRR315796
14    DRR315795
15    DRR334977
16    DRR334976
17    DRR334975
18    DRR334974
19    DRR334973
20    DRR334972
21    DRR334971
22    DRR334970
23    DRR334969
24    DRR334968
25    DRR334967
26    DRR334966
27    DRR334965
28    DRR334964
29    DRR334963
30    DRR334962
⋮     ⋮
77300 SRR25438772
77301 SRR25438773
77302 SRR25445395
77303 SRR25445396
77304 SRR25453755
77305 SRR25453756
77306 SRR25453758
77307 SRR25453759
77308 SRR25453761
77309 SRR25453762
77310 SRR25453764
77311 SRR25453765
77312 SRR25453757
77313 SRR25453760
77314 SRR25453763
77315 SRR25453766
77316 SRR25453690
77317 SRR25453691
77318 SRR25453692
77319 SRR25453693
77320 SRR25453694
77321 SRR25453695
77322 SRR25453696
77323 SRR25453697
77324 SRR25453698
77325 SRR25453699
77326 SRR25453700
77327 SRR25453701
77328 SRR065197
77329 SRR065196
      run.filename
1     NA
2     NA
3     NA
4     NA
5     NA
6     NA
7     NA
8     NA
9     NA
10    NA
11    NA
12    NA
13    NA
14    NA
15    NA
16    NA
17    NA
18    NA
19    NA
20    NA
21    NA
22    NA
23    NA
24    NA
25    NA
26    NA
27    NA
28    NA
29    NA
30    NA
⋮     ⋮
77300 72R_S1_L001_R2_001.fastq.gz 72R_S1_L001_R1_001.fastq.gz
77301 72R_S1_L002_R2_001.fastq.gz 72R_S1_L002_R1_001.fastq.gz
77302 DSDF_1.fq.gz DSDF_2.fq.gz
77303 AB72h_1.fq.gz AB72h_2.fq.gz
77304 13RL.fastq.gz
77305 13RH.fastq.gz
77306 12RL.fastq.gz
77307 12RH.fastq.gz
77308 11RL.fastq.gz
77309 11RH.fastq.gz
77310 10RL.fastq.gz
77311 10RH.fastq.gz
77312 13RG.fastq.gz
77313 12RG.fastq.gz
77314 11RG.fastq.gz
77315 10RG.fastq.gz
77316 8R_TCCGGAGA_L007_R1_001.fastq.gz
77317 8RG_TCCGCGAA_L007_R1_001.fastq.gz
77318 6RG_TAATGCGC_L007_R1_001.fastq.gz
77319 6R_CTGAAGCT_L006_R1_001.fastq.gz
77320 4RG_ATTCAGAA_L006_R1_001.fastq.gz
77321 4R_ATTACTCG_L007_R1_001.fastq.gz
77322 3RG_TCTCGCGC_L008_R1_001.fastq.gz
77323 3R_GAATTCGT_L007_R1_001.fastq.gz
77324 2RG_CGGCTATG_L006_R1_001.fastq.gz
77325 2R_CTGAAGCT_L007_R1_001.fastq.gz
77326 1RG_ATTCAGAA_L008_R1_001.fastq.gz
77327 1R_ATTACTCG_L006_R1_001.fastq.gz
77328 MUT_1.txt.tar.gz MUT_2N.txt.tar.gz MUT_3.txt.tar.gz
77329 WT_1.txt.tar WT_2.txt.tar.gz WT_3.txt.tar.gz WT_4.txt.tar.gz
      run.semantic_name       run.total_bases run.total_spots run.read_lengths
1     NA                      23076492885     76679376        0:150.51 1:150.44
2     NA                      26091623771     86694066        0:150.51 1:150.45
3     NA                      23833525756     79191795        0:150.51 1:150.44
4     NA                      27688386114     92009317        0:150.49 1:150.44
5     NA                      22970994572     76322352        0:150.52 1:150.46
6     NA                      23637901630     78541449        0:150.51 1:150.45
7     NA                      10262353995     34151547        0:150.27 1:150.22
8     NA                      11516368634     38355888        0:150.15 1:150.10
9     NA                       8814057148     29367513        0:150.09 1:150.04
10    NA                      10491955578     34900682        0:150.34 1:150.28
11    NA                       9197802250     30604326        0:150.30 1:150.24
12    NA                      10498982078     34931731        0:150.31 1:150.25
13    NA                       9850145990     32782079        0:150.26 1:150.21
14    NA                       9542039835     31780260        0:150.15 1:150.10
15    NA                       3791170746     37701921        0:100.56 1:0
16    NA                       2801693695     27860658        0:100.56 1:0
17    NA                       3148691934     31307464        0:100.57 1:0
18    NA                       2856186273     28400524        0:100.57 1:0
19    NA                       3199929804     31816971        0:100.57 1:0
20    NA                       3658675391     36374718        0:100.58 1:0
21    NA                       3017524690     30006334        0:100.56 1:0
22    NA                       3115915184     30982336        0:100.57 1:0
23    NA                       3206657309     31883532        0:100.57 1:0
24    NA                       3157078356     31416275        0:100.49 1:0
25    NA                       3155807651     31404635        0:100.49 1:0
26    NA                       2589772286     25765782        0:100.51 1:0
27    NA                       3124746628     31095367        0:100.49 1:0
28    NA                       3171661466     31561473        0:100.49 1:0
29    NA                       2916453082     29023768        0:100.48 1:0
30    NA                       2600103192     25872833        0:100.50 1:0
⋮     ⋮                       ⋮               ⋮               ⋮
77300 fastq fastq             29746470730     252088735       0:28 1:90
77301 fastq fastq             29439309532     249485674       0:28 1:90
77302 fastq fastq              7321466700      24404889       0:150 1:150
77303 fastq fastq              7282847400      24276158       0:150 1:150
77304 fastq                    2089168000      32643250       0:64
77305 fastq                    1736530176      27133284       0:64
77306 fastq                    1694665088      26479142       0:64
77307 fastq                    1181540480      18461570       0:64
77308 fastq                       2358656         36854       0:64
77309 fastq                     561279168       8769987       0:64
77310 fastq                    1007185216      15737269       0:64
77311 fastq                    1086843776      16981934       0:64
77312 fastq                     387535808       6055247       0:64
77313 fastq                    1740870592      27201103       0:64
77314 fastq                    1737498752      27148418       0:64
77315 fastq                    1331151616      20799244       0:64
77316 fastq                    1990069575      30616455       0:65
77317 fastq                    2383865380      36674852       0:65
77318 fastq                    1719033680      26446672       0:65
77319 fastq                     236401295       3636943       0:65
77320 fastq                    2585576630      39778102       0:65
77321 fastq                    1488627530      22901962       0:65
77322 fastq                    2357869150      36274910       0:65
77323 fastq                    1536622230      23640342       0:65
77324 fastq                    2280472155      35084187       0:65
77325 fastq                    1604922800      24691120       0:65
77326 fastq                    1334015540      20523316       0:65
77327 fastq                    1185862925      18244045       0:65
77328 fastq fastq fastq        2418427464      31821414       0:76
77329 fastq fastq fastq fastq  2697785376      35497176       0:76
      run.base_counts                                               run.Acount
1     A:6146969533;C:5373690527;G:5458576301;T:6095818756;N:1437768 6146969533
2     A:6955374552;C:6050013285;G:6169385096;T:6915281392;N:1569446 6955374552
3     A:6324521565;C:5556755459;G:5694025045;T:6256748423;N:1475264 6324521565
4     A:7681451080;C:6071566134;G:6242782106;T:7690830655;N:1756139 7681451080
5     A:6142535654;C:5310453740;G:5430124468;T:6086516676;N:1364034 6142535654
6     A:6359178134;C:5420730443;G:5530700546;T:6325864263;N:1428244 6359178134
7     A:2735078560;C:2386126821;G:2433638250;T:2707202814;N:307550  2735078560
8     A:3080341643;C:2678048339;G:2713051368;T:3044449330;N:477954  3080341643
9     A:2350403211;C:2054073465;G:2083044327;T:2326181188;N:354957  2350403211
10    A:2796521111;C:2446218287;G:2483414564;T:2765477785;N:323831  2796521111
11    A:2468967963;C:2130949980;G:2158692262;T:2438931017;N:261028  2468967963
12    A:2804535103;C:2445295179;G:2478768789;T:2770066062;N:316945  2804535103
13    A:2636205537;C:2286508705;G:2319481100;T:2607600624;N:350024  2636205537
14    A:2543384204;C:2224374632;G:2258183435;T:2515655339;N:442225  2543384204
15    A:967477491;C:926887571;G:898697642;T:998107868;N:174          967477491
16    A:700189496;C:702936549;G:679920984;T:718646067;N:599          700189496
17    A:785000734;C:791315678;G:766594599;T:805780465;N:458          785000734
18    A:695685787;C:733754277;G:715270279;T:711475544;N:386          695685787
19    A:777149590;C:825478743;G:804835148;T:792466124;N:199          777149590
20    A:879342063;C:954687406;G:929537615;T:895107890;N:417          879342063
21    A:771967717;C:738814269;G:712866126;T:793876235;N:343          771967717
22    A:765727966;C:794741415;G:771082024;T:784363609;N:170          765727966
23    A:792874386;C:814578518;G:787469614;T:811734581;N:210          792874386
24    A:816263259;C:752748024;G:759884392;T:828182261;N:420          816263259
25    A:819014350;C:749873295;G:756284406;T:830635394;N:206          819014350
26    A:679223577;C:610675892;G:617869465;T:682003195;N:157          679223577
27    A:821891547;C:734660854;G:739230475;T:828963220;N:532          821891547
28    A:836793307;C:742872021;G:750053514;T:841942389;N:235          836793307
29    A:761416880;C:692014182;G:696272089;T:766749729;N:202          761416880
30    A:668944597;C:625686885;G:631010166;T:674461210;N:334          668944597
⋮     ⋮                                                             ⋮
77300 A:9066744486;C:6016546935;G:6505612209;T:8157084760;N:482340  9066744486
77301 A:8981406953;C:5950431891;G:6431556541;T:8075272292;N:641855  8981406953
77302 A:1813294876;C:1845213605;G:1859878889;T:1803063099;N:16231   1813294876
77303 A:1798434468;C:1842126395;G:1854757553;T:1787514637;N:14347   1798434468
77304 A:491435480;C:556848569;G:626704317;T:414165769;N:13865        491435480
77305 A:421791163;C:450901073;G:507159612;T:356667757;N:10571        421791163
77306 A:412504613;C:441115914;G:486407671;T:354625248;N:11642        412504613
77307 A:282401507;C:312999760;G:348583745;T:237547841;N:7627         282401507
77308 A:628520;C:555799;G:609693;T:564639;N:5                           628520
77309 A:138194739;C:146880621;G:155990407;T:120209501;N:3900         138194739
77310 A:243406379;C:261239943;G:302385706;T:200146973;N:6215         243406379
77311 A:256170266;C:286682618;G:326964274;T:217019550;N:7068         256170266
77312 A:94655944;C:99109692;G:113770594;T:79997029;N:2549             94655944
77313 A:415787017;C:459034090;G:503793126;T:362245237;N:11122        415787017
77314 A:426360365;C:450684665;G:510478050;T:349965057;N:10615        426360365
77315 A:310326669;C:355505465;G:405609592;T:259699955;N:9935         310326669
77316 A:473644843;C:520846698;G:589102396;T:406389632;N:86006        473644843
77317 A:573283048;C:622540836;G:710185489;T:477753498;N:102509       573283048
77318 A:439517820;C:424875107;G:481225010;T:373342716;N:73027        439517820
77319 A:57600628;C:60492858;G:68869661;T:49424175;N:13973             57600628
77320 A:647806248;C:654823875;G:732496526;T:550295882;N:154099       647806248
77321 A:376988405;C:376878521;G:409189318;T:325506991;N:64295        376988405
77322 A:575608693;C:613034989;G:678568905;T:490543392;N:113171       575608693
77323 A:400302281;C:383386741;G:418378970;T:334487419;N:66819        400302281
77324 A:590717034;C:568277576;G:627592931;T:493748155;N:136459       590717034
77325 A:426901347;C:388498454;G:422016147;T:367437097;N:69755        426901347
77326 A:364210162;C:319706046;G:337403959;T:312630966;N:64407        364210162
77327 A:327160336;C:286538557;G:300617329;T:271475361;N:71342        327160336
77328 A:604956506;C:600954722;G:608767958;T:600808464;N:2939814      604956506
77329 A:676186765;C:669131645;G:670872323;T:676745206;N:4849437      676186765
      run.Ccount run.Gcount ⋯
1     5373690527 5458576301 ⋯
2     6050013285 6169385096 ⋯
3     5556755459 5694025045 ⋯
4     6071566134 6242782106 ⋯
5     5310453740 5430124468 ⋯
6     5420730443 5530700546 ⋯
7     2386126821 2433638250 ⋯
8     2678048339 2713051368 ⋯
9     2054073465 2083044327 ⋯
10    2446218287 2483414564 ⋯
11    2130949980 2158692262 ⋯
12    2445295179 2478768789 ⋯
13    2286508705 2319481100 ⋯
14    2224374632 2258183435 ⋯
15     926887571  898697642 ⋯
16     702936549  679920984 ⋯
17     791315678  766594599 ⋯
18     733754277  715270279 ⋯
19     825478743  804835148 ⋯
20     954687406  929537615 ⋯
21     738814269  712866126 ⋯
22     794741415  771082024 ⋯
23     814578518  787469614 ⋯
24     752748024  759884392 ⋯
25     749873295  756284406 ⋯
26     610675892  617869465 ⋯
27     734660854  739230475 ⋯
28     742872021  750053514 ⋯
29     692014182  696272089 ⋯
30     625686885  631010166 ⋯
⋮     ⋮          ⋮          ⋱
77300 6016546935 6505612209 ⋯
77301 5950431891 6431556541 ⋯
77302 1845213605 1859878889 ⋯
77303 1842126395 1854757553 ⋯
77304  556848569  626704317 ⋯
77305  450901073  507159612 ⋯
77306  441115914  486407671 ⋯
77307  312999760  348583745 ⋯
77308     555799     609693 ⋯
77309  146880621  155990407 ⋯
77310  261239943  302385706 ⋯
77311  286682618  326964274 ⋯
77312   99109692  113770594 ⋯
77313  459034090  503793126 ⋯
77314  450684665  510478050 ⋯
77315  355505465  405609592 ⋯
77316  520846698  589102396 ⋯
77317  622540836  710185489 ⋯
77318  424875107  481225010 ⋯
77319   60492858   68869661 ⋯
77320  654823875  732496526 ⋯
77321  376878521  409189318 ⋯
77322  613034989  678568905 ⋯
77323  383386741  418378970 ⋯
77324  568277576  627592931 ⋯
77325  388498454  422016147 ⋯
77326  319706046  337403959 ⋯
77327  286538557  300617329 ⋯
77328  600954722  608767958 ⋯
77329  669131645  670872323 ⋯
      tissue_curation_runexperimentsampleGEOsample_twentycolumns0
1     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
2     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
3     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
4     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
5     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
6     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
7     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
8     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
9     Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
10    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
11    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
12    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
13    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
14    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
15    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
16    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
17    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
18    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
19    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
20    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
21    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
22    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined
23    Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined,Undetermined

In [79]:
## let's check column names and rename especially
# devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns
#devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse
#tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns
#tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse
colnames(metadata_curationstep14b)
## change to
## devstage_curation
## devstage_curation_coarse
## tissue_curation
## tissue_curation_coarse


metadata_curationstep14b <- metadata_curationstep14b %>% rename(devstage_curation = devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns)
metadata_curationstep14b <- metadata_curationstep14b %>% rename(devstage_curation_coarse = devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse)
metadata_curationstep14b <- metadata_curationstep14b %>% rename(tissue_curation = tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns)
metadata_curationstep14b <- metadata_curationstep14b %>% rename(tissue_curation_coarse = tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse)

  [1] "run.accession"
  [2] "run.filename"
  [3] "run.semantic_name"
  [4] "run.total_bases"
  [5] "run.total_spots"
  [6] "run.read_lengths"
  [7] "run.base_counts"
  [8] "run.Acount"
  [9] "run.Ccount"
 [10] "run.Gcount"
 [11] "run.Tcount"
 [12] "run.Ncount"
 [13] "run.r1_length"
 [14] "run.r2_length"
 [15] "run.r3_length"
 [16] "run.r4_length"
 [17] "run.experiment"
 [18] "run.pool_member"
 [19] "experiment.instrument_model"
 [20] "experiment.library_layout"
 [21] "experiment.library_selection"
 [22] "experiment.library_source"
 [23] "experiment.library_strategy"
 [24] "experiment.platform"
 [25] "experiment.spot_descriptor"
 [26] "experiment.study_ref"
 [27] "sample.centername"
 [28] "GEOsample.accession"
 [29] "GEOsample.studyID"
 [30] "GEOsample.sampleID_withrun"
 [31] "study.alias"
 [32] "study.type"
 [33] "study.PMIDs"
 [34] "submission.bioprojectsource"
 [35] "submission.srasource"
 [36] "submission.accession"
 [37] "study.accession"
 [38] "bioproject"
 [39] "study.title"
 [40] "sample.accession"
 [41] "experiment.accession"
 [42] "earliest_date"
 [43] "experiment.title"
 [44] "experiment.attributes"
 [45] "sample.title"
 [46] "sample.attributes"
 [47] "GEOsample.title"
 [48] "GEOsample.characteristics"
 [49] "experiment.title_devstage"
 [50] "experiment.title_age"
 [51] "experiment.title_tissue"
 [52] "experiment.attributes_devstage"
 [53] "experiment.attributes_age"
 [54] "experiment.attributes_tissue"
 [55] "sample.title_devstage"
 [56] "sample.title_age"
 [57] "sample.title_tissue"
 [58] "sample.attributes_devstage"
 [59] "sample.attributes_age"
 [60] "sample.attributes_tissue"
 [61] "GEOsample.title_devstage"
 [62] "GEOsample.title_age"
 [63] "GEOsample.title_tissue"
 [64] "GEOsample.characteristics_devstage"
 [65] "GEOsample.characteristics_age"
 [66] "GEOsample.characteristics_tissue"
 [67] "run.title"
 [68] "run.attributes"
 [69] "experiment.library_name"
 [70] "experiment.design_description"
 [71] "experiment.library_construction_protocol"
 [72] "sample.description"
 [73] "GEOsample.dataprocessing"
 [74] "GEOsample.source"
 [75] "GEOsample.treatmentprotocol"
 [76] "GEOsample.extractprotocol"
 [77] "GEOsample.growthprotocol"
 [78] "study.abstract"
 [79] "study.attributes"
 [80] "run.alias"
 [81] "experiment.alias"
 [82] "sample.alias"
 [83] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
 [84] "devstage_curation_runexperimentsampleGEOsample_twentycolumns0"
 [85] "devstage_curation_runexperimentsampleGEOsample_coarselast0"
 [86] "devstage_curation_runexperimentsampleGEOsample_coarse0"
 [87] "devstage_curation_runexperimentsampleGEOsample_twentycolumns"
 [88] "devstage_curation_runexperimentsampleGEOsample_coarselast"
 [89] "devstage_curation_runexperimentsampleGEOsample_coarse"
 [90] "devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse"
 [91] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
 [92] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
 [93] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
 [94] "devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse"
 [95] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns"
 [96] "devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse"
 [97] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
 [98] "tissue_curation_runexperimentsampleGEOsample_twentycolumns0"
 [99] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
[100] "tissue_curation_runexperimentsampleGEOsample_twentycolumns"
[101] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
[102] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
[103] "tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse"
[104] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns_and_twentycolumns"
[105] "tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse"
[106] "technology_curation"
[107] "seqdetective.library_layout_curation"

In [94]:
## late December - add country!

metadata_curationstep_country <- read_tsv("all_zf_submissioncenters2_with_condensed_and_country_v4.tsv")
metadata_curationstep_country <- metadata_curationstep_country %>% select(bioproject,submission.bioprojectsource.country)

Rows: 77329 Columns: 5
── Column specification ────────────────────────────────────────────────────────
Delimiter: "\t"
chr (5): submission.bioprojectsource, submission.accession, bioproject, subm...

ℹ Use `spec()` to retrieve the full column specification for this data.
ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

In [96]:
# 1) Check how many unique countries per bioproject
country_check <- metadata_curationstep_country %>%
  group_by(bioproject) %>%
  summarise(
    n_countries = n_distinct(submission.bioprojectsource.country),
    countries = paste(unique(submission.bioprojectsource.country), collapse = "|")
  )

# View bioprojects with multiple countries (if any)
country_check %>% filter(n_countries > 1)

     bioproject n_countries countries

In [98]:
metadata_curationstep_country_collapsed <- metadata_curationstep_country %>%
  distinct(bioproject, submission.bioprojectsource.country)
head(metadata_curationstep_country_collapsed)

  bioproject  submission.bioprojectsource.country
1 PRJNA382557 Australia
2 PRJNA382558 Australia
3 PRJNA382561 Australia
4 PRJNA505329 Australia
5 PRJNA529645 Australia
6 PRJEB42059  Australia

In [99]:
metadata_curationstep14c <- left_join(metadata_curationstep14b,metadata_curationstep_country_collapsed)
metadata_curationstep14c <- metadata_curationstep14c %>% relocate(submission.bioprojectsource.country, .after = submission.bioprojectsource)

ncol(metadata_curationstep14b)
ncol(metadata_curationstep14c)

Joining with `by = join_by(bioproject)`

[1] 107

[1] 108

In [100]:
colnames(metadata_curationstep14c)

  [1] "run.accession"
  [2] "run.filename"
  [3] "run.semantic_name"
  [4] "run.total_bases"
  [5] "run.total_spots"
  [6] "run.read_lengths"
  [7] "run.base_counts"
  [8] "run.Acount"
  [9] "run.Ccount"
 [10] "run.Gcount"
 [11] "run.Tcount"
 [12] "run.Ncount"
 [13] "run.r1_length"
 [14] "run.r2_length"
 [15] "run.r3_length"
 [16] "run.r4_length"
 [17] "run.experiment"
 [18] "run.pool_member"
 [19] "experiment.instrument_model"
 [20] "experiment.library_layout"
 [21] "experiment.library_selection"
 [22] "experiment.library_source"
 [23] "experiment.library_strategy"
 [24] "experiment.platform"
 [25] "experiment.spot_descriptor"
 [26] "experiment.study_ref"
 [27] "sample.centername"
 [28] "GEOsample.accession"
 [29] "GEOsample.studyID"
 [30] "GEOsample.sampleID_withrun"
 [31] "study.alias"
 [32] "study.type"
 [33] "study.PMIDs"
 [34] "submission.bioprojectsource"
 [35] "submission.bioprojectsource.country"
 [36] "submission.srasource"
 [37] "submission.accession"
 [38] "study.accession"
 [39] "bioproject"
 [40] "study.title"
 [41] "sample.accession"
 [42] "experiment.accession"
 [43] "earliest_date"
 [44] "experiment.title"
 [45] "experiment.attributes"
 [46] "sample.title"
 [47] "sample.attributes"
 [48] "GEOsample.title"
 [49] "GEOsample.characteristics"
 [50] "experiment.title_devstage"
 [51] "experiment.title_age"
 [52] "experiment.title_tissue"
 [53] "experiment.attributes_devstage"
 [54] "experiment.attributes_age"
 [55] "experiment.attributes_tissue"
 [56] "sample.title_devstage"
 [57] "sample.title_age"
 [58] "sample.title_tissue"
 [59] "sample.attributes_devstage"
 [60] "sample.attributes_age"
 [61] "sample.attributes_tissue"
 [62] "GEOsample.title_devstage"
 [63] "GEOsample.title_age"
 [64] "GEOsample.title_tissue"
 [65] "GEOsample.characteristics_devstage"
 [66] "GEOsample.characteristics_age"
 [67] "GEOsample.characteristics_tissue"
 [68] "run.title"
 [69] "run.attributes"
 [70] "experiment.library_name"
 [71] "experiment.design_description"
 [72] "experiment.library_construction_protocol"
 [73] "sample.description"
 [74] "GEOsample.dataprocessing"
 [75] "GEOsample.source"
 [76] "GEOsample.treatmentprotocol"
 [77] "GEOsample.extractprotocol"
 [78] "GEOsample.growthprotocol"
 [79] "study.abstract"
 [80] "study.attributes"
 [81] "run.alias"
 [82] "experiment.alias"
 [83] "sample.alias"
 [84] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
 [85] "devstage_curation_runexperimentsampleGEOsample_twentycolumns0"
 [86] "devstage_curation_runexperimentsampleGEOsample_coarselast0"
 [87] "devstage_curation_runexperimentsampleGEOsample_coarse0"
 [88] "devstage_curation_runexperimentsampleGEOsample_twentycolumns"
 [89] "devstage_curation_runexperimentsampleGEOsample_coarselast"
 [90] "devstage_curation_runexperimentsampleGEOsample_coarse"
 [91] "devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse"
 [92] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
 [93] "devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
 [94] "devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
 [95] "devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse"
 [96] "devstage_curation"
 [97] "devstage_curation_coarse"
 [98] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0"
 [99] "tissue_curation_runexperimentsampleGEOsample_twentycolumns0"
[100] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns"
[101] "tissue_curation_runexperimentsampleGEOsample_twentycolumns"
[102] "tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns"
[103] "tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns"
[104] "tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse"
[105] "tissue_curation"
[106] "tissue_curation_coarse"
[107] "technology_curation"
[108] "seqdetective.library_layout_curation"

In [117]:
## rename 14c to 14b to preserve code below
metadata_curationstep14b <- metadata_curationstep14c

In [118]:
## finally remove columns only now for fewercolumns version
metadata_curationstep14fewer <- metadata_curationstep14b %>% select(-devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns0)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_twentycolumns0)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_coarselast0)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_coarse0)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_twentycolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_coarselast)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_coarse)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_alsostudy_coarse)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-devstage_curation_runexperimentsampleGEOsample_withmultistage_coarse)

metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns0)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_twentycolumns0)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_twentycolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_sixcuratedcolumns_and_twentycolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_withmultistage_sixcuratedcolumns)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% select(-tissue_curation_runexperimentsampleGEOsample_withmultistage_coarse)


# last move 2 study columns to 51,52 & technology after date
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(technology_curation, .after = earliest_date)
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(study.attributes, .after = last_col())
metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(study.abstract, .after = last_col())

In [119]:
head(metadata_curationstep14fewer)
colnames(metadata_curationstep14fewer)

  run.accession run.filename run.semantic_name run.total_bases run.total_spots
1 DRR314108     NA           NA                23076492885     76679376
2 DRR314107     NA           NA                26091623771     86694066
3 DRR314106     NA           NA                23833525756     79191795
4 DRR314105     NA           NA                27688386114     92009317
5 DRR314104     NA           NA                22970994572     76322352
6 DRR314103     NA           NA                23637901630     78541449
  run.read_lengths
1 0:150.51 1:150.44
2 0:150.51 1:150.45
3 0:150.51 1:150.44
4 0:150.49 1:150.44
5 0:150.52 1:150.46
6 0:150.51 1:150.45
  run.base_counts                                               run.Acount
1 A:6146969533;C:5373690527;G:5458576301;T:6095818756;N:1437768 6146969533
2 A:6955374552;C:6050013285;G:6169385096;T:6915281392;N:1569446 6955374552
3 A:6324521565;C:5556755459;G:5694025045;T:6256748423;N:1475264 6324521565
4 A:7681451080;C:6071566134;G:6242782106;T:7690830655;N:1756139 7681451080
5 A:6142535654;C:5310453740;G:5430124468;T:6086516676;N:1364034 6142535654
6 A:6359178134;C:5420730443;G:5530700546;T:6325864263;N:1428244 6359178134
  run.Ccount run.Gcount ⋯ run.alias experiment.alias sample.alias
1 5373690527 5458576301 ⋯ DRR314108 DRX303511        SAMD00399013
2 6050013285 6169385096 ⋯ DRR314107 DRX303510        SAMD00399012
3 5556755459 5694025045 ⋯ DRR314106 DRX303509        SAMD00399011
4 6071566134 6242782106 ⋯ DRR314105 DRX303508        SAMD00399010
5 5310453740 5430124468 ⋯ DRR314104 DRX303507        SAMD00399009
6 5420730443 5530700546 ⋯ DRR314103 DRX303506        SAMD00399008
  devstage_curation devstage_curation_coarse tissue_curation
1 Hatching          Embryo                   Undetermined
2 Hatching          Embryo                   Undetermined
3 Hatching          Embryo                   Undetermined
4 Hatching          Embryo                   Undetermined
5 Hatching          Embryo                   Undetermined
6 Hatching          Embryo                   Undetermined
  tissue_curation_coarse seqdetective.library_layout_curation study.attributes
1 Embryo Imprecise       PAIRED                               NA
2 Embryo Imprecise       PAIRED                               NA
3 Embryo Imprecise       PAIRED                               NA
4 Embryo Imprecise       PAIRED                               NA
5 Embryo Imprecise       PAIRED                               NA
6 Embryo Imprecise       PAIRED                               NA
  study.abstract
1 To characterize the physiological function of Banp  the expression profile of banp mutant and wild type sibling was obtained by ATAC sequencing and RNA sequencing. All data were obtained using embryo heads at 48 hpf.
2 To characterize the physiological function of Banp  the expression profile of banp mutant and wild type sibling was obtained by ATAC sequencing and RNA sequencing. All data were obtained using embryo heads at 48 hpf.
3 To characterize the physiological function of Banp  the expression profile of banp mutant and wild type sibling was obtained by ATAC sequencing and RNA sequencing. All data were obtained using embryo heads at 48 hpf.
4 To characterize the physiological function of Banp  the expression profile of banp mutant and wild type sibling was obtained by ATAC sequencing and RNA sequencing. All data were obtained using embryo heads at 48 hpf.
5 To characterize the physiological function of Banp  the expression profile of banp mutant and wild type sibling was obtained by ATAC sequencing and RNA sequencing. All data were obtained using embryo heads at 48 hpf.
6 To characterize the physiological function of Banp  the expression profile of banp mutant and wild type sibling was obtained by ATAC sequencing and RNA sequencing. All data were obtained using embryo heads at 48 hpf.

 [1] "run.accession"
 [2] "run.filename"
 [3] "run.semantic_name"
 [4] "run.total_bases"
 [5] "run.total_spots"
 [6] "run.read_lengths"
 [7] "run.base_counts"
 [8] "run.Acount"
 [9] "run.Ccount"
[10] "run.Gcount"
[11] "run.Tcount"
[12] "run.Ncount"
[13] "run.r1_length"
[14] "run.r2_length"
[15] "run.r3_length"
[16] "run.r4_length"
[17] "run.experiment"
[18] "run.pool_member"
[19] "experiment.instrument_model"
[20] "experiment.library_layout"
[21] "experiment.library_selection"
[22] "experiment.library_source"
[23] "experiment.library_strategy"
[24] "experiment.platform"
[25] "experiment.spot_descriptor"
[26] "experiment.study_ref"
[27] "sample.centername"
[28] "GEOsample.accession"
[29] "GEOsample.studyID"
[30] "GEOsample.sampleID_withrun"
[31] "study.alias"
[32] "study.type"
[33] "study.PMIDs"
[34] "submission.bioprojectsource"
[35] "submission.bioprojectsource.country"
[36] "submission.srasource"
[37] "submission.accession"
[38] "study.accession"
[39] "bioproject"
[40] "study.title"
[41] "sample.accession"
[42] "experiment.accession"
[43] "earliest_date"
[44] "technology_curation"
[45] "experiment.title"
[46] "experiment.attributes"
[47] "sample.title"
[48] "sample.attributes"
[49] "GEOsample.title"
[50] "GEOsample.characteristics"
[51] "experiment.title_devstage"
[52] "experiment.title_age"
[53] "experiment.title_tissue"
[54] "experiment.attributes_devstage"
[55] "experiment.attributes_age"
[56] "experiment.attributes_tissue"
[57] "sample.title_devstage"
[58] "sample.title_age"
[59] "sample.title_tissue"
[60] "sample.attributes_devstage"
[61] "sample.attributes_age"
[62] "sample.attributes_tissue"
[63] "GEOsample.title_devstage"
[64] "GEOsample.title_age"
[65] "GEOsample.title_tissue"
[66] "GEOsample.characteristics_devstage"
[67] "GEOsample.characteristics_age"
[68] "GEOsample.characteristics_tissue"
[69] "run.title"
[70] "run.attributes"
[71] "experiment.library_name"
[72] "experiment.design_description"
[73] "experiment.library_construction_protocol"
[74] "sample.description"
[75] "GEOsample.dataprocessing"
[76] "GEOsample.source"
[77] "GEOsample.treatmentprotocol"
[78] "GEOsample.extractprotocol"
[79] "GEOsample.growthprotocol"
[80] "run.alias"
[81] "experiment.alias"
[82] "sample.alias"
[83] "devstage_curation"
[84] "devstage_curation_coarse"
[85] "tissue_curation"
[86] "tissue_curation_coarse"
[87] "seqdetective.library_layout_curation"
[88] "study.attributes"
[89] "study.abstract"

In [120]:
## then use this order - adding submission.bioprojectsource.country last
desired_order14 <- c(
    "run.accession", "study.accession", "bioproject", "study.title", "sample.accession",
    "experiment.accession", "earliest_date", 
    "devstage_curation", "devstage_curation_coarse", "tissue_curation", "tissue_curation_coarse",
    "seqdetective.library_layout_curation", "technology_curation", "run.title", "run.attributes",
    "experiment.title", "experiment.alias", "experiment.library_name", "experiment.design_description",
    "experiment.library_construction_protocol", "experiment.attributes", "sample.description",
    "sample.title", "sample.alias", "sample.attributes", "submission.bioprojectsource", "submission.bioprojectsource.country",
    "GEOsample.title", "GEOsample.dataprocessing", "GEOsample.source", "GEOsample.treatmentprotocol",
    "GEOsample.extractprotocol", "GEOsample.growthprotocol", "GEOsample.characteristics", "GEOsample.accession", "run.filename",
    "run.semantic_name", "run.total_bases", "run.total_spots", "experiment.library_strategy",
    "experiment.library_source", "experiment.library_selection", "experiment.library_layout",
    "experiment.platform", "experiment.instrument_model", "experiment.spot_descriptor", "study.alias",
    "study.type", "study.abstract", "study.attributes", "study.PMIDs", 
    "run.alias", "run.read_lengths", "run.base_counts", "run.r1_length", "run.r2_length",
    "run.r3_length", "run.r4_length", "run.Acount", "run.Ccount", "run.Gcount", "run.Tcount", "run.Ncount",
    "run.experiment", "run.pool_member", "experiment.study_ref", "sample.centername", 
    "submission.accession", "submission.srasource"
)


## close but need to move GEOsample fields up
# desired_order14 <- c(
#     "run.accession", "study.accession", "bioproject", "study.title", "sample.accession",
#     "experiment.accession", "earliest_date", 
#     "devstage_curation", "devstage_curation_coarse", "tissue_curation", "tissue_curation_coarse",
#     "seqdetective.library_layout_curation", "technology_curation", "run.title", "run.attributes",
#     "experiment.title", "experiment.alias", "experiment.library_name", "experiment.design_description",
#     "experiment.library_construction_protocol", "experiment.attributes", "sample.description",
#     "sample.title", "sample.alias", "sample.attributes", "submission.bioprojectsource", "run.filename",
#     "run.semantic_name", "run.total_bases", "run.total_spots", "experiment.library_strategy",
#     "experiment.library_source", "experiment.library_selection", "experiment.library_layout",
#     "experiment.platform", "experiment.instrument_model", "experiment.spot_descriptor", "study.alias",
#     "study.type", "study.abstract", "study.attributes", "study.PMIDs", "GEOsample.accession",
#     "GEOsample.title", "GEOsample.dataprocessing", "GEOsample.source", "GEOsample.treatmentprotocol",
#     "GEOsample.extractprotocol", "GEOsample.growthprotocol", "GEOsample.characteristics",
#     "run.alias", "run.read_lengths", "run.base_counts", "run.r1_length", "run.r2_length",
#     "run.r3_length", "run.r4_length", "run.Acount", "run.Ccount", "run.Gcount", "run.Tcount", "run.Ncount",
#     "run.experiment", "run.pool_member", "experiment.study_ref", "sample.centername", 
#     "submission.accession", "submission.srasource"
# )


### move these earlier to before run.filename
#GEOsample.accession	GEOsample.title	GEOsample.dataprocessing	GEOsample.source	GEOsample.treatmentprotocol	GEOsample.extractprotocol	GEOsample.growthprotocol	GEOsample.characteristics

# (seqdetective.library_layout_curation, .after = technology_curation)


# desired_order14 <- c(
#     "run.accession", "study.accession", "bioproject", "study.title", "sample.accession",
#     "experiment.accession", "earliest_date", "run.title", "run.alias", "run.attributes",
#     "experiment.title", "experiment.alias", "experiment.library_name", "experiment.design_description",
#     "experiment.library_construction_protocol", "experiment.attributes", "sample.description",
#     "sample.title", "sample.alias", "sample.attributes", "submission.bioprojectsource", "run.filename",
#     "run.semantic_name", "run.total_bases", "run.total_spots", "experiment.library_strategy",
#     "experiment.library_source", "experiment.library_selection", "experiment.library_layout",
#     "experiment.platform", "experiment.instrument_model", "experiment.spot_descriptor", "study.alias",
#     "study.type", "study.abstract", "study.attributes", "study.PMIDs", "GEOsample.accession",
#     "GEOsample.title", "GEOsample.dataprocessing", "GEOsample.source", "GEOsample.treatmentprotocol",
#     "GEOsample.extractprotocol", "GEOsample.growthprotocol", "GEOsample.characteristics", "GEO_studyID",
#     "GEO_sampleID_withrun", "run.read_lengths", "run.base_counts", "run.r1_length", "run.r2_length",
#     "run.r3_length", "run.r4_length", "run.Acount", "run.Ccount", "run.Gcount", "run.Tcount", "run.Ncount",
#     "run.experiment", "run.pool_member", "experiment.study_ref", "sample.centername", 
#     "submission.accession", "submission.srasource", "run.enafirstpublic_date",
#     "run.enalastupdate_date", "run.lastSRAFile_date", "run.published_date", "run.SRAFile_date",
#     "sample.enafirstpublic_date", "sample.enafirstpublic2_date", "sample.enalastupdate_date",
#     "sample.enalastupdate2_date", "sample.insdcfirstpublic_date", "sample.insdclastupdate_date",
#     "study.enafirstpublic_date", "study.enalastupdate_date", "GEOsample.submission_date",
#     "GEOsample.release_date", "GEOsample.lastupdate_date"
# )

In [121]:
## move by select

metadata_curationstep14fewer <- metadata_curationstep14fewer %>%
  select(all_of(desired_order14))

In [122]:

# ## also 9 more to get everything up to study.abstract into first 50 columns???
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.title, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.attributes, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.filename, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.semantic_name, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.base_counts, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.Acount, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.Ccount, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.Gcount, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.Tcount, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.Ncount, .before = experiment.title_devstage)


# ## lastly move these to near end (after study.abstract)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.experiment, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.pool_member, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(run.alias, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(experiment.alias, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(experiment.study_ref, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(sample.alias, .before = experiment.title_devstage)
# metadata_curationstep14fewer <- metadata_curationstep14fewer %>% relocate(study.alias, .before = experiment.title_devstage)

In [123]:
colnames(metadata_curationstep14fewer)

 [1] "run.accession"
 [2] "study.accession"
 [3] "bioproject"
 [4] "study.title"
 [5] "sample.accession"
 [6] "experiment.accession"
 [7] "earliest_date"
 [8] "devstage_curation"
 [9] "devstage_curation_coarse"
[10] "tissue_curation"
[11] "tissue_curation_coarse"
[12] "seqdetective.library_layout_curation"
[13] "technology_curation"
[14] "run.title"
[15] "run.attributes"
[16] "experiment.title"
[17] "experiment.alias"
[18] "experiment.library_name"
[19] "experiment.design_description"
[20] "experiment.library_construction_protocol"
[21] "experiment.attributes"
[22] "sample.description"
[23] "sample.title"
[24] "sample.alias"
[25] "sample.attributes"
[26] "submission.bioprojectsource"
[27] "submission.bioprojectsource.country"
[28] "GEOsample.title"
[29] "GEOsample.dataprocessing"
[30] "GEOsample.source"
[31] "GEOsample.treatmentprotocol"
[32] "GEOsample.extractprotocol"
[33] "GEOsample.growthprotocol"
[34] "GEOsample.characteristics"
[35] "GEOsample.accession"
[36] "run.filename"
[37] "run.semantic_name"
[38] "run.total_bases"
[39] "run.total_spots"
[40] "experiment.library_strategy"
[41] "experiment.library_source"
[42] "experiment.library_selection"
[43] "experiment.library_layout"
[44] "experiment.platform"
[45] "experiment.instrument_model"
[46] "experiment.spot_descriptor"
[47] "study.alias"
[48] "study.type"
[49] "study.abstract"
[50] "study.attributes"
[51] "study.PMIDs"
[52] "run.alias"
[53] "run.read_lengths"
[54] "run.base_counts"
[55] "run.r1_length"
[56] "run.r2_length"
[57] "run.r3_length"
[58] "run.r4_length"
[59] "run.Acount"
[60] "run.Ccount"
[61] "run.Gcount"
[62] "run.Tcount"
[63] "run.Ncount"
[64] "run.experiment"
[65] "run.pool_member"
[66] "experiment.study_ref"
[67] "sample.centername"
[68] "submission.accession"
[69] "submission.srasource"

In [124]:
## get summaries of categories
metadata_curationstep14fewer %>% group_by(devstage_curation) %>% summarize(count=n()) %>% arrange(desc(count))
metadata_curationstep14fewer %>% group_by(devstage_curation_coarse) %>% summarize(count=n()) %>% arrange(desc(count))
metadata_curationstep14fewer %>% group_by(tissue_curation) %>% summarize(count=n()) %>% arrange(desc(count))
metadata_curationstep14fewer %>% group_by(tissue_curation_coarse) %>% summarize(count=n()) %>% arrange(desc(count))

   devstage_curation count
1  Larval            19709
2  Adult             15670
3  Undetermined      10064
4  Pharyngula         7444
5  Hatching           5782
6  Gastrula           4676
7  Multi-stage        4114
8  Segmentation       3626
9  Juvenile           2710
10 Blastula           2320
11 Cleavage            676
12 Zygote              538

  devstage_curation_coarse count
1 Embryo                   30056
2 Larval                   21006
3 Adult                    16849
4 Undetermined              4327
5 Juvenile                  2716
6 Multi-stage               2375

   tissue_curation    count
1  Whole Organism     25682
2  Embryo Imprecise    8973
3  Brain               6454
4  Multi-tissue        5171
5  Undetermined        4325
6  Trunk               3555
7  Heart               3173
8  Pancreas            2522
9  Spinal Cord         2275
10 Liver               1826
11 Eye                 1527
12 Fin                 1280
13 Gonad               1126
14 Cancer or Tumor     1116
15 Kidney              1056
16 Spleen               948
17 Gut                  899
18 Head                 838
19 Tail                 804
20 Muscle               605
21 Blood                574
22 Skin                 398
23 Cell Line            387
24 Endothelium          374
25 Oocyte               276
26 Gill                 261
27 Lateral Line         200
28 Bone or Cartilage    119
29 Jaw                   85
30 Thymus                79
31 BCR TCR repertoire    65
32 Lymphatic System      64
33 Adipose Tissue        57
34 Marrow                49
35 Pineal Gland          40
36 Pituitary Gland       40
37 Pharyngeal Arch       34
38 Scale                 32
39 Ear                   18
40 Swim Bladder          12
41 Thyroid               10

   tissue_curation_coarse    count
1  All anatomical structures 34655
2  Nervous System             9567
3  Multi-system               6009
4  Surface Structure          5350
5  Cardiovascular System      3611
6  Endocrine System           2612
7  Embryo Imprecise           2580
8  Liver and Biliary System   1826
9  Sensory System             1745
10 Undetermined               1745
11 Hematopoietic System       1666
12 Reproductive System        1402
13 Cancer or Tumor            1116
14 Renal System               1105
15 Digestive System            899
16 Muscular System             605
17 Cell Line                   387
18 Respiratory System          261
19 Skeletal Element            119
20 Adipose Tissue               57
21 Swim Bladder                 12

In [125]:
write.table(metadata_curationstep14fewer, file = paste0("all_zf_dates_devstage_tissue_tech_curated.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

In [126]:
unique(metadata_curationstep14fewer$tissue_curation)
unique(metadata_curationstep14fewer$tissue_curation_coarse)

 [1] "Undetermined"       "Gut"                "Brain"
 [4] "Spinal Cord"        "Gonad"              "Multi-tissue"
 [7] "Whole Organism"     "Fin"                "Trunk"
[10] "Liver"              "Muscle"             "Heart"
[13] "Gill"               "Pancreas"           "Eye"
[16] "Embryo Imprecise"   "Oocyte"             "Skin"
[19] "Spleen"             "Head"               "Swim Bladder"
[22] "Kidney"             "Blood"              "Scale"
[25] "Cell Line"          "Tail"               "Pharyngeal Arch"
[28] "Bone or Cartilage"  "Endothelium"        "Lateral Line"
[31] "Cancer or Tumor"    "Thymus"             "Pituitary Gland"
[34] "Jaw"                "Adipose Tissue"     "Pineal Gland"
[37] "Ear"                "Thyroid"            "Lymphatic System"
[40] "Marrow"             "BCR TCR repertoire"

 [1] "Embryo Imprecise"          "Undetermined"
 [3] "Digestive System"          "Nervous System"
 [5] "Reproductive System"       "Multi-system"
 [7] "All anatomical structures" "Surface Structure"
 [9] "Liver and Biliary System"  "Muscular System"
[11] "Cardiovascular System"     "Respiratory System"
[13] "Endocrine System"          "Sensory System"
[15] "Hematopoietic System"      "Swim Bladder"
[17] "Renal System"              "Cell Line"
[19] "Skeletal Element"          "Cancer or Tumor"
[21] "Adipose Tissue"

In [127]:
## also make full set of columns for LLMs...instead use 'rawcolumns' from above
# ## pulling intermediate columns
# metadata_curationstep14toadd <- metadata_curationstep9 %>% select(run.accession,43:50)

# ## join then move to before experiment.title
# metadata_curationstep14withintermediates <- left_join(metadata_curationstep14,metadata_curationstep14toadd)

# metadata_curationstep14withintermediates <- metadata_curationstep14withintermediates %>% relocate(85:92, .before = experiment.title)

# metadata_curationstep14withintermediates
# write.table(metadata_curationstep14withintermediates, file = paste0("all_zf_dates_devstage_tissue_tech_curated_withGEO_morecolumnsandintermediates.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)


# ## first saving a fullcolumns version then removing ~10 columns
write.table(metadata_curationstep14b, file = paste0("all_zf_dates_devstage_tissue_tech_curated_rawcolumns.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

In [128]:

# ## pulling unknown in either coarse devstage or tissue
# ## latest 2025 'unknown' set - where either  devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse or tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse
# ## are undetermined

# ## filter 
# metadata_curationstep13_unknown <- metadata_curationstep13fewer2 %>% filter(devstage_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse == "Undetermined" | tissue_curation_runexperimentsampleGEOsample_alsostudy_withmultistage_coarse == "Undetermined")
# ## 2409 of 5444 have pubmed pmids!
# write.table(metadata_curationstep13_unknown, file = paste0("all_zf_dates_devstage_tissue_tech_curated_withGEO_unknowndevstageortissue.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

## separate devstage & tissue unknowns
metadata_curationstep14fewer_unknowndev <- metadata_curationstep14fewer %>% filter(devstage_curation_coarse == "Undetermined")
metadata_curationstep14fewer_unknowntis <- metadata_curationstep14fewer %>% filter(tissue_curation_coarse == "Undetermined")
write.table(metadata_curationstep14fewer_unknowndev, file = paste0("all_zf_dates_devstage_tissue_tech_curated_unknowndevstage.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)
write.table(metadata_curationstep14fewer_unknowntis, file = paste0("all_zf_dates_devstage_tissue_tech_curated_unknowntissue.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)
metadata_curationstep14fewer_unknowndev
metadata_curationstep14fewer_unknowntis

     run.accession study.accession bioproject
1    DRR050167     DRP003043       PRJDB4416
2    DRR050166     DRP003043       PRJDB4416
3    DRR050165     DRP003043       PRJDB4416
4    DRR050164     DRP003043       PRJDB4416
5    DRR050163     DRP003043       PRJDB4416
6    DRR050162     DRP003043       PRJDB4416
7    DRR051067     DRP003977       PRJDB4470
8    DRR051063     DRP003977       PRJDB4470
9    ERR1125090    ERP013160       PRJEB11748
10   ERR1125089    ERP013160       PRJEB11748
11   ERR1125088    ERP013160       PRJEB11748
12   ERR1125087    ERP013160       PRJEB11748
13   ERR1125086    ERP013160       PRJEB11748
14   ERR1125085    ERP013160       PRJEB11748
15   ERR1125084    ERP013160       PRJEB11748
16   ERR1125083    ERP013160       PRJEB11748
17   ERR1125082    ERP013160       PRJEB11748
18   ERR1125081    ERP013160       PRJEB11748
19   ERR1125080    ERP013160       PRJEB11748
20   ERR1125079    ERP013160       PRJEB11748
21   ERR1125078    ERP013160       PRJEB11748
22   ERR1125077    ERP013160       PRJEB11748
23   ERR1125076    ERP013160       PRJEB11748
24   ERR1125075    ERP013160       PRJEB11748
25   ERR1125074    ERP013160       PRJEB11748
26   ERR1125073    ERP013160       PRJEB11748
27   ERR1125072    ERP013160       PRJEB11748
28   ERR1125071    ERP013160       PRJEB11748
29   ERR1125070    ERP013160       PRJEB11748
30   ERR1125069    ERP013160       PRJEB11748
⋮    ⋮             ⋮               ⋮
4298 SRR25247935   SRP448831       PRJNA994052
4299 SRR25247937   SRP448831       PRJNA994052
4300 SRR25247938   SRP448831       PRJNA994052
4301 SRR25247939   SRP448831       PRJNA994052
4302 SRR25247940   SRP448831       PRJNA994052
4303 SRR25247944   SRP448831       PRJNA994052
4304 SRR25247941   SRP448831       PRJNA994052
4305 SRR25247942   SRP448831       PRJNA994052
4306 SRR25247943   SRP448831       PRJNA994052
4307 SRR25247945   SRP448831       PRJNA994052
4308 SRR25247946   SRP448831       PRJNA994052
4309 SRR25247947   SRP448831       PRJNA994052
4310 SRR25247948   SRP448831       PRJNA994052
4311 SRR25253548   SRP449239       PRJNA994180
4312 SRR25253549   SRP449239       PRJNA994180
4313 SRR25253550   SRP449239       PRJNA994180
4314 SRR25253551   SRP449239       PRJNA994180
4315 SRR25253552   SRP449239       PRJNA994180
4316 SRR25253553   SRP449239       PRJNA994180
4317 SRR25253554   SRP449239       PRJNA994180
4318 SRR25253555   SRP449239       PRJNA994180
4319 SRR25288286   SRP449631       PRJNA994919
4320 SRR25288287   SRP449631       PRJNA994919
4321 SRR25288288   SRP449631       PRJNA994919
4322 SRR25320257   SRP450092       PRJNA996066
4323 SRR25320258   SRP450092       PRJNA996066
4324 SRR25320259   SRP450092       PRJNA996066
4325 SRR25320260   SRP450092       PRJNA996066
4326 SRR25320261   SRP450092       PRJNA996066
4327 SRR25320262   SRP450092       PRJNA996066
     study.title
1    Transcriptome analysis in ES1 expressing rods of zebrafish
2    Transcriptome analysis in ES1 expressing rods of zebrafish
3    Transcriptome analysis in ES1 expressing rods of zebrafish
4    Transcriptome analysis in ES1 expressing rods of zebrafish
5    Transcriptome analysis in ES1 expressing rods of zebrafish
6    Transcriptome analysis in ES1 expressing rods of zebrafish
7    Gene expression analysis of the zebrafish brain
8    Gene expression analysis of the zebrafish brain
9    Analysis of single CD41 cell transcriptomes from Zebrafish
10   Analysis of single CD41 cell transcriptomes from Zebrafish
11   Analysis of single CD41 cell transcriptomes from Zebrafish
12   Analysis of single CD41 cell transcriptomes from Zebrafish
13   Analysis of single CD41 cell transcriptomes from Zebrafish
14   Analysis of single CD41 cell transcriptomes from Zebrafish
15   Analysis of single CD41 cell transcriptomes from Zebrafish
16   Analysis of single CD41 cell transcriptomes from Zebrafish
17   Analysis of single CD41 cell transcriptomes from Zebrafish
18   Analysis of single CD41 cell transcriptomes from Zebrafish
19   Analysis of single CD41 cell transcriptomes from Zebrafish
20   Analysis of single CD41 cell transcriptomes from Zebrafish
21   Analysis of single CD41 cell transcriptomes from Zebrafish
22   Analysis of single CD41 cell transcriptomes from Zebrafish
23   Analysis of single CD41 cell transcriptomes from Zebrafish
24   Analysis of single CD41 cell transcriptomes from Zebrafish
25   Analysis of single CD41 cell transcriptomes from Zebrafish
26   Analysis of single CD41 cell transcriptomes from Zebrafish
27   Analysis of single CD41 cell transcriptomes from Zebrafish
28   Analysis of single CD41 cell transcriptomes from Zebrafish
29   Analysis of single CD41 cell transcriptomes from Zebrafish
30   Analysis of single CD41 cell transcriptomes from Zebrafish
⋮    ⋮
4298 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4299 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4300 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4301 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4302 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4303 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4304 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4305 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4306 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4307 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4308 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4309 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4310 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
4311 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4312 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4313 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4314 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4315 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4316 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4317 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4318 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
4319 Diverse Epithelial Lymphocytes in Zebrafish Revealed Using a Novel Scale Biopsy Method
4320 Diverse Epithelial Lymphocytes in Zebrafish Revealed Using a Novel Scale Biopsy Method
4321 Diverse Epithelial Lymphocytes in Zebrafish Revealed Using a Novel Scale Biopsy Method
4322 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
4323 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
4324 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
4325 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
4326 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
4327 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
     sample.accession experiment.accession earliest_date devstage_curation
1    DRS025834        DRX045209            2016-03-09    Undetermined
2    DRS025833        DRX045208            2016-03-09    Undetermined
3    DRS025832        DRX045207            2016-03-09    Undetermined
4    DRS025831        DRX045206            2016-03-09    Undetermined
5    DRS025830        DRX045205            2016-03-09    Undetermined
6    DRS025829        DRX045204            2016-03-09    Undetermined
7    DRS057267        DRX045959            2018-01-06    Undetermined
8    DRS057266        DRX045955            2018-01-06    Undetermined
9    ERS959300        ERX1204289           2016-01-08    Undetermined
10   ERS959299        ERX1204288           2016-01-08    Undetermined
11   ERS959298        ERX1204287           2016-01-08    Undetermined
12   ERS959297        ERX1204286           2016-01-08    Undetermined
13   ERS959296        ERX1204285           2016-01-08    Undetermined
14   ERS959295        ERX1204284           2016-01-08    Undetermined
15   ERS959294        ERX1204283           2016-01-08    Undetermined
16   ERS959293        ERX1204282           2016-01-08    Undetermined
17   ERS959292        ERX1204281           2016-01-08    Undetermined
18   ERS959291        ERX1204280           2016-01-08    Undetermined
19   ERS959290        ERX1204279           2016-01-08    Undetermined
20   ERS959289        ERX1204278           2016-01-08    Undetermined
21   ERS959288        ERX1204277           2016-01-08    Undetermined
22   ERS959287        ERX1204276           2016-01-08    Undetermined
23   ERS959286        ERX1204275           2016-01-08    Undetermined
24   ERS959285        ERX1204274           2016-01-08    Undetermined
25   ERS959284        ERX1204273           2016-01-08    Undetermined
26   ERS959283        ERX1204272           2016-01-08    Undetermined
27   ERS959282        ERX1204271           2016-01-08    Undetermined
28   ERS959281        ERX1204270           2016-01-08    Undetermined
29   ERS959280        ERX1204269           2016-01-08    Undetermined
30   ERS959279        ERX1204268           2016-01-08    Undetermined
⋮    ⋮                ⋮                    ⋮             ⋮
4298 SRS18268478      SRX20994072          2023-07-12    Undetermined
4299 SRS18268479      SRX20994071          2023-07-12    Undetermined
4300 SRS18268477      SRX20994070          2023-07-12    Undetermined
4301 SRS18268476      SRX20994069          2023-07-12    Undetermined
4302 SRS18268475      SRX20994068          2023-07-12    Undetermined
4303 SRS18268474      SRX20994067          2023-07-12    Undetermined
4304 SRS18268473      SRX20994066          2023-07-12    Undetermined
4305 SRS18268472      SRX20994065          2023-07-12    Undetermined
4306 SRS18268471      SRX20994064          2023-07-12    Undetermined
4307 SRS18268470      SRX20994063          2023-07-12    Undetermined
4308 SRS18268469      SRX20994062          2023-07-12    Undetermined
4309 SRS18268468      SRX20994061          2023-07-12    Undetermined
4310 SRS18268467      SRX20994060          2023-07-12    Undetermined
4311 SRS18272874      SRX20999601          2023-07-12    Undetermined
4312 SRS18272873      SRX20999600          2023-07-12    Undetermined
4313 SRS18272872      SRX20999599          2023-07-12    Undetermined
4314 SRS18272871      SRX20999598          2023-07-12    Undetermined
4315 SRS18272870      SRX20999597          2023-07-12    Undetermined
4316 SRS18272869      SRX20999596          2023-07-12    Undetermined
4317 SRS18272868      SRX20999595          2023-07-12    Undetermined
4318 SRS18272867      SRX20999594          2023-07-12    Undetermined
4319 SRS18304345      SRX21031899          2023-07-14    Undetermined
4320 SRS18304344      SRX21031898          2023-07-14    Undetermined
4321 SRS18304343      SRX21031897          2023-07-14    Undetermined
4322 SRS18332761      SRX21062493          2023-07-18    Undetermined
4323 SRS18332759      SRX21062492          2023-07-18    Undetermined
4324 SRS18332760      SRX21062491          2023-07-18    Undetermined
4325 SRS18332758      SRX21062490          2023-07-18    Undetermined
4326 SRS18332757      SRX21062489          2023-07-18    Undetermined
4327 SRS18332756      SRX21062488          2023-07-18    Undetermined
     devstage_curation_coarse tissue_curation ⋯ run.Ccount run.Gcount
1    Undetermined             Fin             ⋯   79475572   83520360
2    Undetermined             Fin             ⋯   86415371   90822163
3    Undetermined             Fin             ⋯  129885620  136727379
4    Undetermined             Fin             ⋯   73070267   77738821
5    Undetermined             Fin             ⋯  113928273  120051739
6    Undetermined             Fin             ⋯  104872341  113114502
7    Undetermined             Brain           ⋯ 3957379257 3797879751
8    Undetermined             Brain           ⋯ 3082552426 3134669086
9    Undetermined             Multi-tissue    ⋯  119943911  107010121
10   Undetermined             Multi-tissue    ⋯  177925445  163584543
11   Undetermined             Multi-tissue    ⋯   65911990   56070317
12   Undetermined             Multi-tissue    ⋯  147934323  135438512
13   Undetermined             Multi-tissue    ⋯  113778792  100790228
14   Undetermined             Multi-tissue    ⋯  128853235  113767154
15   Undetermined             Multi-tissue    ⋯   70641903   63273746
16   Undetermined             Multi-tissue    ⋯  431331917  395349978
17   Undetermined             Multi-tissue    ⋯  124659105  116512220
18   Undetermined             Multi-tissue    ⋯  126637668  113969658
19   Undetermined             Multi-tissue    ⋯  101773143   92417709
20   Undetermined             Multi-tissue    ⋯   99221881   89989919
21   Undetermined             Multi-tissue    ⋯  109515316   94767411
22   Undetermined             Multi-tissue    ⋯  136424495  117844174
23   Undetermined             Multi-tissue    ⋯  255515134  223466753
24   Undetermined             Multi-tissue    ⋯  192249391  170692002
25   Undetermined             Multi-tissue    ⋯  169567853  145782205
26   Undetermined             Multi-tissue    ⋯  112027431   94702679
27   Undetermined             Multi-tissue    ⋯  131541373  114686700
28   Undetermined             Multi-tissue    ⋯  232331615  201687129
29   Undetermined             Multi-tissue    ⋯  235501274  209565850
30   Undetermined             Multi-tissue    ⋯  123870390  106224297
⋮    ⋮                        ⋮               ⋱ ⋮          ⋮
4298 Undetermined             Marrow          ⋯ 1520031310 1849059138
4299 Undetermined             Marrow          ⋯ 1802515744 2029257538
4300 Undetermined             Marrow          ⋯ 1639877964 1850759915
4301 Undetermined             Marrow          ⋯ 1520823030 1694205993
4302 Undetermined             Marrow          ⋯ 1669568274 1858403783
4303 Undetermined             Marrow          ⋯ 1744556837 1930871463
4304 Undetermined             Marrow          ⋯ 1527167803 1677900707
4305 Undetermined             Thymus          ⋯ 1601232886 1787641759
4306 Undetermined             Thymus          ⋯ 1558094669 1747369217
4307 Undetermined             Thymus          ⋯ 1690333059 1912063529
4308 Undetermined             Thymus          ⋯ 1804435410 2009975925
4309 Undetermined             Thymus          ⋯ 1702138319 1938033936
4310 Undetermined             Thymus          ⋯ 1886184090 2274314822
4311 Undetermined             Eye             ⋯ 1687426244 1785339875
4312 Undetermined             Eye             ⋯ 1077631009 1137108891
4313 Undetermined             Eye             ⋯ 1039410282 1103144747
4314 Undetermined             Eye             ⋯ 1128470469 1198385405
4315 Undetermined             Eye             ⋯  751206133  783572508
4316 Undetermined             Eye             ⋯  788484354  823319620
4317 Undetermined             Eye             ⋯ 1233227329 1289921693
4318 Undetermined             Eye             ⋯ 1274004687 1327972080
4319 Undetermined             Scale           ⋯ 2322303742 2574066837
4320 Undetermined             Multi-tissue    ⋯ 2439333260 2665663309
4321 Undetermined             Thymus          ⋯ 2208968733 2525266634
4322 Undetermined             Gut             ⋯ 2108316310 2611487888
4323 Undetermined             Gut             ⋯ 3613697125 4175903766
4324 Undetermined             Gut             ⋯ 2385768928 2685002752
4325 Undetermined             Gut             ⋯ 2385685766 2716165649
4326 Undetermined             Gut             ⋯ 2496955346 2795939748
4327 Undetermined             Gut             ⋯ 2461578237 2848406965
     run.Tcount run.Ncount run.experiment run.pool_member experiment.study_ref
1     101561779       0    DRX045209      DRS025834       DRP003043
2     121670773       0    DRX045208      DRS025833       DRP003043
3     153657736       0    DRX045207      DRS025832       DRP003043
4      92783592       0    DRX045206      DRS025831       DRP003043
5     146481242       0    DRX045205      DRS025830       DRP003043
6     123927858       0    DRX045204      DRS025829       DRP003043
7    5144366288 4618438    DRX045959      DRS057267       DRP003977
8    4606055524 5037798    DRX045955      DRS057266       DRP003977
9     144702244   58425    ERX1204289     ERS959300       ERP013160
10    204300253   90496    ERX1204288     ERS959299       ERP013160
11     83174302   34739    ERX1204287     ERS959298       ERP013160
12    179644376   73873    ERX1204286     ERS959297       ERP013160
13    147398469   59692    ERX1204285     ERS959296       ERP013160
14    160924124   65914    ERX1204284     ERS959295       ERP013160
15     92076705   36992    ERX1204283     ERS959294       ERP013160
16    501936461  220985    ERX1204282     ERS959293       ERP013160
17    154445053   65245    ERX1204281     ERS959292       ERP013160
18    161280891   65508    ERX1204280     ERS959291       ERP013160
19    126320727   52529    ERX1204279     ERS959290       ERP013160
20    125475523   51043    ERX1204278     ERS959289       ERP013160
21    130118835   52935    ERX1204277     ERS959288       ERP013160
22    161912153   66959    ERX1204276     ERS959287       ERP013160
23    289885657  118527    ERX1204275     ERS959286       ERP013160
24    236829325   97591    ERX1204274     ERS959285       ERP013160
25    201982364   85092    ERX1204273     ERS959284       ERP013160
26    140510643   49324    ERX1204272     ERS959283       ERP013160
27    168631560   69868    ERX1204271     ERS959282       ERP013160
28    278600621  113090    ERX1204270     ERS959281       ERP013160
29    290299755  122822    ERX1204269     ERS959280       ERP013160
30    154741718   61242    ERX1204268     ERS959279       ERP013160
⋮    ⋮          ⋮          ⋮              ⋮               ⋮
4298 2280354641   31300    SRX20994072    SRS18268478     SRP448831
4299 3030992999   38416    SRX20994071    SRS18268479     SRP448831
4300 2689649693   34194    SRX20994070    SRS18268477     SRP448831
4301 2537855107   32317    SRX20994069    SRS18268476     SRP448831
4302 2815553963   35738    SRX20994068    SRS18268475     SRP448831
4303 2836881708   35911    SRX20994067    SRS18268474     SRP448831
4304 2446333840   31681    SRX20994066    SRS18268473     SRP448831
4305 2580087936   33513    SRX20994065    SRS18268472     SRP448831
4306 2514010546   32402    SRX20994064    SRS18268471     SRP448831
4307 2635521209   34284    SRX20994063    SRS18268470     SRP448831
4308 3001626142   38381    SRX20994062    SRS18268469     SRP448831
4309 2901841449   36802    SRX20994061    SRS18268468     SRP448831
4310 2665699767   37990    SRX20994060    SRS18268467     SRP448831
4311 2616019593 1816455    SRX20999601    SRS18272874     SRP449239
4312 1679156666 1135302    SRX20999600    SRS18272873     SRP449239
4313 1685792809 1154423    SRX20999599    SRS18272872     SRP449239
4314 1871305613 1288123    SRX20999598    SRS18272871     SRP449239
4315 1216050370  816882    SRX20999597    SRS18272870     SRP449239
4316 1297264565  884334    SRX20999596    SRS18272869     SRP449239
4317 1921011454 1016257    SRX20999595    SRS18272868     SRP449239

     run.accession study.accession bioproject
1    DRR334977     DRP008001       PRJDB12578
2    DRR334976     DRP008001       PRJDB12578
3    DRR334975     DRP008001       PRJDB12578
4    DRR334974     DRP008001       PRJDB12578
5    DRR334973     DRP008001       PRJDB12578
6    DRR334972     DRP008001       PRJDB12578
7    DRR334971     DRP008001       PRJDB12578
8    DRR334970     DRP008001       PRJDB12578
9    DRR334969     DRP008001       PRJDB12578
10   DRR334968     DRP008001       PRJDB12578
11   DRR334967     DRP008001       PRJDB12578
12   DRR334966     DRP008001       PRJDB12578
13   DRR334965     DRP008001       PRJDB12578
14   DRR334964     DRP008001       PRJDB12578
15   DRR334963     DRP008001       PRJDB12578
16   DRR334962     DRP008001       PRJDB12578
17   DRR334961     DRP008001       PRJDB12578
18   DRR334960     DRP008001       PRJDB12578
19   DRR408245     DRP012042       PRJDB14275
20   DRR408244     DRP012042       PRJDB14275
21   DRR408243     DRP012042       PRJDB14275
22   ERR977399     ERP011343       PRJEB10137
23   ERR977398     ERP011343       PRJEB10137
24   ERR977397     ERP011343       PRJEB10137
25   ERR1675931    ERP011346       PRJEB10140
26   ERR977594     ERP011346       PRJEB10140
27   ERR977593     ERP011346       PRJEB10140
28   ERR977592     ERP011346       PRJEB10140
29   ERR977591     ERP011346       PRJEB10140
30   ERR977590     ERP011346       PRJEB10140
⋮    ⋮             ⋮               ⋮
1716 SRR24511699   SRP437162       PRJNA971593
1717 SRR24511700   SRP437162       PRJNA971593
1718 SRR24511701   SRP437162       PRJNA971593
1719 SRR24511702   SRP437162       PRJNA971593
1720 SRR24511703   SRP437162       PRJNA971593
1721 SRR24511704   SRP437162       PRJNA971593
1722 SRR24511705   SRP437162       PRJNA971593
1723 SRR24511706   SRP437162       PRJNA971593
1724 SRR24511707   SRP437162       PRJNA971593
1725 SRR25158718   SRP447562       PRJNA991461
1726 SRR25158716   SRP447562       PRJNA991461
1727 SRR25158717   SRP447562       PRJNA991461
1728 SRR25158719   SRP447562       PRJNA991461
1729 SRR25158720   SRP447562       PRJNA991461
1730 SRR25158725   SRP447562       PRJNA991461
1731 SRR25158721   SRP447562       PRJNA991461
1732 SRR25158724   SRP447562       PRJNA991461
1733 SRR25158722   SRP447562       PRJNA991461
1734 SRR25158723   SRP447562       PRJNA991461
1735 SRR25158726   SRP447562       PRJNA991461
1736 SRR25158727   SRP447562       PRJNA991461
1737 SRR25204253   SRP448120       PRJNA992237
1738 SRR25204254   SRP448120       PRJNA992237
1739 SRR25204255   SRP448120       PRJNA992237
1740 SRR25204256   SRP448120       PRJNA992237
1741 SRR25204257   SRP448120       PRJNA992237
1742 SRR25204258   SRP448120       PRJNA992237
1743 SRR25204259   SRP448120       PRJNA992237
1744 SRR25204260   SRP448120       PRJNA992237
1745 SRR25204261   SRP448120       PRJNA992237
     study.title
1    Allometric scaling of RNA abundance from genes to communities
2    Allometric scaling of RNA abundance from genes to communities
3    Allometric scaling of RNA abundance from genes to communities
4    Allometric scaling of RNA abundance from genes to communities
5    Allometric scaling of RNA abundance from genes to communities
6    Allometric scaling of RNA abundance from genes to communities
7    Allometric scaling of RNA abundance from genes to communities
8    Allometric scaling of RNA abundance from genes to communities
9    Allometric scaling of RNA abundance from genes to communities
10   Allometric scaling of RNA abundance from genes to communities
11   Allometric scaling of RNA abundance from genes to communities
12   Allometric scaling of RNA abundance from genes to communities
13   Allometric scaling of RNA abundance from genes to communities
14   Allometric scaling of RNA abundance from genes to communities
15   Allometric scaling of RNA abundance from genes to communities
16   Allometric scaling of RNA abundance from genes to communities
17   Allometric scaling of RNA abundance from genes to communities
18   Allometric scaling of RNA abundance from genes to communities
19   Zebrafish EN/ENCDC RNA seq
20   Zebrafish EN/ENCDC RNA seq
21   Zebrafish EN/ENCDC RNA seq
22   RNAseq from mature ductal cells from nkx6.1:GFP zebrafish lines
23   RNAseq from mature ductal cells from nkx6.1:GFP zebrafish lines
24   RNAseq from mature ductal cells from nkx6.1:GFP zebrafish lines
25   RNAseq from the pancreatic acinar  alpha  beta and delta cells from zebrafish
26   RNAseq from the pancreatic acinar  alpha  beta and delta cells from zebrafish
27   RNAseq from the pancreatic acinar  alpha  beta and delta cells from zebrafish
28   RNAseq from the pancreatic acinar  alpha  beta and delta cells from zebrafish
29   RNAseq from the pancreatic acinar  alpha  beta and delta cells from zebrafish
30   RNAseq from the pancreatic acinar  alpha  beta and delta cells from zebrafish
⋮    ⋮
1716 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1717 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1718 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1719 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1720 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1721 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1722 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1723 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1724 Trim2b mediates protection against SVCV infection by degrading NLRP12 like and viral SVCV N/SVCV G proteins
1725 The effects of broflanilide on developing zebrafish
1726 The effects of broflanilide on developing zebrafish
1727 The effects of broflanilide on developing zebrafish
1728 The effects of broflanilide on developing zebrafish
1729 The effects of broflanilide on developing zebrafish
1730 The effects of broflanilide on developing zebrafish
1731 The effects of broflanilide on developing zebrafish
1732 The effects of broflanilide on developing zebrafish
1733 The effects of broflanilide on developing zebrafish
1734 The effects of broflanilide on developing zebrafish
1735 The effects of broflanilide on developing zebrafish
1736 The effects of broflanilide on developing zebrafish
1737 Danio rerio Raw sequence reads
1738 Danio rerio Raw sequence reads
1739 Danio rerio Raw sequence reads
1740 Danio rerio Raw sequence reads
1741 Danio rerio Raw sequence reads
1742 Danio rerio Raw sequence reads
1743 Danio rerio Raw sequence reads
1744 Danio rerio Raw sequence reads
1745 Danio rerio Raw sequence reads
     sample.accession experiment.accession earliest_date devstage_curation
1    DRS217313        DRX323973            2021-12-23    Adult
2    DRS217312        DRX323972            2021-12-23    Adult
3    DRS217311        DRX323971            2021-12-23    Adult
4    DRS217310        DRX323970            2021-12-23    Adult
5    DRS217309        DRX323969            2021-12-23    Adult
6    DRS217308        DRX323968            2021-12-23    Adult
7    DRS217307        DRX323967            2021-12-23    Adult
8    DRS217306        DRX323966            2021-12-23    Adult
9    DRS217305        DRX323965            2021-12-23    Adult
10   DRS217304        DRX323964            2021-12-23    Adult
11   DRS217303        DRX323963            2021-12-23    Adult
12   DRS217302        DRX323962            2021-12-23    Adult
13   DRS217318        DRX323961            2021-12-23    Adult
14   DRS217317        DRX323960            2021-12-23    Adult
15   DRS217316        DRX323959            2021-12-23    Adult
16   DRS217315        DRX323958            2021-12-23    Adult
17   DRS217314        DRX323957            2021-12-23    Adult
18   DRS217301        DRX323956            2021-12-23    Adult
19   DRS407176        DRX393851            2024-09-22    Undetermined
20   DRS407175        DRX393850            2024-09-22    Undetermined
21   DRS407174        DRX393849            2024-09-22    Undetermined
22   ERS805483        ERX1054382           2015-08-05    Adult
23   ERS805482        ERX1054381           2015-08-05    Adult
24   ERS805481        ERX1054380           2015-08-05    Adult
25   ERS805781        ERX1745976           2015-08-05    Adult
26   ERS805784        ERX1054577           2015-08-05    Adult
27   ERS805783        ERX1054576           2015-08-05    Adult
28   ERS805782        ERX1054575           2015-08-05    Adult
29   ERS805780        ERX1054574           2015-08-05    Adult
30   ERS805779        ERX1054573           2015-08-05    Adult
⋮    ⋮                ⋮                    ⋮             ⋮
1716 SRS17622213      SRX20296169          2023-05-11    Larval
1717 SRS17622209      SRX20296168          2023-05-11    Larval
1718 SRS17622208      SRX20296167          2023-05-11    Larval
1719 SRS17622205      SRX20296166          2023-05-11    Larval
1720 SRS17622206      SRX20296165          2023-05-11    Larval
1721 SRS17622207      SRX20296164          2023-05-11    Larval
1722 SRS17622216      SRX20296163          2023-05-11    Larval
1723 SRS17622215      SRX20296162          2023-05-11    Larval
1724 SRS17622214      SRX20296161          2023-05-11    Larval
1725 SRS18184164      SRX20906947          2023-07-05    Larval
1726 SRS18184159      SRX20906946          2023-07-05    Larval
1727 SRS18184166      SRX20906945          2023-07-05    Larval
1728 SRS18184158      SRX20906944          2023-07-05    Larval
1729 SRS18184160      SRX20906943          2023-07-05    Larval
1730 SRS18184163      SRX20906942          2023-07-05    Larval
1731 SRS18184157      SRX20906941          2023-07-05    Larval
1732 SRS18184154      SRX20906940          2023-07-05    Larval
1733 SRS18184155      SRX20906939          2023-07-05    Larval
1734 SRS18184162      SRX20906938          2023-07-05    Larval
1735 SRS18184161      SRX20906937          2023-07-05    Larval
1736 SRS18184156      SRX20906936          2023-07-05    Larval
1737 SRS18227788      SRX20951228          2023-07-08    Larval
1738 SRS18227789      SRX20951227          2023-07-08    Larval
1739 SRS18227787      SRX20951226          2023-07-08    Larval
1740 SRS18227786      SRX20951225          2023-07-08    Larval
1741 SRS18227784      SRX20951224          2023-07-08    Larval
1742 SRS18227785      SRX20951223          2023-07-08    Larval
1743 SRS18227783      SRX20951222          2023-07-08    Larval
1744 SRS18227782      SRX20951221          2023-07-08    Larval
1745 SRS18227781      SRX20951220          2023-07-08    Larval
     devstage_curation_coarse tissue_curation ⋯ run.Ccount run.Gcount
1    Adult                    Undetermined    ⋯  926887571  898697642
2    Adult                    Undetermined    ⋯  702936549  679920984
3    Adult                    Undetermined    ⋯  791315678  766594599
4    Adult                    Undetermined    ⋯  733754277  715270279
5    Adult                    Undetermined    ⋯  825478743  804835148
6    Adult                    Undetermined    ⋯  954687406  929537615
7    Adult                    Undetermined    ⋯  738814269  712866126
8    Adult                    Undetermined    ⋯  794741415  771082024
9    Adult                    Undetermined    ⋯  814578518  787469614
10   Adult                    Undetermined    ⋯  752748024  759884392
11   Adult                    Undetermined    ⋯  749873295  756284406
12   Adult                    Undetermined    ⋯  610675892  617869465
13   Adult                    Undetermined    ⋯  734660854  739230475
14   Adult                    Undetermined    ⋯  742872021  750053514
15   Adult                    Undetermined    ⋯  692014182  696272089
16   Adult                    Undetermined    ⋯  625686885  631010166
17   Adult                    Undetermined    ⋯  615324906  621209484
18   Adult                    Undetermined    ⋯  675761096  678969165
19   Larval                   Undetermined    ⋯  879988139  903976580
20   Larval                   Undetermined    ⋯  778042505  798459853
21   Larval                   Undetermined    ⋯  705895776  724185148
22   Adult                    Undetermined    ⋯ 2759135663 2772107550
23   Adult                    Undetermined    ⋯ 3245710338 3382410145
24   Adult                    Undetermined    ⋯ 1435392327 1491979725
25   Adult                    Undetermined    ⋯ 2448656972 2434247998
26   Adult                    Undetermined    ⋯ 3974803883 4029409265
27   Adult                    Undetermined    ⋯ 3700546898 3749520213
28   Adult                    Undetermined    ⋯  824702298  830498571
29   Adult                    Undetermined    ⋯ 2076658898 2097686086
30   Adult                    Undetermined    ⋯  562486325  570096367
⋮    ⋮                        ⋮               ⋱ ⋮          ⋮
1716 Larval                   Undetermined    ⋯ 1657749252 1683099090
1717 Larval                   Undetermined    ⋯ 1678649361 1700066381
1718 Larval                   Undetermined    ⋯ 1561530930 1580425572
1719 Larval                   Undetermined    ⋯ 1378143902 1397930058
1720 Larval                   Undetermined    ⋯ 1375116718 1397748981
1721 Larval                   Undetermined    ⋯ 1428154837 1450804881
1722 Larval                   Undetermined    ⋯ 1580919201 1602574620
1723 Larval                   Undetermined    ⋯ 1507987394 1532101693
1724 Larval                   Undetermined    ⋯ 1459940320 1480166756
1725 Larval                   Undetermined    ⋯ 1644260948 1637773337
1726 Larval                   Undetermined    ⋯ 1590039257 1582452542
1727 Larval                   Undetermined    ⋯ 1893088277 1881915860
1728 Larval                   Undetermined    ⋯ 2183820603 2173234184
1729 Larval                   Undetermined    ⋯ 1362384976 1359250005
1730 Larval                   Undetermined    ⋯ 2025003234 2015716402
1731 Larval                   Undetermined    ⋯ 1511638242 1507512994
1732 Larval                   Undetermined    ⋯ 1962167435 1952766294
1733 Larval                   Undetermined    ⋯ 1547948508 1536813022
1734 Larval                   Undetermined    ⋯ 1455145891 1445644648
1735 Larval                   Undetermined    ⋯ 1696218292 1690719844
1736 Larval                   Undetermined    ⋯ 1798775465 1785485903
1737 Larval                   Undetermined    ⋯ 2032526244 2114078273
1738 Larval                   Undetermined    ⋯ 1651512663 1729908592
1739 Larval                   Undetermined    ⋯ 1871228929 1936430185
1740 Larval                   Undetermined    ⋯ 1865787204 1931889271
1741 Larval                   Undetermined    ⋯ 1938384185 2018262699
1742 Larval                   Undetermined    ⋯ 1682144847 1758829885
1743 Larval                   Undetermined    ⋯ 1661281561 1757033088
1744 Larval                   Undetermined    ⋯ 1639682770 1725383993
1745 Larval                   Undetermined    ⋯ 1878920378 1955076309
     run.Tcount run.Ncount run.experiment run.pool_member experiment.study_ref
1     998107868        174 DRX323973      DRS217313       DRP008001
2     718646067        599 DRX323972      DRS217312       DRP008001
3     805780465        458 DRX323971      DRS217311       DRP008001
4     711475544        386 DRX323970      DRS217310       DRP008001
5     792466124        199 DRX323969      DRS217309       DRP008001
6     895107890        417 DRX323968      DRS217308       DRP008001
7     793876235        343 DRX323967      DRS217307       DRP008001
8     784363609        170 DRX323966      DRS217306       DRP008001
9     811734581        210 DRX323965      DRS217305       DRP008001
10    828182261        420 DRX323964      DRS217304       DRP008001
11    830635394        206 DRX323963      DRS217303       DRP008001
12    682003195        157 DRX323962      DRS217302       DRP008001
13    828963220        532 DRX323961      DRS217318       DRP008001
14    841942389        235 DRX323960      DRS217317       DRP008001
15    766749729        202 DRX323959      DRS217316       DRP008001
16    674461210        334 DRX323958      DRS217315       DRP008001
17    688756167        148 DRX323957      DRS217314       DRP008001
18    763212637        145 DRX323956      DRS217301       DRP008001
19    962122970    4958821 DRX393851      DRS407176       DRP012042
20    859611841    5910184 DRX393850      DRS407175       DRP012042
21    775760738    5606315 DRX393849      DRS407174       DRP012042
22   3905748607 1048961339 ERX1054382     ERS805483       ERP011343
23   5701198546   90957928 ERX1054381     ERS805482       ERP011343
24   2755195660   42883432 ERX1054380     ERS805481       ERP011343
25   2833404838   75855708 ERX1745976     ERS805781       ERP011346
26   4779969672   81832122 ERX1054577     ERS805784       ERP011346
27   4395516227   76504549 ERX1054576     ERS805783       ERP011346
28    958264119     384386 ERX1054575     ERS805782       ERP011346
29   2672752253  159387303 ERX1054574     ERS805780       ERP011346
30    643677230      75628 ERX1054573     ERS805779       ERP011346
⋮    ⋮          ⋮          ⋮              ⋮               ⋮
1716 1900841390  72673     SRX20296169    SRS17622213     SRP437162
1717 1895101096  73721     SRX20296168    SRS17622209     SRP437162
1718 1767705366  62729     SRX20296167    SRS17622208     SRP437162
1719 1545345688  22471     SRX20296166    SRS17622205     SRP437162
1720 1544008759  22399     SRX20296165    SRS17622206     SRP437162
1721 1629615795  23699     SRX20296164    SRS17622207     SRP437162
1722 1826626759  69912     SRX20296163    SRS17622216     SRP437162
1723 1707819337  65621     SRX20296162    SRS17622215     SRP437162
1724 1673343035  63514     SRX20296161    SRS17622214     SRP437162
1725 1899982712 117076     SRX20906947    SRS18184164     SRP447562
1726 1779517158 110121     SRX20906946    SRS18184159     SRP447562
1727 2345216790 143635     SRX20906945    SRS18184166     SRP447562
1728 2470867546 114143     SRX20906944    SRS18184158     SRP447562
1729 1570453936  83504     SRX20906943    SRS18184160     SRP447562
1730 2342482424 137369     SRX20906942    SRS18184163     SRP447562
1731 1764173234 105472     SRX20906941    SRS18184157     SRP447562
1732 2331863687 144042     SRX20906940    SRS18184154     SRP447562
1733 1774624688 111522     SRX20906939    SRS18184155     SRP447562
1734 1695353403  65240     SRX20906938    SRS18184162     SRP447562
1735 2106801214  94600     SRX20906937    SRS18184161     SRP447562
1736 2144526098  96228     SRX20906936    SRS18184156     SRP447562
1737 2136804263  64107     SRX20951228    SRS18227788     SRP448120
1738 1751362435  49851     SRX20951227    SRS18227789     SRP448120
1739 1959940726  59407     SRX20951226    SRS18227787     SRP448120
1740 1943679942  57848     SRX20951225    SRS18227786     SRP448120
1741 2062351129  59671     SRX20951224    SRS18227784     SRP448120
1742 1804752117  54670     SRX20951223    SRS18227785     SRP448120
1743 1802327080  54122     SRX20951222    SRS18227783     SRP448120
1744 1742476809  51954     SRX20951221    SRS18227782     SRP448120
1745 1976502641  59757     SRX20951220    SRS18227781     SRP448120
     sample.centername           submission.accession
1    NA                          DRA013226
2    NA                          DRA013226
3    NA                          DRA013226
4    NA                          DRA013226
5    NA                          DRA013226
6    NA                          DRA013226
7    NA                          DRA013226
8    NA                          DRA013226
9    NA                          DRA013226
10   NA                          DRA013226
11   NA                          DRA013226

In [129]:
metadata_curationstep14fewer_unknown <- metadata_curationstep14fewer %>% filter(devstage_curation_coarse == "Undetermined" | tissue_curation_coarse == "Undetermined")
metadata_curationstep14fewer_unknown
write.table(metadata_curationstep14fewer_unknown, file = paste0("all_zf_dates_devstage_tissue_tech_curated_unknown.tsv"), sep = "\t", row.names = FALSE, quote = FALSE)

     run.accession study.accession bioproject
1    DRR334977     DRP008001       PRJDB12578
2    DRR334976     DRP008001       PRJDB12578
3    DRR334975     DRP008001       PRJDB12578
4    DRR334974     DRP008001       PRJDB12578
5    DRR334973     DRP008001       PRJDB12578
6    DRR334972     DRP008001       PRJDB12578
7    DRR334971     DRP008001       PRJDB12578
8    DRR334970     DRP008001       PRJDB12578
9    DRR334969     DRP008001       PRJDB12578
10   DRR334968     DRP008001       PRJDB12578
11   DRR334967     DRP008001       PRJDB12578
12   DRR334966     DRP008001       PRJDB12578
13   DRR334965     DRP008001       PRJDB12578
14   DRR334964     DRP008001       PRJDB12578
15   DRR334963     DRP008001       PRJDB12578
16   DRR334962     DRP008001       PRJDB12578
17   DRR334961     DRP008001       PRJDB12578
18   DRR334960     DRP008001       PRJDB12578
19   DRR408245     DRP012042       PRJDB14275
20   DRR408244     DRP012042       PRJDB14275
21   DRR408243     DRP012042       PRJDB14275
22   DRR050167     DRP003043       PRJDB4416
23   DRR050166     DRP003043       PRJDB4416
24   DRR050165     DRP003043       PRJDB4416
25   DRR050164     DRP003043       PRJDB4416
26   DRR050163     DRP003043       PRJDB4416
27   DRR050162     DRP003043       PRJDB4416
28   DRR051067     DRP003977       PRJDB4470
29   DRR051063     DRP003977       PRJDB4470
30   ERR977399     ERP011343       PRJEB10137
⋮    ⋮             ⋮               ⋮
5129 SRR25247935   SRP448831       PRJNA994052
5130 SRR25247937   SRP448831       PRJNA994052
5131 SRR25247938   SRP448831       PRJNA994052
5132 SRR25247939   SRP448831       PRJNA994052
5133 SRR25247940   SRP448831       PRJNA994052
5134 SRR25247944   SRP448831       PRJNA994052
5135 SRR25247941   SRP448831       PRJNA994052
5136 SRR25247942   SRP448831       PRJNA994052
5137 SRR25247943   SRP448831       PRJNA994052
5138 SRR25247945   SRP448831       PRJNA994052
5139 SRR25247946   SRP448831       PRJNA994052
5140 SRR25247947   SRP448831       PRJNA994052
5141 SRR25247948   SRP448831       PRJNA994052
5142 SRR25253548   SRP449239       PRJNA994180
5143 SRR25253549   SRP449239       PRJNA994180
5144 SRR25253550   SRP449239       PRJNA994180
5145 SRR25253551   SRP449239       PRJNA994180
5146 SRR25253552   SRP449239       PRJNA994180
5147 SRR25253553   SRP449239       PRJNA994180
5148 SRR25253554   SRP449239       PRJNA994180
5149 SRR25253555   SRP449239       PRJNA994180
5150 SRR25288286   SRP449631       PRJNA994919
5151 SRR25288287   SRP449631       PRJNA994919
5152 SRR25288288   SRP449631       PRJNA994919
5153 SRR25320257   SRP450092       PRJNA996066
5154 SRR25320258   SRP450092       PRJNA996066
5155 SRR25320259   SRP450092       PRJNA996066
5156 SRR25320260   SRP450092       PRJNA996066
5157 SRR25320261   SRP450092       PRJNA996066
5158 SRR25320262   SRP450092       PRJNA996066
     study.title
1    Allometric scaling of RNA abundance from genes to communities
2    Allometric scaling of RNA abundance from genes to communities
3    Allometric scaling of RNA abundance from genes to communities
4    Allometric scaling of RNA abundance from genes to communities
5    Allometric scaling of RNA abundance from genes to communities
6    Allometric scaling of RNA abundance from genes to communities
7    Allometric scaling of RNA abundance from genes to communities
8    Allometric scaling of RNA abundance from genes to communities
9    Allometric scaling of RNA abundance from genes to communities
10   Allometric scaling of RNA abundance from genes to communities
11   Allometric scaling of RNA abundance from genes to communities
12   Allometric scaling of RNA abundance from genes to communities
13   Allometric scaling of RNA abundance from genes to communities
14   Allometric scaling of RNA abundance from genes to communities
15   Allometric scaling of RNA abundance from genes to communities
16   Allometric scaling of RNA abundance from genes to communities
17   Allometric scaling of RNA abundance from genes to communities
18   Allometric scaling of RNA abundance from genes to communities
19   Zebrafish EN/ENCDC RNA seq
20   Zebrafish EN/ENCDC RNA seq
21   Zebrafish EN/ENCDC RNA seq
22   Transcriptome analysis in ES1 expressing rods of zebrafish
23   Transcriptome analysis in ES1 expressing rods of zebrafish
24   Transcriptome analysis in ES1 expressing rods of zebrafish
25   Transcriptome analysis in ES1 expressing rods of zebrafish
26   Transcriptome analysis in ES1 expressing rods of zebrafish
27   Transcriptome analysis in ES1 expressing rods of zebrafish
28   Gene expression analysis of the zebrafish brain
29   Gene expression analysis of the zebrafish brain
30   RNAseq from mature ductal cells from nkx6.1:GFP zebrafish lines
⋮    ⋮
5129 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5130 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5131 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5132 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5133 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5134 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5135 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5136 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5137 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5138 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5139 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5140 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5141 Dynamic Changes in Lymphocyte Populations Establish Zebrafish as a Thymic Involution Model
5142 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5143 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5144 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5145 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5146 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5147 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5148 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5149 Evolution of neuronal cell classes and types in the vertebrate retina [Zebrafish]
5150 Diverse Epithelial Lymphocytes in Zebrafish Revealed Using a Novel Scale Biopsy Method
5151 Diverse Epithelial Lymphocytes in Zebrafish Revealed Using a Novel Scale Biopsy Method
5152 Diverse Epithelial Lymphocytes in Zebrafish Revealed Using a Novel Scale Biopsy Method
5153 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
5154 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
5155 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
5156 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
5157 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
5158 Multi omics analysis of zebrafish response to tick saliva reveals biological processes associated with alpha Gal syndrome
     sample.accession experiment.accession earliest_date devstage_curation
1    DRS217313        DRX323973            2021-12-23    Adult
2    DRS217312        DRX323972            2021-12-23    Adult
3    DRS217311        DRX323971            2021-12-23    Adult
4    DRS217310        DRX323970            2021-12-23    Adult
5    DRS217309        DRX323969            2021-12-23    Adult
6    DRS217308        DRX323968            2021-12-23    Adult
7    DRS217307        DRX323967            2021-12-23    Adult
8    DRS217306        DRX323966            2021-12-23    Adult
9    DRS217305        DRX323965            2021-12-23    Adult
10   DRS217304        DRX323964            2021-12-23    Adult
11   DRS217303        DRX323963            2021-12-23    Adult
12   DRS217302        DRX323962            2021-12-23    Adult
13   DRS217318        DRX323961            2021-12-23    Adult
14   DRS217317        DRX323960            2021-12-23    Adult
15   DRS217316        DRX323959            2021-12-23    Adult
16   DRS217315        DRX323958            2021-12-23    Adult
17   DRS217314        DRX323957            2021-12-23    Adult
18   DRS217301        DRX323956            2021-12-23    Adult
19   DRS407176        DRX393851            2024-09-22    Undetermined
20   DRS407175        DRX393850            2024-09-22    Undetermined
21   DRS407174        DRX393849            2024-09-22    Undetermined
22   DRS025834        DRX045209            2016-03-09    Undetermined
23   DRS025833        DRX045208            2016-03-09    Undetermined
24   DRS025832        DRX045207            2016-03-09    Undetermined
25   DRS025831        DRX045206            2016-03-09    Undetermined
26   DRS025830        DRX045205            2016-03-09    Undetermined
27   DRS025829        DRX045204            2016-03-09    Undetermined
28   DRS057267        DRX045959            2018-01-06    Undetermined
29   DRS057266        DRX045955            2018-01-06    Undetermined
30   ERS805483        ERX1054382           2015-08-05    Adult
⋮    ⋮                ⋮                    ⋮             ⋮
5129 SRS18268478      SRX20994072          2023-07-12    Undetermined
5130 SRS18268479      SRX20994071          2023-07-12    Undetermined
5131 SRS18268477      SRX20994070          2023-07-12    Undetermined
5132 SRS18268476      SRX20994069          2023-07-12    Undetermined
5133 SRS18268475      SRX20994068          2023-07-12    Undetermined
5134 SRS18268474      SRX20994067          2023-07-12    Undetermined
5135 SRS18268473      SRX20994066          2023-07-12    Undetermined
5136 SRS18268472      SRX20994065          2023-07-12    Undetermined
5137 SRS18268471      SRX20994064          2023-07-12    Undetermined
5138 SRS18268470      SRX20994063          2023-07-12    Undetermined
5139 SRS18268469      SRX20994062          2023-07-12    Undetermined
5140 SRS18268468      SRX20994061          2023-07-12    Undetermined
5141 SRS18268467      SRX20994060          2023-07-12    Undetermined
5142 SRS18272874      SRX20999601          2023-07-12    Undetermined
5143 SRS18272873      SRX20999600          2023-07-12    Undetermined
5144 SRS18272872      SRX20999599          2023-07-12    Undetermined
5145 SRS18272871      SRX20999598          2023-07-12    Undetermined
5146 SRS18272870      SRX20999597          2023-07-12    Undetermined
5147 SRS18272869      SRX20999596          2023-07-12    Undetermined
5148 SRS18272868      SRX20999595          2023-07-12    Undetermined
5149 SRS18272867      SRX20999594          2023-07-12    Undetermined
5150 SRS18304345      SRX21031899          2023-07-14    Undetermined
5151 SRS18304344      SRX21031898          2023-07-14    Undetermined
5152 SRS18304343      SRX21031897          2023-07-14    Undetermined
5153 SRS18332761      SRX21062493          2023-07-18    Undetermined
5154 SRS18332759      SRX21062492          2023-07-18    Undetermined
5155 SRS18332760      SRX21062491          2023-07-18    Undetermined
5156 SRS18332758      SRX21062490          2023-07-18    Undetermined
5157 SRS18332757      SRX21062489          2023-07-18    Undetermined
5158 SRS18332756      SRX21062488          2023-07-18    Undetermined
     devstage_curation_coarse tissue_curation ⋯ run.Ccount run.Gcount
1    Adult                    Undetermined    ⋯  926887571  898697642
2    Adult                    Undetermined    ⋯  702936549  679920984
3    Adult                    Undetermined    ⋯  791315678  766594599
4    Adult                    Undetermined    ⋯  733754277  715270279
5    Adult                    Undetermined    ⋯  825478743  804835148
6    Adult                    Undetermined    ⋯  954687406  929537615
7    Adult                    Undetermined    ⋯  738814269  712866126
8    Adult                    Undetermined    ⋯  794741415  771082024
9    Adult                    Undetermined    ⋯  814578518  787469614
10   Adult                    Undetermined    ⋯  752748024  759884392
11   Adult                    Undetermined    ⋯  749873295  756284406
12   Adult                    Undetermined    ⋯  610675892  617869465
13   Adult                    Undetermined    ⋯  734660854  739230475
14   Adult                    Undetermined    ⋯  742872021  750053514
15   Adult                    Undetermined    ⋯  692014182  696272089
16   Adult                    Undetermined    ⋯  625686885  631010166
17   Adult                    Undetermined    ⋯  615324906  621209484
18   Adult                    Undetermined    ⋯  675761096  678969165
19   Larval                   Undetermined    ⋯  879988139  903976580
20   Larval                   Undetermined    ⋯  778042505  798459853
21   Larval                   Undetermined    ⋯  705895776  724185148
22   Undetermined             Fin             ⋯   79475572   83520360
23   Undetermined             Fin             ⋯   86415371   90822163
24   Undetermined             Fin             ⋯  129885620  136727379
25   Undetermined             Fin             ⋯   73070267   77738821
26   Undetermined             Fin             ⋯  113928273  120051739
27   Undetermined             Fin             ⋯  104872341  113114502
28   Undetermined             Brain           ⋯ 3957379257 3797879751
29   Undetermined             Brain           ⋯ 3082552426 3134669086
30   Adult                    Undetermined    ⋯ 2759135663 2772107550
⋮    ⋮                        ⋮               ⋱ ⋮          ⋮
5129 Undetermined             Marrow          ⋯ 1520031310 1849059138
5130 Undetermined             Marrow          ⋯ 1802515744 2029257538
5131 Undetermined             Marrow          ⋯ 1639877964 1850759915
5132 Undetermined             Marrow          ⋯ 1520823030 1694205993
5133 Undetermined             Marrow          ⋯ 1669568274 1858403783
5134 Undetermined             Marrow          ⋯ 1744556837 1930871463
5135 Undetermined             Marrow          ⋯ 1527167803 1677900707
5136 Undetermined             Thymus          ⋯ 1601232886 1787641759
5137 Undetermined             Thymus          ⋯ 1558094669 1747369217
5138 Undetermined             Thymus          ⋯ 1690333059 1912063529
5139 Undetermined             Thymus          ⋯ 1804435410 2009975925
5140 Undetermined             Thymus          ⋯ 1702138319 1938033936
5141 Undetermined             Thymus          ⋯ 1886184090 2274314822
5142 Undetermined             Eye             ⋯ 1687426244 1785339875
5143 Undetermined             Eye             ⋯ 1077631009 1137108891
5144 Undetermined             Eye             ⋯ 1039410282 1103144747
5145 Undetermined             Eye             ⋯ 1128470469 1198385405
5146 Undetermined             Eye             ⋯  751206133  783572508
5147 Undetermined             Eye             ⋯  788484354  823319620
5148 Undetermined             Eye             ⋯ 1233227329 1289921693
5149 Undetermined             Eye             ⋯ 1274004687 1327972080
5150 Undetermined             Scale           ⋯ 2322303742 2574066837
5151 Undetermined             Multi-tissue    ⋯ 2439333260 2665663309
5152 Undetermined             Thymus          ⋯ 2208968733 2525266634
5153 Undetermined             Gut             ⋯ 2108316310 2611487888
5154 Undetermined             Gut             ⋯ 3613697125 4175903766
5155 Undetermined             Gut             ⋯ 2385768928 2685002752
5156 Undetermined             Gut             ⋯ 2385685766 2716165649
5157 Undetermined             Gut             ⋯ 2496955346 2795939748
5158 Undetermined             Gut             ⋯ 2461578237 2848406965
     run.Tcount run.Ncount run.experiment run.pool_member experiment.study_ref
1     998107868        174 DRX323973      DRS217313       DRP008001
2     718646067        599 DRX323972      DRS217312       DRP008001
3     805780465        458 DRX323971      DRS217311       DRP008001
4     711475544        386 DRX323970      DRS217310       DRP008001
5     792466124        199 DRX323969      DRS217309       DRP008001
6     895107890        417 DRX323968      DRS217308       DRP008001
7     793876235        343 DRX323967      DRS217307       DRP008001
8     784363609        170 DRX323966      DRS217306       DRP008001
9     811734581        210 DRX323965      DRS217305       DRP008001
10    828182261        420 DRX323964      DRS217304       DRP008001
11    830635394        206 DRX323963      DRS217303       DRP008001
12    682003195        157 DRX323962      DRS217302       DRP008001
13    828963220        532 DRX323961      DRS217318       DRP008001
14    841942389        235 DRX323960      DRS217317       DRP008001
15    766749729        202 DRX323959      DRS217316       DRP008001
16    674461210        334 DRX323958      DRS217315       DRP008001
17    688756167        148 DRX323957      DRS217314       DRP008001
18    763212637        145 DRX323956      DRS217301       DRP008001
19    962122970    4958821 DRX393851      DRS407176       DRP012042
20    859611841    5910184 DRX393850      DRS407175       DRP012042
21    775760738    5606315 DRX393849      DRS407174       DRP012042
22    101561779          0 DRX045209      DRS025834       DRP003043
23    121670773          0 DRX045208      DRS025833       DRP003043
24    153657736          0 DRX045207      DRS025832       DRP003043
25     92783592          0 DRX045206      DRS025831       DRP003043
26    146481242          0 DRX045205      DRS025830       DRP003043
27    123927858          0 DRX045204      DRS025829       DRP003043
28   5144366288    4618438 DRX045959      DRS057267       DRP003977
29   4606055524    5037798 DRX045955      DRS057266       DRP003977
30   3905748607 1048961339 ERX1054382     ERS805483       ERP011343
⋮    ⋮          ⋮          ⋮              ⋮               ⋮
5129 2280354641   31300    SRX20994072    SRS18268478     SRP448831
5130 3030992999   38416    SRX20994071    SRS18268479     SRP448831
5131 2689649693   34194    SRX20994070    SRS18268477     SRP448831
5132 2537855107   32317    SRX20994069    SRS18268476     SRP448831
5133 2815553963   35738    SRX20994068    SRS18268475     SRP448831
5134 2836881708   35911    SRX20994067    SRS18268474     SRP448831
5135 2446333840   31681    SRX20994066    SRS18268473     SRP448831
5136 2580087936   33513    SRX20994065    SRS18268472     SRP448831
5137 2514010546   32402    SRX20994064    SRS18268471     SRP448831
5138 2635521209   34284    SRX20994063    SRS18268470     SRP448831
5139 3001626142   38381    SRX20994062    SRS18268469     SRP448831
5140 2901841449   36802    SRX20994061    SRS18268468     SRP448831
5141 2665699767   37990    SRX20994060    SRS18268467     SRP448831
5142 2616019593 1816455    SRX20999601    SRS18272874     SRP449239
5143 1679156666 1135302    SRX20999600    SRS18272873     SRP449239
5144 1685792809 1154423    SRX20999599    SRS18272872     SRP449239
5145 1871305613 1288123    SRX20999598    SRS18272871     SRP449239
5146 1216050370  816882    SRX20999597    SRS18272870     SRP449239
5147 1297264565  884334    SRX20999596    SRS18272869     SRP449239
5148 1921011454 1016257    SRX20999595    SRS18272868     SRP449239
5149 1988461414 1050023    SRX20999594    SRS18272867     SRP449239
5150 2662358757  133293    SRX21031899    SRS18304345     SRP449631

In [130]:
n_distinct(metadata_curationstep14fewer$bioproject)
n_distinct(metadata_curationstep14fewer$submission.accession)

[1] 2469

[1] 3032